Error on source files with unicode directional formatting characters
scala/scala pull request #10017
Opened 2022-04-26 14:22 UTC by lrytz

Don't allow characters with unicode property `Bidi_Class` in source files.

Fixes https://github.com/scala/bug/issues/12478

2022-04-26 15:06 UTC, som-snytt commented
I forgot to joke on the ticket that most Scala allows you:

> to write code that looks like it does one thing, but actually does another

Oh, I also forgot to joke that we should allow bidi under `-language:postfixOps` where you write them as prefix ops.

I half-expected or half-hoped that this check would leverage the supplementary char check, except erroring. But that would only be useful if the special chars were allowed directly in literals.

Also code comments. I don't think it cares about badly formed chars in comments, but I did not check.

I might expect the error message to show me the decoded text. Github says, Go get yourself an editor that will display the hidden codes to you.

2022-04-26 20:32 UTC, lrytz commented
@sjrd could you maybe review this?

2022-04-26 21:37 UTC, som-snytt approved these changes
It's a simple mechanism, so they will slip no bidi chars past the goalie.

2022-04-27 11:22 UTC, sjrd requested changes

2022-04-27 11:22 UTC, sjrd commented on src/reflect/scala/reflect/internal/Chars.scala
> +         '\u2066' | '\u2067' | '\u2068' | '\u2069' => true
I think we should forbid all 25 characters with the Unicode property `Bidi_Control`, as defined in `PropList.txt`:
https://www.unicode.org/Public/UCD/latest/ucd/PropList.txt

The [original vulnerability report](https://trojansource.codes/trojan-source.pdf) only mentions those 9 code points in Table I, sure, but it does refer to the Unicode specification for "the Complete list", and that goes to https://www.unicode.org/reports/tr9/tr9-42.html#Directional_Formatting_Characters, which says that all the involved characters have the property `Bidi_Control`.

2022-04-27 12:03 UTC, lrytz commented on src/reflect/scala/reflect/internal/Chars.scala
> +         '\u2066' | '\u2067' | '\u2068' | '\u2069' => true
👍  -- though they are 12, not 25, right?

2022-04-27 12:51 UTC, sjrd commented on src/reflect/scala/reflect/internal/Chars.scala
> +         '\u2066' | '\u2067' | '\u2068' | '\u2069' => true
Er yes 12, indeed.

2022-04-27 12:52 UTC, sjrd approved these changes

2022-05-02 11:33 UTC, merged

2022-05-03 07:30 UTC, lrytz commented
Backport to 2.12 is not trivial because 2.12 eagerly interpretes `\u` escapes in the scanner, so i don't know how to let the escapes pass in string / char literals.

https://github.com/scala/scala/blob/7dbc139b4a113c18e99e8720b985a249fc9b181f/src/compiler/scala/tools/nsc/util/CharArrayReader.scala#L82

2022-05-03 07:31 UTC, lrytz commented
I guess just let any escapes pass on 2.12, just error if the codepoints appear in the file.

2022-05-09 11:10 UTC, lrytz commented on src/reflect/scala/reflect/internal/Chars.scala
> +         '\u2066' | '\u2067' | '\u2068' | '\u2069' => true
@sjrd maybe we were a bit too eager here? The paper says "Table I provides a list of Bidi override characters relevant to this attack". I guess by "complete list" they meant "complete list of directional formatting characters", not "complete list of characters that can be exploited".

The community build found a few `U+200E` "left-to-right mark" characters here (accidental I assume, they don't serve any purpose): https://github.com/monix/monix/blob/ec5555c28406b21f785e7141970765c729988810/monix-eval/shared/src/main/scala/monix/eval/Coeval.scala#L40. They are not flagged by GitHub, for example. VS Code screenshot:

<img width="877" alt="image" src="https://user-images.githubusercontent.com/119636/167397751-8a01d614-2021-4c98-b8a5-d0f6b8c66cc2.png">

There's an example on Wikipedia showing where such marks are needed: https://en.wikipedia.org/wiki/Bidirectional_text#Marks. Could be relevant when using other alphabets in scaladoc comments.

2022-05-09 12:14 UTC, sjrd commented on src/reflect/scala/reflect/internal/Chars.scala
> +         '\u2066' | '\u2067' | '\u2068' | '\u2069' => true
Ah yes, you are right, indeed.

2022-05-09 13:22 UTC, SethTisue commented
adjusted a bit by #10030