Reflect future status of `App` in scaladoc
scala/scala pull request #10070
Opened 2022-07-08 19:16 UTC by armanbilge

To match Dotty documenation at https://github.com/lampepfl/dotty/blob/8bae490bb513c4ce78812ff721144dfc78dbb430/docs/_docs/reference/changed-features/main-functions.md?plain=1#L86

Since the standard library is shared with Scala 3 seems particularly important to get this information in there?

https://www.scala-lang.org/api/3.1.2/scala/App.html

2022-07-08 19:24 UTC, julienrf reviewed
Thank you @armanbilge. I suggest providing the signature of the `main` method, so that users can just copy-paste it.

2022-07-08 19:24 UTC, julienrf commented on src/library/scala/App.scala
> + *  an `Array[String]` argument instead.
```suggestion
 *  between Scala 2 and Scala 3, it is recommended to use an explicit `main` method:
 *  {{{
 *  object Main {
 *    def main(args: Array[String]): Unit = {
 *      // your program here
 *    }
 *  }
 *  }}}
```

2022-07-11 18:11 UTC, SethTisue commented on src/library/scala/App.scala
> + *  In Scala 3, `App` exists only in a limited form that does not support command line
this makes it sound like the main and perhaps only limitation is the lack of support for command line arguments. but it's equally important that Scala 3 does not implement `DelayedInit`

2022-07-11 18:11 UTC, SethTisue commented on src/library/scala/App.scala
> + *  between Scala 2 and Scala 3, it is recommended to use an explicit `main` method:
it's good to give this good recommendation on how to cross-build, but there are also Scala 3 users who don't care about cross-building, and for those users, our recommendation should be to use `@main`

2022-07-11 18:11 UTC, SethTisue requested changes
some suggested further improvements

2022-07-11 18:34 UTC, armanbilge commented
Thanks, good feedback 👍

2022-07-11 19:14 UTC, SethTisue approved these changes

2022-07-12 07:50 UTC, merged