{get=>find}Resource in some tests
scala/scala pull request #10203
Opened 2022-10-31 13:47 UTC by ansvonwa

This does not call the parent class loader first, which may return different resources if they're on classpath.

fixes scala/bug#12677

2022-10-31 21:28 UTC, som-snytt commented
`findResource` is made public by `java.net.URLClassLoader`.

Probably it's fine.

That line is really only constructing a URL, so even better:
```
private def manifestAt(location: Path): URL = URI.create(s"jar:file:$location!/META-INF/MANIFEST.MF").toURL
```
invoked with just `manifestAt(jar.toAbsolutePath)`. I added `toAbsolutePath` just in case. I tested under linux, I think or assume windows does the right thing.

If it were necessary to go through a class loader, the optimal would be `getResources` and take the resource which is contained by the location.

Also if it were necessary to use a class loader, it would be more natural to use `AbstractFileClassLoader` (which does not have a public `findResource`).

2022-10-31 21:33 UTC, som-snytt requested changes
Suggest creating the URL directly, as we have the file Path and well-known zip entry.

The proposed tweak does avoid delegating to the parent CL.

2022-11-02 13:27 UTC, ansvonwa commented
> The proposed tweak does avoid delegating to the parent CL.

Not sure which of the solutions (yours or mine) you mean, iiuc they both don't delegate to the parent anymore.

Anyway, I think yours looks fine too, so there it is!

2022-11-02 14:15 UTC, som-snytt commented
Thanks again, I meant your tweak, which was also clever and valid.

2022-11-02 14:15 UTC, som-snytt approved these changes

2022-11-02 15:34 UTC, som-snytt commented
@SethTisue is it possible to request a windows test? I remember dotty has a special comment command.

A comment command should be called a commandment.

2022-11-02 15:44 UTC, SethTisue commented
> is it possible to request a windows test?

I hoped this would be possible via the GitHub web UI, and.... well, I think it will be once we merge #10206 and merge it forward onto 2.13.x.

Rather than wait for that, I'm going to merge this now and if it fails on Windows we'll deal with it.

2022-11-02 15:45 UTC, merged

2022-11-02 15:45 UTC, SethTisue commented
Thank you @ansvonwa and @som-snytt !

2022-11-02 16:01 UTC, som-snytt commented
> we'll deal with it.

I'll rely on Seth's strong coping mechanisms.

2022-11-03 06:24 UTC, SethTisue commented
It wasn't our lucky day: https://github.com/scala/scala/actions/runs/3379006847/jobs/5609993160

```
[error] Test scala.tools.nsc.classpath.ZipAndJarFileLookupFactoryTest.manifest classpath entry works failed: java.lang.IllegalArgumentException: Illegal character in opaque part at index 11: jar:file:C:\Users\RUNNER~1\AppData\Local\Temp\junit1086976373254541561.jar!/META-INF/MANIFEST.MF, took 0.0 sec
[3721](https://github.com/scala/scala/actions/runs/3379006847/jobs/5609993160#step:6:3722)
[error]     at java.net.URI.create(URI.java:852)
[3722](https://github.com/scala/scala/actions/runs/3379006847/jobs/5609993160#step:6:3723)
[error]     at scala.tools.nsc.classpath.ZipAndJarFileLookupFactoryTest.manifestAt$1(ZipAndJarFileLookupFactoryTest.scala:84)
[3723](https://github.com/scala/scala/actions/runs/3379006847/jobs/5609993160#step:6:3724)
[error]     at scala.tools.nsc.classpath.ZipAndJarFileLookupFactoryTest.$anonfun$manifest classpath entry works$3(ZipAndJarFileLookupFactoryTest.scala:87)
[3724](https://github.com/scala/scala/actions/runs/3379006847/jobs/5609993160#step:6:3725)
[error]     at scala.tools.nsc.classpath.ZipAndJarFileLookupFactoryTest.manifest classpath entry works(ZipAndJarFileLookupFactoryTest.scala:87)
[3725](https://github.com/scala/scala/actions/runs/3379006847/jobs/5609993160#step:6:3726)
[error]     ...
[3726](https://github.com/scala/scala/actions/runs/3379006847/jobs/5609993160#step:6:3727)
[error] Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 11: jar:file:C:\Users\RUNNER~1\AppData\Local\Temp\junit1086976373254541561.jar!/META-INF/MANIFEST.MF
[3727](https://github.com/scala/scala/actions/runs/3379006847/jobs/5609993160#step:6:3728)
[error]     at java.net.URI$Parser.fail(URI.java:2847)
[3728](https://github.com/scala/scala/actions/runs/3379006847/jobs/5609993160#step:6:3729)
[error]     at java.net.URI$Parser.checkChars(URI.java:3020)
[3729](https://github.com/scala/scala/actions/runs/3379006847/jobs/5609993160#step:6:3730)
[error]     at java.net.URI$Parser.parse(URI.java:3057)
[3730](https://github.com/scala/scala/actions/runs/3379006847/jobs/5609993160#step:6:3731)
[error]     at java.net.URI.this(URI.java:588)
[3731](https://github.com/scala/scala/actions/runs/3379006847/jobs/5609993160#step:6:3732)
[error]     at java.net.URI.create(URI.java:850)
[3732](https://github.com/scala/scala/actions/runs/3379006847/jobs/5609993160#step:6:3733)
[error]     ... 40 more
```

2022-11-03 10:45 UTC, som-snytt commented
Follow-up at https://github.com/scala/scala/pull/10207