Don't GLB binders of type patterns, use the type directly
scala/scala pull request #10247
Opened 2022-12-21 15:59 UTC by lrytz

In type patterns `c match { case x: T }`, the translation would assign the GLB of `c`'s type and `T` to the varaible `x`.

This seems to trace back to the first version of the "virtual pattern matcher". I could not find a similar use of `glb` in that revision of the codebase. So I'm not sure if it was a new addition, or picked up from the previous implementation.

https://github.com/scala/scala/blob/8a9fd64129926eea35f7dca181242855f14e153f/src/compiler/scala/tools/nsc/typechecker/PatMatVirtualiser.scala#L438-L440

In the test case, the GLB collapsed to `Null` because its computation failed (combination of f-bounds, existentials, skolems that I don't follow), see `throw GlbFailure`. This is how it's been for 14 years (b894f804ad). This resulted in a cast to `Null$` failing at runtime.

I assume GLB is fixed in Scala 3, as this core of the type system has a new implementation. But the test case as such doesn't compile in Scala 3 due to the non-wildcard existential.

2022-12-22 10:03 UTC, lrytz commented
@SethTisue could you run this one through the community build?

2022-12-22 10:54 UTC, retronym requested changes
Glad my hunch seems to be working! Easier than fixing `glb` itself in this instance!

 - [x] Remove `def glbWith`, should be dead code now
 - [ ] Analyze a `jardiff` of a bootstrapped vs non-boostrapped compiler to get a sense of what, if anything, changes using the compiler as a test case.

2022-12-22 14:17 UTC, lrytz commented
The `def glbWith` is already removed.

Jardiff for library+reflect+compiler here: https://gist.github.com/lrytz/35b3e7be0b6dab13ed95e771feb04429

It looks fine. The type of this `cl` variable changed: https://github.com/scala/scala/blob/2.13.x/src/compiler/scala/tools/nsc/classpath/ZipAndJarFileLookupFactory.scala#L221

As it's captured below in `new TimerTask { ... }`, the field of the anonymous class changed (from `Object` to `Closeable`).

2022-12-23 03:10 UTC, retronym approved these changes

2023-01-06 02:08 UTC, SethTisue commented
> could you run this one through the community build?

I'll get to it... a bit backed up, post-holidays

2023-01-10 04:10 UTC, SethTisue commented
queued: https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/4226/

2023-01-11 02:40 UTC, SethTisue commented
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/4226/ was green 🎉

(the metals failure is expected, it always fails on PR validation snapshots)

2023-01-11 02:41 UTC, merged

2023-01-11 02:43 UTC, SethTisue commented
I have lingering suspicion that there may be codebases out there relying on the old behavior. I think we can go ahead with it regardless, but let's release-note it.