Patmat: Fix over-prunning of private children
scala/scala pull request #10269
Opened 2023-01-19 15:27 UTC by dwijnand

2023-01-25 08:32 UTC, lrytz requested changes
When I change the example a little I now get a false exhaustivity warning:

```scala
object T {
  private sealed trait T
  private object O extends T
  private trait U extends T
  private object P extends U

  def t1(t: T) = t match {
    case O => ()
    case _: U => println("hai") // false "unreachable code" in 2.13.10
  }

  def t2(t: T) = t match {
    case O => ()
    case P => println("hai") // false "would fail on (_: T.U)" with this PR
  }
}
```

2023-01-25 11:34 UTC, dwijnand commented
That's not false:

```scala
object Outlaw extends U
t2(Outlaw)
```

`T` is the end of the line, because it isn't sealed.  Unless you want to extend the sealed child machinery so that "private" is more "effectively sealed" and has sealed children.  But I don't think we should.

2023-01-25 11:40 UTC, lrytz commented
Ah, so `private` is not taken as effectively sealed. I haven't thought about this much, why do you think that's the right thing to do?

2023-01-25 12:06 UTC, dwijnand commented
Well the machinery for children is currently only set up - I mean in the compiler in general - for sealed classes.  So we'd have to extend that.  And I'm not sure if extending that is an expected/intended/acceptable change?  Maybe just yes, maybe sealed should be reserved for that.

2023-01-25 13:36 UTC, som-snytt commented
I agree about "effectively sealed", because people (we the users) often reason from the obvious, such as, "it knows I don't have a subclass." I remember something about sealed and children from looking at java sealed, but to me, sealed is a stronger mechanism than warnings due to "effectively sealed." However, I don't have a lot of experience (history of annoyance) to fall back on.

2023-01-25 14:07 UTC, lrytz reviewed
Finally got it... removing `isPrivate` is the fix for the bug, but that was an incorrect fix for t6159. So you added a fix for t6159 below.

I changed things a bit, maybe it's clearer?

2023-01-25 14:07 UTC, lrytz commented on src/compiler/scala/tools/nsc/transform/patmat/MatchAnalysis.scala
> +          isPrimitiveValueClass(child) // keep sealed, abstract, primitive classes
This is redundant I think, value classes are not sealed (they are abstract though).

2023-01-25 14:25 UTC, lrytz commented on src/compiler/scala/tools/nsc/transform/patmat/MatchAnalysis.scala
> +          child.isAbstractClass && children1.exists(sym => (sym ne child) && sym.isSubClass(child))
maybe we can only remove private children here? This example (two files) no longer shows an exhaustivity warning:

```
object A {
  sealed trait X
  class X1 extends X2 with X { }
  abstract class X2 extends X
  sealed trait X3 extends X

  def f(x: X) = x match {
    case _: X1 => 0
  }
}
```

```
object B {
  def main(args: Array[String]): Unit = {
    A.f(new A.X2 { })
  }
}

```

2023-01-26 12:25 UTC, lrytz commented on test/files/pos/t6159.scala
> +    case _: X2 => 1 // required, otherwise inexhaustive
maybe put this in a `neg/` test..

2023-01-26 16:23 UTC, SethTisue commented
> remove private abstract children

I was something of a private abstract child, myself

2023-01-30 13:26 UTC, lrytz approved these changes

2023-01-30 14:05 UTC, merged