Improve doc of Seq.sortWith
scala/scala pull request #10292
Opened 2023-02-05 02:10 UTC by som-snytt

Clarify scala/bug#12725

Huge improvement to the example. Motivates not just using `sorted`.

2023-02-05 15:10 UTC, noresttherein commented
May I suggest forgoing 'stable' at all? It may be a regional thing, but I fixed on the stronger meaning of the term because in my experience it was always used to mean 'doesn't change the order of *any* elements which already are in the proper order'. Even if the term is also used in literature in a weaker sense, my example shows that it can be a source of confusion, which the added line already explains adequately. I am not sure that, even after the fix, I would go further than 'stable' in the docummentation before discovering unexpected behaviour.

2023-02-05 17:47 UTC, som-snytt commented
@noresttherein I don't understand your comment, but I've been meaning to refresh my knowledge about algorithms. Sedgewick: "A sorting method is _stable_ if it preserves the relative order of equal keys in the array." It makes no sense to speak of preserving the order of unequal keys, because they must be sorted.

Maybe you mean something about "natural order" versus equality with respect to the comparison function which determines ordering for the sort. The augmented example is intended to show that we use an unnatural order.

2023-02-08 18:20 UTC, SethTisue commented
I also don't see the wiggle room in “stable”. It's very much the standard term.

2023-02-17 03:40 UTC, SethTisue requested changes

2023-02-17 03:40 UTC, SethTisue commented on src/library/scala/collection/Seq.scala
> +   *  The sort is stable. That is, elements that are equal (such that `lt` returns false)
```suggestion
   *  The sort is stable. That is, elements that are equal (`lt` returns false
   * for both directions of comparison)
```

2023-02-17 03:40 UTC, SethTisue commented on src/library/scala/collection/Seq.scala
> +   *              its first argument precedes its second argument in
```suggestion
   *              its first argument strictly precedes its second argument in
```

2023-02-17 04:13 UTC, som-snytt commented
thanks, I knew it was too concise. suggestions pushed and rebased for concision of history.

2023-02-17 10:22 UTC, odd approved these changes

2023-02-17 15:20 UTC, merged