warning when constant multiplication overflow
scala/scala pull request #10587
Opened 2023-10-28 15:12 UTC by txdv

This will emit warnings when constant overflows during multiplication, subtraction and addition

2023-10-28 15:16 UTC, txdv commented
I signed the CLA, don't know how to rerun it.

2023-10-28 17:36 UTC, txdv commented
Do I need to merge it into one commit?

2023-10-28 18:58 UTC, som-snytt commented
this repo encourages squashing and push -f. There is also `[ci: last-only]` in the title to test only the last commit, when pushing history that will be squashed later.

2023-10-28 19:08 UTC, SethTisue commented
> Do I need to merge it into one commit?

Every commit must pass CI, though we use `[ci: last-only]` if we feel there are special circumstances.

It's up to you/us whether a PR is best as a single commit, or whether it's better in more readily understandable, distinct pieces. This PR looks to me like it should be a single commit.

2023-10-28 20:55 UTC, som-snytt commented
Seth warns if commit folding underflows.

2023-10-30 09:29 UTC, sjrd commented
Hum, I don't think this is the right approach. As is, the warning says that constant-folding threw an `ArithmeticException`, but the same code would *not*, in fact, throw an `ArithmeticException` at run-time.

More problematic, code that *does* constant-fold today will stop being constant-folded with these changes. This can cause surprising performance regressions in generated code.

We should still perform constant-folding even in the presence of overflow, and only *additionally* emit a warning that says what truly happens: that *overflow* occurred while constant-folding, and not an `ArithmeticException`.

2023-10-31 10:26 UTC, txdv commented
> More problematic, code that does constant-fold today will stop being constant-folded with these changes. This can cause surprising performance regressions in generated code.

Yes, I want to avoid situations like:

```scala
object Main {
  val long: Long = 100 * 1024 * 1024 * 1024
}
```

Where it compiles and just sets it to 0. Java and Rust treats these as compilation errors. I'll create a second PR with warning only, but a warning is not enough in this situation.

2023-10-31 10:47 UTC, sjrd commented
That specific one, maybe not because it collapses to 0, but that's not the case for every constant-fold that overflows. Some are intentional, exploiting the modulo 32/64 arithmetics.

2023-11-29 17:21 UTC, lrytz commented
> We should still perform constant-folding even in the presence of overflow, and only _additionally_ emit a warning that says what truly happens: that _overflow_ occurred while constant-folding, and not an `ArithmeticException`.

Yes, that's what we should be doing. @txdv are you interested in coming back to this?

2024-01-19 10:33 UTC, txdv commented
@lrytz yes, going to fix it right now

2024-01-19 10:38 UTC, txdv commented
@lrytz I left the multiplication overflow check

2024-01-25 18:59 UTC, som-snytt requested changes

2024-01-25 18:59 UTC, som-snytt commented on src/compiler/scala/tools/nsc/typechecker/ConstantFolder.scala
> +    case nme.MUL => Constant(Math.multiplyExact(x.intValue, y.intValue))
This doesn't address Seb's objection, that it throws and uses the original tree instead of the overflowing result.

2024-01-25 19:03 UTC, som-snytt commented
Closing in favor of the superseding PR, on which txdv is an author.

I don't see javac warning or erroring, not sure if I'm missing something?

In any case, it seems like a helpful lint. Just forgot that I omitted the edge case neg of min value.

2024-01-25 19:03 UTC, closed without merging