Improve Array.copy performance
scala/scala pull request #10962
Opened 2024-12-20 14:52 UTC by bbrehm

If source and dest are both non-primitive array types, then we can always use System.arraycopy and avoid the slowcopy branch. ArrayBuffer.toArray is added to the benchmark suite in order to avoid regressions and demonstrate the performance impact.

============================
We found that while debugging some performance issues in our product. I'm new to contributing to scala-core, is anything more needed from us? We're actually on scala3, but as far as I understood the stdlib is shared? Or do we need to submit a separate PR to dotty?

cc @mpollmeier

Benchmark results:
before:
[info] # JMH version: 1.37
[info] # VM version: JDK 21.0.5, OpenJDK 64-Bit Server VM, 21.0.5+11
[info] Benchmark                                (size)  Mode  Cnt      Score      Error  Units
[info] ArrayBufferBenchmark.toObjArrayTagged        10  avgt    3     22.612 ±    0.777  ns/op
[info] ArrayBufferBenchmark.toObjArrayTagged       100  avgt    3    138.671 ±    6.337  ns/op
[info] ArrayBufferBenchmark.toObjArrayTagged      1000  avgt    3   1481.954 ±   23.427  ns/op
[info] ArrayBufferBenchmark.toObjArrayTagged     10000  avgt    3  20339.480 ± 4783.063  ns/op
[info] ArrayBufferBenchmark.toObjArrayUntagged      10  avgt    3     12.081 ±    0.857  ns/op
[info] ArrayBufferBenchmark.toObjArrayUntagged     100  avgt    3     27.387 ±    1.870  ns/op
[info] ArrayBufferBenchmark.toObjArrayUntagged    1000  avgt    3    268.906 ±    0.578  ns/op
[info] ArrayBufferBenchmark.toObjArrayUntagged   10000  avgt    3   3275.216 ±  191.143  ns/op

after:
[info] Benchmark                                (size)  Mode  Cnt     Score      Error  Units
[info] ArrayBufferBenchmark.toObjArrayTagged        10  avgt    3    24.527 ±    2.174  ns/op
[info] ArrayBufferBenchmark.toObjArrayTagged       100  avgt    3    89.477 ±    5.532  ns/op
[info] ArrayBufferBenchmark.toObjArrayTagged      1000  avgt    3   967.160 ±   16.491  ns/op
[info] ArrayBufferBenchmark.toObjArrayTagged     10000  avgt    3  9293.766 ±  631.164  ns/op
[info] ArrayBufferBenchmark.toObjArrayUntagged      10  avgt    3    11.202 ±    0.234  ns/op
[info] ArrayBufferBenchmark.toObjArrayUntagged     100  avgt    3    27.401 ±    0.115  ns/op
[info] ArrayBufferBenchmark.toObjArrayUntagged    1000  avgt    3   273.243 ±   23.052  ns/op
[info] ArrayBufferBenchmark.toObjArrayUntagged   10000  avgt    3  3375.853 ± 2073.324  ns/op

2024-12-20 15:22 UTC, SethTisue commented
This looks quite appealing, thank you! We'll need a signed CLA (see the "checks" section). And we might not look at this until January.

@scala/collections

2024-12-20 20:08 UTC, mpollmeier commented
Big shoutout to yourkit profiler btw, this issue was immediately obvious in their flamegraph view. They hand out free licenses to open source projects, and this codepath was actually triggered by one of our open source projects (https://github.com/joernio/flatgraph/blob/066654dd286293b8e80f1a75e3fb8c147531220f/core/src/main/scala/flatgraph/DiffGraphApplier.scala#L444)

2024-12-20 22:32 UTC, sjrd requested changes

2024-12-20 22:32 UTC, sjrd commented on src/library/scala/Array.scala
> +    if (srcClass.isArray && (destClass.isAssignableFrom(srcClass) ||
```suggestion
    if (srcClass.isArray && ((destClass eq srcClass) ||
```
When one of the two arrays is a primitive array, the only way one can be assignable from the other is if they are the same array type. 

Using `eq` here will therefore act both as a fast path for all typical copies, and handling the primitive cases. Then your new condition can deal with all the reference array types that don't make it into the fast path.

2025-01-06 10:00 UTC, bbrehm commented
OK, CLA is signed. Sorry for the delay, took some days to get corporate to ack that.

Should be ready from my POV?

/rebuild

2025-01-06 10:01 UTC, sjrd approved these changes

2025-01-06 15:31 UTC, bbrehm commented
I think the validate-main failures are spurious and need human intervention, a la `java.io.IOException: No space left on device`

2025-01-06 15:36 UTC, sjrd commented
You'll need to squash the commits as a single commit with a clean error message.

The bot can only mark a PR as green if *all* commits in it are green. In this codebase we typically address review comments by amending/squashing commits, rather than adding separate "fixup" commits.

2025-01-07 20:38 UTC, bbrehm commented
error message looks flaky?

/rebuild

2025-01-07 20:42 UTC, SethTisue commented
I hit re-run on the Travis-CI build. (`/rebuild` only does Jenkins... but for PR validation we'll shortly be replacing Travis-CI with GitHub actions anyway...)

2025-01-07 23:45 UTC, SethTisue commented
rebased on top of #10978 — hopefully that'll fix CI

2025-01-08 02:39 UTC, He-Pin commented on src/library/scala/Array.scala
> +        (destClass.isArray && !srcClass.getComponentType.isPrimitive && !destClass.getComponentType.isPrimitive)))
So we can copy an Array[Dog] to an Array[Cat] now？

2025-01-08 04:40 UTC, sjrd commented on src/library/scala/Array.scala
> +        (destClass.isArray && !srcClass.getComponentType.isPrimitive && !destClass.getComponentType.isPrimitive)))
You could do that before this PR. It was just slower. 

It works if all the dogs in your source array also happen to be cats.

2025-01-08 08:20 UTC, som-snytt commented on src/library/scala/Array.scala
> +        (destClass.isArray && !srcClass.getComponentType.isPrimitive && !destClass.getComponentType.isPrimitive)))
Ah, we have just solved the previously intractable "dog person or cat person problem".

2025-01-08 10:49 UTC, bbrehm commented on src/library/scala/Array.scala
> +        (destClass.isArray && !srcClass.getComponentType.isPrimitive && !destClass.getComponentType.isPrimitive)))
And our answer was and is "null person" or "java.lang.ArrayStoreException person" ;)

2025-01-08 12:38 UTC, He-Pin commented on src/library/scala/Array.scala
> +        (destClass.isArray && !srcClass.getComponentType.isPrimitive && !destClass.getComponentType.isPrimitive)))
@bbrehm I think you can update the benchmark result with the new code :)

2025-01-08 14:03 UTC, mpollmeier commented on src/library/scala/Array.scala
> +        (destClass.isArray && !srcClass.getComponentType.isPrimitive && !destClass.getComponentType.isPrimitive)))
Would be good to mark this comment or review as resolved. As @sjrd mentioned the behaviour hasn't changed, and the rest is just joking around. Would be sad if anyone gets fooled into thinking this is a stopper.

2025-01-08 14:44 UTC, bbrehm commented on src/library/scala/Array.scala
> +        (destClass.isArray && !srcClass.getComponentType.isPrimitive && !destClass.getComponentType.isPrimitive)))
>@bbrehm I think you can update the benchmark result with the new code :)

in how far? The only change was @sjrd 's excellent suggestion on better expressing the same check for whether we need the slow loop. However, that should be insignificant, timing wise (the check is only done once!).

A very valid question is about old JVMs that afaik can't intrinsify / model small arraycopies, and always need to call out into the runtime library. I would not be surprised if a fully inlined slowcopy of statically known small size ends up faster than System.arraycopy on JVM8!

I'd put that into the "don't care" category, though -- the mental model of Array.copy should be "System.arraycopy, but supports boxing/unboxing of primitives". Then, one should ideally trust the compiler, same as in C/C++ where `memcpy(dst, src, 8)` can be trusted to become a single load/store instead of a call into libc that then has a loop.

2025-01-08 14:53 UTC, SethTisue commented on src/library/scala/Array.scala
> +        (destClass.isArray && !srcClass.getComponentType.isPrimitive && !destClass.getComponentType.isPrimitive)))
I agree that JDK 8-only performance issues are of little/no concern.

2025-01-08 17:49 UTC, som-snytt commented
I commented on the linked PR that for just building arrays using `addOne`, `ArrayBuilder.ofRef` seems to avoid the gotcha. (untested)

Also worth noting that although some workflows require "all conversations must be marked resolved", that is not the case (so far) in this repo.

Someday github will collect all the humor and bury it in the Comedy Vault under the North Pole, for future generations and alien archaeologists.

2025-01-08 19:54 UTC, SethTisue commented
@som-snytt I hope they are not planning to bury you and me personally, alive, in said Comedy Vault

2025-01-16 11:21 UTC, lrytz reviewed
I couldn't (easily) figure out how `(ref: ArrayBuffer[Int]).asInstanceOf[ArrayBuffer[Integer]].toArray` performance is affected by this PR, could someone explain?

2025-01-16 11:21 UTC, lrytz commented on src/library/scala/Array.scala
> +    if (srcClass.isArray && ((destClass eq srcClass) ||
IIUC there's always only one `Class` instance for a given class (or `Array[C]`) - is that documented?

2025-01-16 12:20 UTC, sjrd commented on src/library/scala/Array.scala
> +    if (srcClass.isArray && ((destClass eq srcClass) ||
https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html

> Every array also belongs to a class that is reflected as a Class object that is _shared by all arrays_ with the same element type and number of dimensions.

(emphasis mine)

2025-01-16 12:22 UTC, sjrd commented
> I couldn't (easily) figure out how `(ref: ArrayBuffer[Int]).asInstanceOf[ArrayBuffer[Integer]].toArray` performance is affected by this PR, could someone explain?

`ArrayBuffer` always uses an `Array[Object]` inside. Calling `toArray` when it's typed as `ArrayBuffer[Integer]` thus instantiates an `Array[Integer]`. It then copies its `Array[Object]` into the `Array[Integer]`. This combination previously used the slow path, and now takes the fast `System.arraycopy` path.

2025-01-16 12:34 UTC, lrytz commented
Thanks! I also missed the `copyToArray` override in `ArrayBuffer`.

2025-01-16 12:37 UTC, merged