Frontend fixes for scala-dev#248
scala/scala pull request #5482
Opened 2016-10-26 18:56 UTC by lrytz

See individual commit messages.

2016-10-26 23:42 UTC, retronym commented
Awesome, this looks to fix https://issues.scala-lang.org/browse/SI-7139!

```
% cat sandbox/test.scala
package test {
  object A
}
package object test {
  type A = Int
}

% scalac sandbox/test.scala && printf ':silent\ndef bug = null.asInstanceOf[test.A.type]\ndef bug = null.asInstanceOf[test.A.type]\n' | scala
Welcome to Scala 2.11.8 (OpenJDK 64-Bit Server VM, Java 1.8.0_112-release).
Type in expressions for evaluation. Or try :help.

scala> :silent

scala> def bug = null.asInstanceOf[test.A.type]

scala> def bug = null.asInstanceOf[test.A.type]
<console>:11: error: type mismatch;
 found   : test.A.type
 required: AnyRef
Note that A extends Any, not AnyRef.
Such types can participate in value classes, but instances
cannot appear in singleton types or in reference comparisons.
       def bug = null.asInstanceOf[test.A.type]
                                        ^

scala> :quit

% qscalac sandbox/test.scala && printf ':silent\ndef bug = null.asInstanceOf[test.A.type]\ndef bug = null.asInstanceOf[test.A.type]\n' | qscala
Welcome to Scala 2.12.0-20161026-205457-37b3df3 (OpenJDK 64-Bit Server VM, Java 1.8.0_112-release).
Type in expressions for evaluation. Or try :help.

scala> :silent

scala> def bug = null.asInstanceOf[test.A.type]

scala> def bug = null.asInstanceOf[test.A.type]

scala> :quit
```

2016-10-27 00:59 UTC, soc commented on src/reflect/scala/reflect/internal/pickling/UnPickler.scala
>        case ex: Throwable =>
Maybe `ex: NonFatal` instead?

2016-10-27 00:59 UTC, soc commented on src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala
> -    }
This is a nice cleanup! :-)

2016-10-27 07:25 UTC, lrytz commented
/synch

2016-10-27 19:20 UTC, lrytz commented
added a test case for SI-7139. all commits are green, so review by @retronym. maybe also @adriaanm, as this touches some low-level internals.

2016-10-27 19:50 UTC, lrytz commented on src/reflect/scala/reflect/internal/pickling/UnPickler.scala
>        case ex: Throwable =>
that's reasonable, will do

2016-10-28 00:04 UTC, adriaanm requested changes
Really good stuff! I have a few small suggestions for locking this down a bit more while we're at it.

2016-10-28 00:04 UTC, adriaanm commented on src/compiler/scala/tools/nsc/symtab/SymbolLoaders.scala
> -  protected def newClassLoader(bin: AbstractFile): SymbolLoader =
I verified this hook (re-introduced by #2963) is no longer used by scala-js (since https://github.com/scala-js/scala-js/commit/8d85779)

2016-10-28 00:04 UTC, adriaanm commented on src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala
> -        if ((clazz eq NoSymbol) && (c ne NoSymbol)) clazz = c
Is there any scenario in e.g. presentation/interactive mode where we needed this? /cc @dragos

2016-10-28 00:04 UTC, adriaanm commented on src/compiler/scala/tools/nsc/symtab/SymbolLoaders.scala
> +  def newModule(owner: Symbol, name: String): Symbol = owner.newModule(newTermName(name))
`: ModuleSymbol` as the result? (Allows tightening `enterClassAndModule` and `ClassfileLoader`).

2016-10-28 00:04 UTC, adriaanm commented on src/compiler/scala/tools/nsc/symtab/SymbolLoaders.scala
> +  def enterClassAndModule(root: Symbol, name: String, getCompleter: (Symbol, Symbol) => SymbolLoader) {
`(Symbol, ModuleSymbol) => SymbolLoader` seems within reach to avoid confusion in the future.

2016-10-28 00:04 UTC, adriaanm commented on src/compiler/scala/tools/nsc/symtab/SymbolLoaders.scala
> +  class ClassfileLoader(val classfile: AbstractFile, clazz: Symbol, module: Symbol) extends SymbolLoader with FlagAssigningCompleter {
`module: ModuleSymbol`

2016-10-28 00:04 UTC, adriaanm commented on src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala
> +  def parse(file: AbstractFile, clazz: Symbol, module: Symbol): Unit = {
`module: ModuleSymbol`

2016-10-28 00:04 UTC, adriaanm commented on src/compiler/scala/tools/nsc/symtab/SymbolLoaders.scala
> +  def newModule(owner: Symbol, name: String): Symbol = owner.newModule(newTermName(name))
Implemented in https://github.com/scala/scala/commit/5c7b8ede926c6157ae9853316f1d4c90859985ee

2016-10-28 06:44 UTC, dragos commented on src/compiler/scala/tools/nsc/symtab/SymbolLoaders.scala
> +      enteringPhase(phaseBeforeRefchecks)(classfileParser.parse(classfile, clazz, module))
The comment seems outdated, the classfile parser doesn't call `companionModule` anymore. Maybe there's no need to call `enteringPhase` either?

2016-10-28 06:46 UTC, dragos commented on src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala
> +  def parse(file: AbstractFile, clazz: Symbol, module: Symbol): Unit = {
This allows callers to pass unrelated symbols. Maybe some warning in a comment is in order (I assume calls to `companionModule` & friends are also "forbidden" inside this method. If so, also worth a comment.

2016-10-28 06:55 UTC, dragos commented on src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala
> -        if ((clazz eq NoSymbol) && (c ne NoSymbol)) clazz = c
No, I don't think so. This looks more like defensive coding.  I don't know if there's any scenario in which `pool.getClassSymbol` returns `NoSymbol`, but that seems to be the only purpose of this call. Maybe the new logic involving `StubSymbol` subsumes it?

2016-10-28 10:35 UTC, lrytz commented on src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala
> -        if ((clazz eq NoSymbol) && (c ne NoSymbol)) clazz = c
With this PR, clazz cannot ever be NoSymbol.

2016-10-28 10:37 UTC, lrytz commented on src/compiler/scala/tools/nsc/symtab/SymbolLoaders.scala
> +      enteringPhase(phaseBeforeRefchecks)(classfileParser.parse(classfile, clazz, module))
Hmm.. I think it's a bit risky to remove the phase travel here, the classfile parser and unpickler call various methods on symbols. I'll update the comment.

2016-10-28 10:40 UTC, lrytz commented on src/compiler/scala/tools/nsc/symtab/SymbolLoaders.scala
> +      enteringPhase(phaseBeforeRefchecks)(classfileParser.parse(classfile, clazz, module))
Though I see it was added not too long ago: 0ccdb15

2016-10-28 10:42 UTC, lrytz commented on src/compiler/scala/tools/nsc/symtab/SymbolLoaders.scala
> +      enteringPhase(phaseBeforeRefchecks)(classfileParser.parse(classfile, clazz, module))
I'll give it a try.

2016-10-28 10:45 UTC, lrytz commented on src/compiler/scala/tools/nsc/symtab/SymbolLoaders.scala
> +  def newModule(owner: Symbol, name: String): Symbol = owner.newModule(newTermName(name))
ok, done.

2016-10-28 16:38 UTC, adriaanm approved these changes

2016-10-28 16:39 UTC, adriaanm commented on src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala
> -        if ((clazz eq NoSymbol) && (c ne NoSymbol)) clazz = c
Ok, thanks.

2016-10-28 16:40 UTC, adriaanm commented
LGTM!

2016-10-28 18:49 UTC, merged