Improve Queue.++ when building another Queue
scala/scala pull request #5579
Opened 2016-12-05 01:55 UTC by edmundnoble

Adds in the Okasaki `concat` version in case we are constructing a `Queue` from two `Queue`s. You can see the impact of the default implementation (and inheritance hierarchy etc.) here: https://ethercalc.org/kknm1xz3mb5s_naakfyfum4p3/app in all of the concat benchmarks, especially the right-associated tree being concatenated. The que method is my Okasaki queue and the sque method is `immutable.Queue:` the performance difference is a few orders of magnitude at my benchmark size.

2016-12-08 12:46 UTC, szeiger commented on src/library/scala/collection/immutable/Queue.scala
> +    if (bf eq Queue.ReusableCBF) {
This looks wrong. The `ReusableCBFInstance` is shared by all GenTraversables. There's no guarantee that either `that` or `That` is of type `Queue`.

2016-12-13 04:33 UTC, edmundnoble commented on src/library/scala/collection/immutable/Queue.scala
> +    if (bf eq Queue.ReusableCBF) {
The assumption that `That =:= Self` seems to be made in List.scala:
```scala
  override def ++[B >: A, That](that: GenTraversableOnce[B])(implicit bf: CanBuildFrom[List[A], B, That]): That =
    if (bf eq List.ReusableCBF) (this ::: that.seq.toList).asInstanceOf[That]
    else super.++(that)

  override def +:[B >: A, That](elem: B)(implicit bf: CanBuildFrom[List[A], B, That]): That = bf match {
    case _: List.GenericCanBuildFrom[_] => (elem :: this).asInstanceOf[That]
    case _ => super.+:(elem)(bf)
  }
```

2016-12-13 05:39 UTC, Ichoran commented on src/library/scala/collection/immutable/Queue.scala
> +    if (bf eq Queue.ReusableCBF) {
`.asInstanceOf[Queue[B]]` is absolutely not a parallel to `.seq.toList`.

2016-12-13 06:46 UTC, edmundnoble commented on src/library/scala/collection/immutable/Queue.scala
> +    if (bf eq Queue.ReusableCBF) {
@Ichoran When is it that `That =:= Self; val that: That = _; that.isInstanceOf[Self]` is not the case? Please provide an example.

2016-12-13 08:10 UTC, retronym commented on src/library/scala/collection/immutable/Queue.scala
> +    if (bf eq Queue.ReusableCBF) {
`ReusableCBFInstance` is a field in `class GenTraversableFactory`. The companions of each collection extend this, and thus have distinct instances.

```
scala> Queue.ReusableCBF eq Seq.ReusableCBF
res8: Boolean = false
```

So this code isn't obviously incorrect to me.

2016-12-13 14:01 UTC, szeiger commented on src/library/scala/collection/immutable/Queue.scala
> +    if (bf eq Queue.ReusableCBF) {
Hm, you're right, `ReusableCBFInstance` is a field of the class. I must have read that wrong the first time and assumed it's in the object.

2017-01-14 19:05 UTC, SethTisue commented on src/library/scala/collection/immutable/Queue.scala
> +      new Queue[B](thatQueue.in ++ (thatQueue.out.reverse ++ this.in), this.out).asInstanceOf[That]
`thatQueue.out.reverse ++ this.in` copies `thatQueue.out` twice — I think you can get it down to one copy by using `List#reverse_:::`, a trick you'll see used in the body of `def enqueue[B >: A](iter: Iterable[B])`

2017-01-14 19:05 UTC, SethTisue requested changes

2017-01-14 19:05 UTC, SethTisue commented on src/library/scala/collection/immutable/Queue.scala
> +      new Queue[B](thatQueue.in ++ (thatQueue.out.reverse ++ this.in), this.out).asInstanceOf[That]
`thatQueue.out.reverse ++ this.in` copies `thatQueue.out` twice — I think you can get it down to one copy by using `List#reverse_:::`, a trick you'll see used in the body of `def enqueue[B >: A](iter: Iterable[B])`

2017-01-23 19:38 UTC, SethTisue approved these changes

2017-02-08 01:27 UTC, merged

2017-05-06 10:06 UTC, xuwei-k commented
https://github.com/scala/bug/issues/10298

2017-05-06 15:05 UTC, Ichoran commented on src/library/scala/collection/immutable/Queue.scala
> +    if (bf eq Queue.ReusableCBF) {
@edmundnoble - Ugh, I'm sorry I overlooked this after the first comment.  As I guess we're all aware now, it's the `that: That` assumption that is wrong.  `That` is the type being produced, while `that` is an instance that is not parameterized by type.  It's a very unfortunate naming convention.

2017-05-06 17:33 UTC, edmundnoble commented on src/library/scala/collection/immutable/Queue.scala
> +    if (bf eq Queue.ReusableCBF) {
Ughhhhh. Crap. My bad.