SI-10102 REPL ignores sbt init errors
scala/scala pull request #5655
Opened 2017-01-19 22:38 UTC by som-snytt

sbt runs user init code early, while creating its
custom `IMain`. Failures in this (arbitrary) code
keep the console from starting, including (silent)
errors due to bugs. Ignore silent errors emitted
on startup when sbt is running.

2017-02-09 00:55 UTC, SethTisue commented
can you suggest a reviewer who could consider this from the sbt side...?

2017-02-09 02:23 UTC, som-snytt commented
@dwijnand still owes me one for https://github.com/scala/scala/pull/5214

2017-02-09 02:27 UTC, som-snytt commented
Also, instead of deprecating `InterpreterLoop`, it should be considered the canonical place to workaround the sbt code. (I intended to donate upgraded `ConsoleInterface` to sbt.)

2017-02-09 02:35 UTC, dwijnand commented
I'm not sure. On all front to be honest. Both on (a) what broke it, (b) what exactly happens, and (c) fixing it like that. Sorry :-/

2017-02-09 04:52 UTC, som-snytt commented
(a) previously, I had refactored how REPL startup happens to be more sane. (b) it checks whether the reporter saw errors during startup. Since sbt executes arbitrary code during startup, that is not unlikely. (c) How about we not fail to start in that case. The reporter still knows it saw an error. Reporters like elephants never forget.

But wait, at this point, I want to refactor some imports to use trailing commas.

2017-02-21 01:27 UTC, adriaanm commented on src/repl/scala/tools/nsc/interpreter/ReplReporter.scala
> +  def reportableErrorCount = errorCount - silentErrors
Let's make these additions `private[interpreter]`.

2017-02-21 01:33 UTC, adriaanm requested changes
You've unlocked the pragmatic fix badge! Thanks for moving us in the right direction here. Eventually, closer cooperation of sbt & scalac is the ticket. A few small requested tweaks, if I may. Also, in future, please consider separate boy scout and bug fix commits.

2017-02-21 01:33 UTC, adriaanm commented on src/repl/scala/tools/nsc/interpreter/ReplReporter.scala
> +    if (count1 > count0 && intp.totalSilence)
Does the reporter contract guarantee `0 <= count1 - count0 <= 1`? I guess so.

2017-02-21 01:33 UTC, adriaanm commented on src/repl/scala/tools/nsc/interpreter/ReplReporter.scala
> +  def reportableErrorCount = errorCount - silentErrors
Let's make these additions `private[interpreter]`.

2017-02-21 03:46 UTC, som-snytt commented
Made `isSbt` a member of `InterpreterLoop` and also pushed `main`, which may trigger mima.

Members of `ReplReporter` are more private.

Rebased.

2017-02-23 01:01 UTC, dwijnand approved these changes
Thanks Som for your explanation and sorry for the late review. This needs rebasing.

I've noted a little concern, if you agree then I guess you could fix it up while rebasing.

It's not a blocker for me though. LGTM.

2017-02-23 01:01 UTC, dwijnand commented on src/repl/scala/tools/nsc/InterpreterLoop.scala
> +  override protected final val isSbt = true
Given Adriaan's previous comment, at a guess I would think this should be `protected[nsc]` (or tools or scala).

nsc is principle of least power and scala is principle of maximal flexibility?

2017-02-23 01:08 UTC, dwijnand commented
It's a shame we can't create a test case to reproduce the original bug and stand as a regression test.

2017-05-23 05:02 UTC, retronym commented
This PR needs a rebase to resolve a conflict with #5727

2017-05-23 05:09 UTC, som-snytt commented
Probably I'll rebase atop `Adriaanite`?

2017-06-27 19:29 UTC, SethTisue commented
@som-snytt rebase?

2017-07-10 14:28 UTC, lrytz commented
Adriaanite is 2.13, so it cannot bite here. I think it would be good to get this fix in for 2.12.3, as the error feedback for affected users is non-obvious.

2017-07-10 14:37 UTC, lrytz approved these changes

2017-07-10 14:37 UTC, lrytz commented on src/repl/scala/tools/nsc/interpreter/ILoop.scala
>            echo("Interpreter encountered errors during initialization!")
Should we actually show (some of) the errors? How can I trigger this line?

2017-07-18 06:00 UTC, merged