Address SI-9675 Add warning about non-sensible equals in anonymous functions
scala/scala pull request #5662
Opened 2017-01-26 00:22 UTC by teldosas

The problem was that in an attempt to address an issue with #4473, warnings about non-sensible equals were removed for synthetic entities. But an anonymous function is also a synthetic entity, so warnings were removed for these too by mistake.

2017-01-26 00:23 UTC, teldosas commented
I signed the CLA

2017-01-29 10:47 UTC, teldosas commented
review @adriaanm 
(Is this how I'm supposed to ask for review?)

2017-01-31 15:29 UTC, adriaanm commented
LGTM Good catch! Looks like a good example of where we could sharpen the distinction between artifact and synthetic.

2017-01-31 15:30 UTC, adriaanm requested changes
The fix looks good, but the test could be rewritten as a neg/ test instead of a run/ one, right? You'll need to create a neg/t9675.flags file that contains `-Xfatal-warnings`, but that should be it.

2017-01-31 15:32 UTC, teldosas commented
@adriaanm But that does not guarantee that we get a warning for every single function. It would be enough to get a warning for a single function for it to succeed.

2017-01-31 17:20 UTC, adriaanm commented
It does, as far as I can see -- neg tests will check that exactly the
errors in the check file are emitted. There's no need to run your app to
get the errors, just compile it
On Tue, Jan 31, 2017 at 08:32 Aristotelis Dossas <notifications@github.com>
wrote:

> @adriaanm <https://github.com/adriaanm> But that does not guarantee that
> we get a warning for every single function. It would be enough to get a
> warning for a single function for it to succeed.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/scala/scala/pull/5662#issuecomment-276396245>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAFjy9m1zHhOzogPMrU24uBxu9a_L94Mks5rX1QagaJpZM4LuKqe>
> .
>

2017-01-31 18:11 UTC, teldosas commented
Ok I made the changes. Now is more clear to me what "run" means. Thanks @adriaanm

2017-01-31 19:23 UTC, adriaanm commented
Sure! Thanks for the quick follow up.
On Tue, Jan 31, 2017 at 11:11 Aristotelis Dossas <notifications@github.com>
wrote:

> Ok I made the changes. Now is more clear to me what "run" means. Thanks
> @adriaanm <https://github.com/adriaanm>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/scala/scala/pull/5662#issuecomment-276444274>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAFjy9T01dx97RGuQ7ZWSRxtkXzDDwDgks5rX3lmgaJpZM4LuKqe>
> .
>

2017-01-31 21:21 UTC, adriaanm commented
How is this test related to this PR?

```
[[syntax trees at end of                    parser]] // client_2.scala
package <empty> {
  object Test extends App {
    def <init>() = {
      super.<init>();
      ()
    };
    val wit = Random.foo("1");
    var t = 1;
    var one: wit.T = 1
  }
}

[[syntax trees at end of                     namer]] // client_2.scala: tree is unchanged since parser
!!  409 - run/random                                [compilation failed]
```

2017-01-31 21:25 UTC, teldosas commented
@adriaanm it doesn't it's about another bug that I was working on, I pushed it by mistake. I will remove it

2017-02-01 00:33 UTC, teldosas commented
@adriaanm I removed it. It should be fine now

2017-02-16 20:15 UTC, adriaanm approved these changes

2017-02-16 20:16 UTC, merged

2017-02-16 20:17 UTC, adriaanm commented
Thanks, @teldosas! For your next fix, please use a commit title more like "SI-9675 warn about non-sensible equals in anonymous functions" (start with ticket number, use active voice)

2017-02-16 22:11 UTC, som-snytt commented
There was no adequate emoji to say, "oh, artifact vs synthetic, I was just wondering about that."