Consolidate collections performance PRs
scala/scala pull request #5664
Opened 2017-01-28 19:21 UTC by adriaanm

See #5650, #5652 and #5653

TODO: update mima for last commit

2017-01-28 20:11 UTC, adriaanm commented
I suggest we either close the other PRs, merge this one, and add the benchmarks, or incorporate these commits into one of the other PRs and close this one.

2017-01-28 21:48 UTC, rorygraves commented
@adriaanm  The List.filter/filterNot benchmark already exists on the https://github.com/scala/scala/pull/5653 PR ListBenchmark.scala

2017-01-28 21:58 UTC, adriaanm commented
Ok, I wasn't clear whether that was the last word on that. I cherry-picked the commits, so then the benchmark is in here too.

2017-01-28 22:03 UTC, adriaanm commented
Mima should be happy with these new commits. I haven't looked into whether each whitelist item is good to go. Leaving that up to @szeiger

2017-01-28 22:16 UTC, rorygraves commented
Looks good.

2017-02-02 18:33 UTC, adriaanm commented
Thanks, sounds like I can safely close the other PRs, since all their commits have been included here? Will get this one merged asap.

2017-02-02 18:45 UTC, rorygraves commented
Yes they can all be safely closed. 
:)


> On 2 Feb 2017, at 18:33, Adriaan Moors <notifications@github.com> wrote:
> 
> Thanks, sounds like I can safely close the other PRs, since all their commits have been included here? Will get this one merged asap.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-02-02 18:50 UTC, adriaanm commented
@szeiger, are you ready to sign off on this? /cc @retronym

2017-02-02 18:52 UTC, szeiger requested changes

2017-02-02 18:52 UTC, szeiger commented on bincompat-forward.whitelist.conf
> +        problemName=DirectMissingMethodProblem
This is a breaking change. WrappedArrray is public and the new method is protected. As discussed before, all these changes need to be moved down into a private implementation class.

2017-02-02 18:52 UTC, szeiger commented on bincompat-forward.whitelist.conf
> +        problemName=DirectMissingMethodProblem
Same here.

2017-02-02 18:52 UTC, szeiger commented on bincompat-forward.whitelist.conf
> +        problemName=IncompatibleResultTypeProblem
This is also a problem.

2017-02-02 19:01 UTC, szeiger commented
I'll try to fix these remaining issues after lunch. Should be ready in a few hours.

2017-02-03 16:20 UTC, szeiger commented
https://github.com/adriaanm/scala/pull/26

2017-02-04 07:04 UTC, adriaanm commented
@szeiger I merged your own fixes for your review -- thanks!

2017-02-08 16:55 UTC, szeiger approved these changes

2017-02-08 18:09 UTC, merged

2017-04-03 14:39 UTC, adriaanm commented
Looks like this is causing LinkageErrors in user code.  Should we revert, declare 2.11.9 a dud and cut 2.11.10?

# Detailed diagnosis by @xuwei-k:
https://github.com/xuwei-k/Scala-2.11.9-FilteredTraversableInternal

# Explanation by @lrytz
The reason why a reference to `FilteredTraversableInternal` appears in @xuwei-k's example:
```scala
List(1).map(identity).filter(_ => true)
```
In erasure type checking, `List(1).map(identity)` has type `Object` (the result type is `That` which is a type parameter), so selecting the `filter` method requires a cast. This is done by [erasure's `adaptMember`](https://github.com/scala/scala/blob/v2.11.9/src/compiler/scala/tools/nsc/transform/Erasure.scala#L674-L676), which casts to the filter method symbol's `owner`, which is now `FilteredTraversableInternal`.

2017-04-03 14:51 UTC, szeiger commented
@lrytz So we now have a situation that looks binary compatible in bytecode but leads to incompatibilities due to additional information in ScalaSig?

2017-04-03 15:02 UTC, lrytz commented
it's not in the scala signature, but bytecode instructions (cast, call
receiver type). i'm not sure it's a binary incompatibility by our defnition
(no linkage error), as you get a ClassNotFound. but the end result is an
incompatibility we don't want to have in a minor release.

On Mon, 3 Apr 2017 at 16:51 Stefan Zeiger <notifications@github.com> wrote:

> @lrytz <https://github.com/lrytz> So we now have a situation that looks
> binary compatible in bytecode but leads to incompatibilities due to
> additional information in ScalaSig?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/scala/scala/pull/5664#issuecomment-291167072>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAHTVMdhEfsrDgq9snlldbMGqHMx1KPIks5rsQd_gaJpZM4Lwl1L>
> .
>

2017-04-03 15:06 UTC, lrytz commented
oh, or maybe it's a NoClassDefFoundErro, which is a linkage error, i'm on
the phone :)


On Mon, 3 Apr 2017 at 17:02 Lukas Rytz <lukas.rytz@lightbend.com> wrote:

> it's not in the scala signature, but bytecode instructions (cast, call
> receiver type). i'm not sure it's a binary incompatibility by our defnition
> (no linkage error), as you get a ClassNotFound. but the end result is an
> incompatibility we don't want to have in a minor release.
>
> On Mon, 3 Apr 2017 at 16:51 Stefan Zeiger <notifications@github.com>
> wrote:
>
>> @lrytz <https://github.com/lrytz> So we now have a situation that looks
>> binary compatible in bytecode but leads to incompatibilities due to
>> additional information in ScalaSig?
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/scala/scala/pull/5664#issuecomment-291167072>, or mute
>> the thread
>> <https://github.com/notifications/unsubscribe-auth/AAHTVMdhEfsrDgq9snlldbMGqHMx1KPIks5rsQd_gaJpZM4Lwl1L>
>> .
>>
>

2017-04-03 18:14 UTC, szeiger commented
"in the bytecode instructions" is the effect, not the cause. Binary compatibility only matters when you have separate compilation, in which case the compiler must be getting the idea of casting to `FilteredTraversableInternal` from somewhere in the class file (ScalaSig?). If I understand you correctly the erased return type of `filter` is `Object` but somehow the compiler knows that the return type is really a type parameter that was instantiated as `FilteredTraversableInternal` and inserts a cast to that type. This implies that looking at the erased types is not sufficient for checking binary compatibility in MiMa. OTOH, why isn't there a bridge method for `filter` if it's overridden in `FilteredTraversableInternal`? Shouldn't we see two copies of this method (one returning `Object` and the other one returning `FilteredTraversableInternal` in all subclasses? Or maybe we do but MiMa doesn't recognize it correctly? Or is it missing because they type is private and therefore must not leak (but still does due to a compiler bug)?

(I'm only speculating here. I'd need more time to look into this but I don't expect to find any until after ScalaDays. For now the only safe solution appears to be never to add a new superclass, even if it's declared private and not supposed to leak.)

2017-04-03 18:57 UTC, lrytz commented
> If I understand you correctly the erased return type of filter is Object but somehow the compiler knows that the return type is really a type parameter that was instantiated as FilteredTraversableInternal and inserts a cast to that type

My explanation was unclear, sorry: the return type of `map` is its `That` type parameter. When type-checking `List(1).map(identity).filter` during erasure, the qualifier `List(1).map(identity)` gets type `Object`, so the selection `qual.filter` needs a cast: `qual.asInstanceOf[<owner-of-filter>].filter`. This happens here: https://github.com/scala/scala/blob/v2.11.9/src/compiler/scala/tools/nsc/transform/Erasure.scala#L674-L676

> This implies that looking at the erased types is not sufficient for checking binary compatibility in MiMa

I would say that MiMa did its job correctly: it identified the class being added, it was whitelisted. Any reference to a new class is a binary incompatibility.

> Shouldn't we see two copies of this method (one returning Object and the other one returning FilteredTraversableInternal) in all subclasses?

The return type of `FilteredTraversableInternal.filter` in bytecode is `Object`.

2017-04-03 19:32 UTC, szeiger commented
Thanks, that makes it clearer. So we'd have to change this to cast to the actual type of the qualifier instead of the method's owner (which can be a supertype) to prevent these leaks?

> I would say that MiMa did its job correctly: it identified the class being added, it was whitelisted. Any reference to a new class is a binary incompatibility.

I was hoping we could change MiMa to ignore new non-accessible superclasses and treat this case as binary compatible but with these owner casts leaking superclasses the only safe situation would be one where all methods implemented by the new superclass are overridden in all subclasses.

2017-04-03 19:43 UTC, lrytz commented
> Thanks, that makes it clearer. So we'd have to change this to cast to the actual type of the qualifier instead of the method's owner (which can be a supertype) to prevent these leaks?

This cannot easily be done, unfortunately. At the beginning of erasure, all types of trees are set to `null`, and then the type checker is run again, this time assigning only erased types. So `List(1).map(identity)` really gets type `Object`, I don't think there's a way to get `List` at this point.

We could remember the type that the tree had after typer (`List[Int]`) and use an erased version of that for the cast, but that sounds like a hack. Incidentally, we need to do exactly that in order to avoid `IllegalAccessError`s for selections of Java-defined methods: if the method is defined in a package-protected class, it might not be accessible. I very recently worked on this: https://github.com/scala/scala/pull/5792. I'm not sure we should use this hack in general, for Scala-only code.

2017-04-03 21:41 UTC, szeiger commented
After further consideration 

> the only safe situation would be one where all methods implemented by the new superclass are overridden in all subclasses

even this wouldn't be safe because it's not transitive. Adding a new superclass with overrides of all methods in all subclasses would be considered safe, adding a new override to an existing private class is safe, but the combination of both breaks binary compatibility.