SI-10194: Fix abstract type resolution for overloaded HOFs
scala/scala pull request #5708
Opened 2017-02-16 21:15 UTC by szeiger

Types in the applicable overload alternatives need to be seen from
the respective owners of the individual alternative, not from the
target’s owner (which can be a subtype of the types that define the
methods).

2017-02-16 21:33 UTC, adriaanm requested changes
Good catch! Would you mind doing the refactoring I suggested if it makes sense?

2017-02-16 21:33 UTC, adriaanm commented on src/compiler/scala/tools/nsc/typechecker/Typers.scala
> +              try functionType(funArgTypes(argTpWithAlt.map { case (tp, alt) => tp.asSeenFrom(pre, alt.owner) }).transpose.map(lub), WildcardType)
Why not keep the`asSeenFrom` in `funArgTypes`? There's a lot going on on this line already.

2017-02-17 15:08 UTC, szeiger commented on src/compiler/scala/tools/nsc/typechecker/Typers.scala
> +              try functionType(funArgTypes(argTpWithAlt.map { case (tp, alt) => tp.asSeenFrom(pre, alt.owner) }).transpose.map(lub), WildcardType)
I tried to simplify it but that didn't really work out.

2017-02-17 15:17 UTC, szeiger commented
Updated (moving `asSeenFrom` back down into `funArgTypes`) and rebased (to clear up the MiMa failure).

2017-02-20 14:00 UTC, lrytz commented
/rebuild - instable test, scala/scala-dev#296

2017-02-20 14:07 UTC, lrytz commented on src/compiler/scala/tools/nsc/typechecker/Typers.scala
> +              try functionType(funArgTypes(argTpWithAlt.map { case (tp, alt) => tp.asSeenFrom(pre, alt.owner) }).transpose.map(lub), WildcardType)
@szeiger I don't understand what didn't work out - it seems it should be easy to move the `asSeenFrom` into `funArgTypes`?

2017-02-20 14:15 UTC, szeiger commented on src/compiler/scala/tools/nsc/typechecker/Typers.scala
> +              try functionType(funArgTypes(argTpWithAlt.map { case (tp, alt) => tp.asSeenFrom(pre, alt.owner) }).transpose.map(lub), WildcardType)
@lrytz That's where it used to be. Moving it out didn't really make the code any simpler.

2017-02-20 15:00 UTC, lrytz commented on src/compiler/scala/tools/nsc/typechecker/Typers.scala
> +              try functionType(funArgTypes(argTpWithAlt.map { case (tp, alt) => tp.asSeenFrom(pre, alt.owner) }).transpose.map(lub), WildcardType)
> Moving it out didn't really make the code any simpler.

Then why was it moved out? I feel like we're talking past each other.. :)

2017-02-20 15:19 UTC, szeiger commented on src/compiler/scala/tools/nsc/typechecker/Typers.scala
> +              try functionType(funArgTypes(argTpWithAlt.map { case (tp, alt) => tp.asSeenFrom(pre, alt.owner) }).transpose.map(lub), WildcardType)
To make it simpler, obviously :)

2017-02-20 15:32 UTC, lrytz commented on src/compiler/scala/tools/nsc/typechecker/Typers.scala
> +              try functionType(funArgTypes(argTpWithAlt.map { case (tp, alt) => tp.asSeenFrom(pre, alt.owner) }).transpose.map(lub), WildcardType)
It's such a detail that I'm sorry to go back and forth so many times.. I just don't understand.. IIUC adriaan suggests to pass `argTpWithAlt` as argument to `funArgTypes` directly and do the `asSeenFrom` there, which also looks better to me. You even seem to agree, as you say

  > Moving it out [of `funArgTypes`?] didn't really make the code any simpler

so why did you move it out?

2017-02-20 15:35 UTC, szeiger commented on src/compiler/scala/tools/nsc/typechecker/Typers.scala
> +              try functionType(funArgTypes(argTpWithAlt.map { case (tp, alt) => tp.asSeenFrom(pre, alt.owner) }).transpose.map(lub), WildcardType)
Because I expected it would. There really isn't any deeper or better explanation...

2017-02-20 18:20 UTC, adriaanm commented on src/compiler/scala/tools/nsc/typechecker/Typers.scala
> +              try functionType(funArgTypes(argTpWithAlt.map { case (tp, alt) => tp.asSeenFrom(pre, alt.owner) }).transpose.map(lub), WildcardType)
> Updated (moving asSeenFrom back down into funArgTypes) 
I'm not seeing this update in the diff.

2017-02-21 10:27 UTC, szeiger commented on src/compiler/scala/tools/nsc/typechecker/Typers.scala
> +              try functionType(funArgTypes(argTpWithAlt.map { case (tp, alt) => tp.asSeenFrom(pre, alt.owner) }).transpose.map(lub), WildcardType)
Huh, still had some unstaged changes lying around. Updated again.

2017-02-21 10:31 UTC, lrytz commented on src/compiler/scala/tools/nsc/typechecker/Typers.scala
> +              try functionType(funArgTypes(argTpWithAlt.map { case (tp, alt) => tp.asSeenFrom(pre, alt.owner) }).transpose.map(lub), WildcardType)
That explains my confusion :-)

2017-02-21 10:32 UTC, lrytz approved these changes

2017-02-21 14:10 UTC, merged