SI-10148 Accept verbose zero
scala/scala pull request #5717
Opened 2017-02-18 00:39 UTC by som-snytt

The test for non-zero must recognize `-0e+00f` and variants.

Community build, I think I love you.

2017-02-18 00:47 UTC, Ichoran requested changes
This isn't enough.  -0.0000000000000000e14f doesn't pass, but it is identically zero so it should.  The logic should be `strVal.find(c => c != '0' && c != '.').exists(_.isDigit)` or somesuch

2017-02-18 03:37 UTC, som-snytt commented
Thanks @Ichoran . I couldn't follow somesuch logic so I tried a regex.

I'm grateful they didn't run community build only to fail on your repo with zero to the nth degree.

2017-02-19 04:26 UTC, som-snytt commented
Am I supposed to "dismiss review" after making a change? I don't wish to appear dismissive.

2017-02-19 22:00 UTC, Ichoran approved these changes
This looks like it should work.  Not the most efficient way, but presumably we're not spending very much compilation time parsing floating point numbers in source code.

2017-02-19 22:00 UTC, Ichoran commented
I don't know how it's supposed to work either.  But my new review evicted the old one.

2017-02-19 22:58 UTC, merged

2017-02-19 22:59 UTC, som-snytt commented
More specifically, the test for "did the user write some variant of zero" is invoked rarely, so I focused on maintenance cost over strict efficiency. Moreover, we know the source text is a good float, and we're only checking for good significant digits. We could make it even more efficient if desired.

2017-02-19 23:00 UTC, som-snytt commented
Or Adriaan could just merge it.

2017-02-19 23:07 UTC, Ichoran commented
Adriaan is even more efficient.

2017-02-24 19:29 UTC, SethTisue commented
2.12 community build is green again