SI-10187 Support mutation of mutable.HashMap in getOrElseUpdate
scala/scala pull request #5719
Opened 2017-02-19 04:50 UTC by retronym

Scala 2.12.1 included optimizations to `HashMape.getOrElseUpdate`
to avoid recomputing the index in the hash table when adding an
the element.

However, this index could be stale if the callback added elements
to the map and triggered a resize.

This commit checks that the table is unchanged before reusing
the index, restoring the 2.12.0 behaviour.

Review by @Ichoran

2017-02-19 21:46 UTC, Ichoran commented on src/library/scala/collection/mutable/HashMap.scala
> +    val table0 = table
This is too early.  You don't have to store table0 until right before the `default = defaultValue` inside the `else`.

2017-02-19 21:47 UTC, Ichoran commented on src/library/scala/collection/mutable/HashMap.scala
> +      addEntry(createNewEntry(key, defaultValue), newEntryIndex)
This should be `default` not `defaultValue`.

2017-02-20 13:41 UTC, szeiger requested changes
Looks good apart from the two issues from Rex's comments.

2017-03-03 06:05 UTC, retronym commented
I've updated the code to address the problems @Ichoran pointed out, and also added a test to show we evaluate the `default` callback the right number of times (0 or 1).

2017-03-06 21:14 UTC, paplorinc commented
Sorry for the inconvenience, though I think Java 9 explicitly prohibited this behavior (and in Java 8 it just wasn't working correctly)
http://download.java.net/java/jdk9/docs/api/java/util/Map.html#computeIfAbsent-K-java.util.function.Function- 
> The remapping function should not modify this map during computation.

2017-03-07 03:32 UTC, retronym commented
Yep, we considered just adopting the Java 9 approach of declaring the behaviour undefined, but it seemed easy enough to rework the implementation to keep the old behaviour, which seemed like the conservative thing to do in a minor release.

2017-03-07 08:01 UTC, paplorinc commented
I guess recursivity would make a lot of sense in case of memoization, e.g.
```scala
def factorial(num: Int, memo: mutable.HashMap[Int, Int] = mutable.HashMap(1 -> 1)): Int
  = memo.getOrElseUpdate(num, num * factorial(num - 1, memo))
```
(or could this be done with something like Groovy's [memoized](http://docs.groovy-lang.org/2.4.7/html/gapi/groovy/transform/Memoized.html)?)

2017-03-07 12:51 UTC, szeiger approved these changes

2017-03-10 17:27 UTC, merged