inlineToStr is not exhaustive and does not remove html tags inside HtmlTag
scala/scala pull request #5728
Opened 2017-02-22 20:44 UTC by Philippus

as can be seen on f.e. this page:
http://www.scala-lang.org/files/archive/api/current/scala/beans/BeanInfoSkip.html
when hovering over "BeanInfoSkip" on the right the title tag contains some unwanted text.
HtmlTag(...) and the <strong>, </strong> should not be inside the title-tag.
This PR should fix that problem.

- added missing Inline matches to inlineToStr so it is now exhaustive
- scala.xml.XML.loadString(tag).text will remove all html tags inside the HtmlTag

2017-02-22 22:40 UTC, SethTisue commented
would it be possible (and not unreasonably hard) to add test coverage...?

2017-02-23 09:03 UTC, lrytz commented
I quickly looked at existing scaladoc tests, they test on the model. The PR here doesn't change the model. Maybe @VladUreche can give a hint if it's easy to test this fix?

2017-02-23 09:08 UTC, lrytz commented on src/scaladoc/scala/tools/nsc/doc/html/Page.scala
> +    case HtmlTag(tag) => scala.xml.XML.loadString(tag).text
The `tag` data could be invalid xml, no? For example:

```
import scala.tools.nsc.doc.model._
import scala.tools.partest.ScaladocModelTest

object Test extends ScaladocModelTest {
  override def code = """
  /** Hi<br>there. */
  class A
  """

  def scaladocSettings = ""

  def testModel(root: Package) = {
    import access._
    root._class("A").comment foreach println
  }
}
```

prints

```
Body(List(Paragraph(Chain(List(Summary(Chain(List(Chain(List(Text(Hi), HtmlTag(<br>), Text(there))), Text(.)))))))))
```

and

```
scala> scala.xml.XML.loadString("<br>")
org.xml.sax.SAXParseException: XML document structures must start and end within the same entity.
```

2017-02-23 09:08 UTC, Philippus commented
I would like to add test cases but it will be a little annoying to do so as the method is inside a larger structure. 
The initial tests for the PR where the method `inlineToStr` is introduced are in `/scala/test/scaladoc/run/shortDescription-annotation.scala`and those tests repeat the `inlineToStr`-method inside the test.

2017-02-23 09:52 UTC, Philippus commented on src/scaladoc/scala/tools/nsc/doc/html/Page.scala
> +    case HtmlTag(tag) => scala.xml.XML.loadString(tag).text
Indeed, I will look into it a little later. I'd prefer to not use a regex, but maybe that's the way to go.

2017-02-23 18:25 UTC, adriaanm commented
/rebuild

2017-02-24 12:43 UTC, lrytz commented
/rebuild

2017-02-24 21:01 UTC, lrytz commented
/synch

2017-02-24 21:03 UTC, SethTisue commented
(in my experience, retroactive application of `[ci: last-only]` doesn't work as a way to make the "combined" red X disappear, you just have to `/nothingtoseehere` it)

2017-02-24 21:03 UTC, lrytz commented
ok, that "/synch" didn't help, the "combined" status is still red. anyway, it would be a good idea to squash all these commits into one and `push -f`.

2017-02-24 21:04 UTC, lrytz requested changes

2017-02-24 21:04 UTC, lrytz commented on test/scaladoc/run/inlineToStr-strips-unwanted-text.scala
> +    }
Copy-pasting is not ideal, obviously.. Given that this function doesn't depend on the class `Page` in which it is defined, how about pulling it out into the companion object? I don't see a problem with that function being public (vs. protected).

2017-02-24 21:08 UTC, lrytz commented on test/scaladoc/run/inlineToStr-strips-unwanted-text.scala
> +    /** This comment contains an <strong>html tag</strong> */
could alo add a test with nested html tags

2017-02-25 12:25 UTC, Philippus commented on test/scaladoc/run/inlineToStr-strips-unwanted-text.scala
> +    }
ok!

2017-02-25 12:26 UTC, Philippus commented on test/scaladoc/run/inlineToStr-strips-unwanted-text.scala
> +    /** This comment contains an <strong>html tag</strong> */
ok!

2017-02-25 12:26 UTC, Philippus commented
after the tests complete, I will try squashing the commits.

2017-03-02 09:26 UTC, Philippus commented
@lrytz when you have time, could you take another look?

2017-03-02 09:42 UTC, lrytz approved these changes

2017-03-02 09:42 UTC, lrytz commented
Thanks a lot!

2017-03-02 09:43 UTC, merged

2017-03-03 20:44 UTC, SethTisue commented
seen in the Scala community build at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/1301/consoleFull:

```
[scalatest] scala.MatchError: scala.tools.nsc.doc.base.MemberLookupBase$$anon$1@1ee38638 (of class scala.tools.nsc.doc.base.MemberLookupBase$$anon$1)
[scalatest] 	at scala.tools.nsc.doc.html.Page$.inlineToStr(Page.scala:124)
[scalatest] 	at scala.tools.nsc.doc.html.Page$.$anonfun$inlineToStr$1(Page.scala:113)
[scalatest] 	at scala.tools.nsc.doc.html.Page$.$anonfun$inlineToStr$1$adapted(Page.scala:113)
[scalatest] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
[scalatest] 	at scala.collection.immutable.List.foreach(List.scala:390)
[scalatest] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
[scalatest] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
[scalatest] 	at scala.collection.immutable.List.flatMap(List.scala:353)
```

looks like a regression as a result of this PR?

2017-03-03 21:22 UTC, lrytz commented
Indeed - the pattern here is too narrow: https://github.com/scala/scala/pull/5728/files#diff-53f51aedd9537e3ba6f849e248398165R124, should probably be

```
    case EntityLink(title, _) => inlineToStr(title)
```

@Philippus do you have time to take a look?

2017-03-03 22:09 UTC, Philippus commented
yes I have time. I've managed to reproduce it with
`/** This comment contains a [[link ,,with a subscript title,,]] */`
shall I commit a fix (and test) to this branch?

2017-03-03 22:15 UTC, SethTisue commented
> shall I commit a fix (and test) 

yes please

> to this branch?

hmm... well, we'll need a new PR. I guess you could reuse the same branch? I don't think it matters

you're in good company, the community build has been catching a lot of regressions lately.

2017-03-03 22:16 UTC, Philippus commented
ok, I'll make a new PR.