SI-10206 tighten fix for SI-6889
scala/scala pull request #5736
Opened 2017-02-23 23:46 UTC by adriaanm

There are more supertypes of `AnyRef` than you might think:
`?{def clone: ?}` is one example...

2017-02-24 00:12 UTC, retronym commented on src/compiler/scala/tools/nsc/typechecker/Implicits.scala
> +            val outSym = out.typeSymbol
I think I like this approach better than mine. Another thing I was thinking about in was whether we might accidentally be contributing unwanted constraints to type variables in `out` in the old approach using `<:<`. Your approach also avoids that.

Noting that if `out` is itself a refinement type of `AnyRef`, `.typeSymbol` will not give us `AnyRefClass` (which is a good thing here, as we don't want to disallow that.

One corner case might be `AnnotatedTypes` with an annotation checker that treats `AnyRef @foo`  as distinct from `AnyRef` and uses implicits to model conversions between the two?

2017-02-24 00:18 UTC, adriaanm commented on src/compiler/scala/tools/nsc/typechecker/Implicits.scala
> +            val outSym = out.typeSymbol
Good catch on the annotated types! I'll add an exclusion for those.

2017-02-24 02:38 UTC, SethTisue commented
is there any risk to targeting 2.11.x here? 2.12.x being the safer choice generally

2017-02-24 03:41 UTC, adriaanm commented
I'm comfortable with it, but I'll let Jason decide in his review. I think this is both narrow and enough of an improvement to just include here.

2017-03-02 19:55 UTC, adriaanm commented
@retronym, could you enter your final review verdict using the System

2017-03-02 22:55 UTC, retronym requested changes
I'd like to see the test case from SI-10206 included, otherwise LGTM.

https://github.com/retronym/scala/blob/a58d8e89beb748ad8a2208322a0cf539a6b9c85c/test/files/pos/t10206.scala

2017-03-06 19:52 UTC, adriaanm commented
Tests added

2017-03-20 23:03 UTC, adriaanm commented
ping @retronym

2017-03-20 23:23 UTC, retronym approved these changes

2017-03-21 18:53 UTC, merged

2019-09-04 20:45 UTC, som-snytt commented
It was issue 6899.

2019-09-04 20:53 UTC, SethTisue commented
title fixed, ticket link added to PR description

2019-09-04 20:55 UTC, som-snytt commented
(Paulp had made the error on the mailing list, so this might have been an in-joke which I ruined.)