Optimize VectorBuilder#++=(xs: TraversableOnce)
scala/scala pull request #5740
Opened 2017-02-24 17:02 UTC by monkey-mas

We can improve the performance by using `xs.foreach(+=(_))` instead of using `super.++=(xs)`

Benchmark results are as follows:

before
```
[info] Benchmark                      (size)  Mode  Cnt          Score        Error  Units
[info] VectorBenchmark.builderConcat       1  avgt   20      61304.834 ±   5649.373  ns/op
[info] VectorBenchmark.builderConcat      10  avgt   20     143109.259 ±  22050.573  ns/op
[info] VectorBenchmark.builderConcat     100  avgt   20    1087507.944 ±  15564.617  ns/op
[info] VectorBenchmark.builderConcat    1000  avgt   20    9975918.443 ±  52197.275  ns/op
[info] VectorBenchmark.builderConcat   10000  avgt   20  101155017.712 ± 988804.970  ns/op
```

after
```
[info] Benchmark                      (size)  Mode  Cnt         Score         Error  Units
[info] VectorBenchmark.builderConcat       1  avgt   20     38958.564 ±    1012.915  ns/op
[info] VectorBenchmark.builderConcat      10  avgt   20    116479.188 ±     916.548  ns/op
[info] VectorBenchmark.builderConcat     100  avgt   20    789017.215 ±    4176.121  ns/op
[info] VectorBenchmark.builderConcat    1000  avgt   20   7428021.120 ±   41471.026  ns/op
[info] VectorBenchmark.builderConcat   10000  avgt   20  74379030.621 ± 1083102.872  ns/op
```

2017-02-24 21:28 UTC, Ichoran commented
Can you fix this in `Growable` instead?  The problem is that the special loop case is `LinearSeq` when it should be `LinearSeqOptimized`.

2017-02-25 12:53 UTC, monkey-mas commented
Thanks for your feedback! I might be wrong but it seems like I can't fix `Grawable#++=(...)` as I want to use [VectorBuilder#+=(...)](https://github.com/scala/scala/pull/5740/files#diff-59f3462485b74027de4fd5e9febcc81bL646) to optimize the code.

2017-02-25 16:07 UTC, Ichoran commented
@monkey-mas - Growable has `+=`.

2017-02-25 16:47 UTC, monkey-mas commented
> The problem is that the special loop case is LinearSeq when it should be LinearSeqOptimized

Can you please be more specific? What do I exactly have to do for `Growable#++=(...)` in this case?

2017-02-25 23:43 UTC, Ichoran commented
Just change `LinearSeq` to `LinearSeqOptimized` and benchmark again.  `Vector` is a `LinearSeq`, but it has a relatively slow head/tail decomposition.  It is _not_ a `LinearSeqOptimized`, so it will fall back to the `foreach(b += _)` branch.

2017-02-26 04:14 UTC, monkey-mas commented
> Vector is a LinearSeq

Vector extends [IndexedSeq](https://github.com/scala/scala/blob/2.13.x/src/library/scala/collection/immutable/Vector.scala#L66). am I correct?

2017-02-27 00:31 UTC, Ichoran commented
It extends both IndexedSeq, because it can index more efficiently than O(n), and LinearSeq because it can do a head/tail decomposition more efficiently than O(n). It does _not_ extends LinearSeqOptimized because head/tail decomposition is not among the fastest operations it can do.

2017-02-27 05:10 UTC, xuwei-k commented
```scala
$ scala -language:_
Welcome to Scala 2.12.1 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_112).
Type in expressions for evaluation. Or try :help.

scala> :paste
// Entering paste mode (ctrl-D to finish)

def getSuperClasses(clazz: Class[_]): List[Class[_]] = {
    @scala.annotation.tailrec
    def loop(o: Class[_], result: List[Class[_]]): List[Class[_]] = {
      val superClass = o.getSuperclass
      if (superClass == null) {
        result
      } else {
        loop(superClass, superClass :: result)
      }
    }
    loop(clazz, List(clazz))
  }

  def allSuperClassAndTrait(clazz: Class[_]): List[Class[_]] = {
    def loop(c: Class[_], result: List[Class[_]]): List[Class[_]] = {
      val interfaces = c.getInterfaces.toList
      if (interfaces.size == 0) {
        c :: result
      } else {
        interfaces.flatMap{ i => loop(i, i :: result) }
      }
    }

    val classes = for {
      c <- getSuperClasses(clazz)
      result <- loop(c, Nil)
    } yield result

    (classes.toSet - clazz).toList.sortBy(_.toString)
  }


// Exiting paste mode, now interpreting.

getSuperClasses: (clazz: Class[_])List[Class[_]]
allSuperClassAndTrait: (clazz: Class[_])List[Class[_]]

scala> allSuperClassAndTrait(classOf[Vector[_]]).foreach(println)
class java.lang.Object
interface java.io.Serializable
interface scala.Equals
interface scala.Function1
interface scala.Immutable
interface scala.PartialFunction
interface scala.Serializable
interface scala.collection.CustomParallelizable
interface scala.collection.GenIterable
interface scala.collection.GenIterableLike
interface scala.collection.GenSeq
interface scala.collection.GenSeqLike
interface scala.collection.GenTraversable
interface scala.collection.GenTraversableLike
interface scala.collection.GenTraversableOnce
interface scala.collection.IndexedSeq
interface scala.collection.IndexedSeqLike
interface scala.collection.Iterable
interface scala.collection.IterableLike
interface scala.collection.Parallelizable
interface scala.collection.Seq
interface scala.collection.SeqLike
interface scala.collection.Traversable
interface scala.collection.TraversableLike
interface scala.collection.TraversableOnce
interface scala.collection.generic.FilterMonadic
interface scala.collection.generic.GenericTraversableTemplate
interface scala.collection.generic.HasNewBuilder
interface scala.collection.immutable.IndexedSeq
interface scala.collection.immutable.Iterable
interface scala.collection.immutable.Seq
interface scala.collection.immutable.Traversable
interface scala.collection.immutable.VectorPointer
```

> It extends both IndexedSeq, because it can index more efficiently than O(n), and LinearSeq 

I don't think so. Vector extends only IndexedSeq in Scala 2.12.1

2017-02-27 17:40 UTC, Ichoran commented
@xuwei-k - Oh!  You're right.  My mistake!

Sorry, @monkey-mas!

Still, can you test the speed of adding a list?  That's what the special-case in `Growable` is for.  Vector-vector additions are not test enough of a speed improvement.

I really hate to have to copy superclass code to subclasses to get decent performance.  The algorithm isn't different at all.

2017-03-27 14:16 UTC, lrytz commented
Moving to M2 as this is still being discussed and doesn't change / add any functionality

2017-04-04 11:04 UTC, l0rinc requested changes

2017-04-04 11:04 UTC, paplorinc commented on test/benchmarks/src/main/scala/scala/collection/immutable/VectorBenchmark.scala
> +    val loopSize = 1000
I think you should let `JMH` do the looping instead:
```scala
@Benchmark
def builderConcatEmpty() = Vector.newBuilder[Any] ++= values

@Benchmark
def builderConcat() = values ++= values
```

2017-04-04 11:04 UTC, paplorinc commented on src/library/scala/collection/immutable/Vector.scala
> +  override def ++=(xs: TraversableOnce[A]): this.type = {
Any reason for overriding `++=` instead of `++`?

2017-07-04 15:10 UTC, szeiger commented
@monkey-mas Do you have time to address the remaining comment? We're planning to close the queue for M2 until the end of next week.

2017-11-29 19:24 UTC, adriaanm commented
Closing since this has been inactive for a while. Please consider resubmitting!

2017-11-29 19:24 UTC, closed without merging

2017-12-11 14:59 UTC, monkey-mas commented
I'm very sorry for blocking this. (Haven't got time to do currently.) Please let me reopen it once I'm ready to contribute to it.