Consistify trailing punctuation in spec
scala/scala pull request #5801
Opened 2017-03-23 11:02 UTC by janekdb

Three types of change,

 - Drop trailing comma on some lists
 - Add missed commas on some lists
 - Drop `  .` on some examples

I have assumed trailing `  .` in `scala` examples was not significant - I couldn't infer any meaning in it but happy to be corrected.

2017-03-23 11:05 UTC, janekdb commented
The rich diff option avoids the puzzling blood-bath of red on the first file,
![image](https://cloud.githubusercontent.com/assets/1123855/24244888/a3852222-0fb8-11e7-9ef9-09a85532e49d.png)

2017-04-04 09:23 UTC, l0rinc requested changes

2017-04-04 09:23 UTC, paplorinc commented on spec/06-expressions.md
>  (new A).superA == "Root",
Please join these lines also :)

2017-04-04 09:23 UTC, paplorinc commented on spec/07-implicits.md
> +List[Int] => Ordered[List[Int]],
the list seems to continue here with `Int =>`

2017-04-04 09:23 UTC, paplorinc commented on spec/07-implicits.md
>  ...
if we interpret `...` as more elements to follow, we should keep the `,`.
Otherwise you could delete that also

2017-04-04 09:23 UTC, paplorinc commented on spec/03-types.md
> -abstract class Outer { type T } .
:+1:, why was there a trailing `.` in the first place?

2017-04-10 10:06 UTC, janekdb commented on spec/07-implicits.md
> +List[Int] => Ordered[List[Int]],
Yes, so adding the missing comma makes sense here don't you think?

2017-04-10 10:07 UTC, janekdb commented on spec/07-implicits.md
>  ...
Agreed. Restored.

2017-04-10 10:09 UTC, janekdb commented
@paplorinc Ready for review.

2017-04-10 14:53 UTC, l0rinc approved these changes

2017-04-10 14:53 UTC, paplorinc commented on spec/06-expressions.md
> +(new A).superA == "Root"
:+1:

2017-04-10 14:53 UTC, paplorinc commented on spec/07-implicits.md
> +List[Int] => Ordered[List[Int]],
My mistake, yes :)
:+1:

2017-04-10 16:10 UTC, merged

2017-04-10 16:10 UTC, SethTisue commented
thank you!