Named Arguments & Implicits
scala/scala pull request #5807
Opened 2017-03-27 19:52 UTC by m4dc4p

Fixes a bug where implicit definition is not resolved when using named arguments at call site.

Updates README with info on using SBT_OPTS to increase JVM heap size if OOM occurs.

2017-03-27 19:58 UTC, m4dc4p commented
CLA signed.

2017-03-27 23:36 UTC, m4dc4p commented
@SethTisue

2017-03-28 08:18 UTC, lrytz requested changes
Hi & welcome!

This is going to be more complicated, unfortunately.. Simply removing the argument names leads to unexpected / wrong results.

```
class Test {
  def m(a: Int) = 0
}

object A extends App {
  implicit class Ext(val f: Test) {
    def m(notMyName: String) = 1
  }
  assert((new Test).m("works") == 1)
  assert((new Test).m(a = "compiles") == 1) // weird, there's no parameter named `a` in the selected method
}

object B extends App {
  implicit class Ext(val f: Test) {
    def m(a: Int, b: Int) = a - b
  }
  assert((new Test).m(b = 5, a = 10) == 5) // ups...
}
```

2017-03-28 08:18 UTC, lrytz commented on README.md
> +  $ SBT_OPTS=-Xmx8192M
This value is really big, `1536m` is good enough. Also, we should mention here again that we recommend https://github.com/paulp/sbt-extras, which sets `-Xmx1536m` by default. So it could be something like:

Note: If compilation fails with "Out of Memory" errors, set `SBT_OPTS=-Xmx1536m`, or use [sbt-extras](https://github.com/paulp/sbt-extras) (recommended) which defines this setting by default.

Feel free to submit this as a separate PR.

2017-04-03 18:37 UTC, m4dc4p commented
Excellent counter-example, thanks for looking.

2017-04-04 20:30 UTC, m4dc4p commented
@lrytz Can I rebase and force push this PR, or is it better to close and create a new branch?

2017-04-04 20:38 UTC, SethTisue commented
rebasing and force-pushing is totally fine, that's usually how we work

2018-02-24 02:38 UTC, SethTisue commented
closing for inactivity. we can reopen it if activity resumes

2018-02-24 02:38 UTC, closed without merging