Optimize CommandLineParser to avoid exponential cost
scala/scala pull request #5882
Opened 2017-05-03 08:47 UTC by retronym

Echoing the performance bug in the bash scripts (scala/bug#9279),
the command line parser exhibited exponential performance.

When using the command line arguments used to compile the standard
library, which contains ~ 700 source files, I noticed about 1% of
compilation time was being spend in evaluating the regex `(\S+)(.*)`.
Inspection of the parser reveals that this was repeatedly being
called on the rest of the command line as the parser consumed
each argument.

This commit switches to using a regex that only matches the
current argument, and then makes sure to split the input
string using structural sharing of the backing char[] (by using
`CharSequence.subsequence`, rather than high level Scala collections
operations from `StringLike`).

After this change, I no longer this area of code in the profiler
results.

2017-05-04 00:09 UTC, retronym commented
```
[error] Test scala.tools.nsc.backend.jvm.DirectCompileTest.testSeparateCompilation failed: scala.tools.cmd.CommandLineParser$ParseException: Illegal argument:  -d /tmp/1493802034123-0 -cp /tmp/1493802034123-0, took 0.003 sec
[error]     at scala.tools.cmd.CommandLineParser$.$anonfun$tokenize$1(CommandLineParser.scala:93)
[error]     at scala.tools.cmd.CommandLineParser$.tokenize(CommandLineParser.scala:97)
[error]     at scala.tools.testing.BytecodeTesting$.newCompilerWithoutVirtualOutdir(BytecodeTesting.scala:138)
[error]     at scala.tools.testing.BytecodeTesting$.compileClassesSeparately(BytecodeTesting.scala:173)
[error]     at scala.tools.nsc.backend.jvm.DirectCompileTest.testSeparateCompilation(DirectCompileTest.scala:79)
[error]     ...
```

2017-05-04 00:09 UTC, retronym commented
I'll re-open when I address the test failure.

2017-05-15 16:02 UTC, adriaanm requested changes
Looks good, but I do have a few nits to pick.

2017-05-15 16:02 UTC, adriaanm commented on src/compiler/scala/tools/cmd/CommandLineParser.scala
> +        val prefixLen = next.prefixLength(Character.isWhitespace)
For extra tidiness, could avoid the`leadingWhitespace` string with:

```
val leadingWhitespaceLen = next.prefixLength(Character.isWhitespace)
val rest = next.substring(leadingWhitespaceLen, next.length)

if (leadingWhitespaceLen == 0 && rest.nonEmpty)
```

2017-05-15 16:02 UTC, adriaanm commented on src/compiler/scala/tools/cmd/CommandLineParser.scala
> +        case Some(prefix) => Some(prefix, s.substring(prefix.length, s.length()))
Inconsistent use of `length()` and `length`

2017-05-15 19:17 UTC, som-snytt commented on src/compiler/scala/tools/cmd/CommandLineParser.scala
> +        case Some(prefix) => Some(prefix, s.substring(prefix.length, s.length()))
laugh + confused emoji might be ambiguous. @ jenkins, this comment should not require human intervention, sorry, I mean intervention by a team developer. Jenkins, old chap, you are the humanist i.e. most human, not "human bigot". Can robots be bigoted or only roboted?

2017-05-15 21:53 UTC, adriaanm commented on src/compiler/scala/tools/cmd/CommandLineParser.scala
> +        case Some(prefix) => Some(prefix, s.substring(prefix.length, s.length()))
I've been puzzling over this comment. Could you help a human out? Am I being too nitpicky?

Not sure which smiley I'll get for this one, but I just noticed there's an overload of substring that only takes a `beginIndex`.

2017-05-15 23:27 UTC, som-snytt commented on src/compiler/scala/tools/cmd/CommandLineParser.scala
> +        case Some(prefix) => Some(prefix, s.substring(prefix.length, s.length()))
I just meant a linter should save you time on this sort of style comment.

I hope you're catching some of the Mr Rogers marathon. He's so good.

2017-05-15 23:34 UTC, retronym commented
I've denitted the patch.

2017-05-25 02:36 UTC, adriaanm approved these changes

2017-05-25 02:36 UTC, merged

2017-05-25 04:26 UTC, som-snytt commented on src/compiler/scala/tools/cmd/CommandLineParser.scala
> +          Left("Arguments should be separated by whitespace.") // TODO: can this happen?
Not quite an answer, but as per the comment on the quote extractor:
```
scala> scala.tools.cmd.CommandLineParser.tokenize(""""abc"def""")
scala.tools.cmd.CommandLineParser$ParseException: Arguments should be separated by whitespace.
```

2018-05-11 06:58 UTC, som-snytt commented on src/compiler/scala/tools/cmd/CommandLineParser.scala
> +          Left("Arguments should be separated by whitespace.") // TODO: can this happen?
Fixed in the latest denitting.