Make SeqLike.distinct access HashSet once per entry
scala/scala pull request #6022
Opened 2017-08-03 04:35 UTC by jxtps

The old distinct first does a contains (`!seen(x)`), then does the insert, with each of these operations doing the full elemToEntry, index, and search dance. Since HashSet.add returns a true if the element was added (false otherwise) we can get away with doing that dance only once.

2017-08-07 05:11 UTC, retronym commented on src/library/scala/collection/SeqLike.scala
> -        seen += x
In the case that `Set#apply` would have returned `true`, the new formulation actually does a bit more work by updating the set with the new element. So I'd expect the new version to be slightly slower when there are many copies of given elements.

It does appear to do less work in the case that `xs.distinct.size / xs.size` is closer to 1.

Would you care to test out these variations in a benchmark? See #5537 for an good example of a benchmark-driven performance patch.

2017-08-07 06:31 UTC, retronym requested changes
Benchmarks needed to evaluate tradeoff

2017-09-18 21:10 UTC, adriaanm commented
Ping! 👋  For this to ship as part of 2.12.4, it will have to be mergeable by Sep 27.

2018-01-15 04:16 UTC, retronym commented
I'm going to close this due to inactivity. If you have the time/inclination to followup with the benchmarks, please @-mention me and I can reopen this PR.

2018-01-15 04:16 UTC, closed without merging