Topic/t10253
scala/scala pull request #6397
Opened 2018-03-08 19:02 UTC by thestuckster

Fixes Latex formatting issues due to trailing '.

2018-03-08 19:17 UTC, thestuckster commented
I have signed the CLA

2018-03-12 01:38 UTC, retronym commented
Many of these changes affect the content of compiler error messages, which is why some tests are failing. You would need to run `sbt 'partest --update-check'` to automatically update the `test/files/*.check` files for the failing tests.

2018-03-12 01:44 UTC, thestuckster commented
@retronym thanks for the comment, that will help a lot! I thought I was going to have to manually update them all and I just haven't had the time do it so that is a godsend

2018-03-12 15:13 UTC, thestuckster commented
/rebuild

2018-03-12 18:44 UTC, SethTisue commented
/synch

2018-03-12 18:47 UTC, SethTisue requested changes
looks good except for the one accidentally modified file. also, before final merge, can you squash all of this into a single commit, please?

2018-03-12 18:47 UTC, SethTisue commented on src/build/dbuild-meta-json-gen.scala
> +
this change appears to been inadvertent

2018-03-12 18:49 UTC, SethTisue commented
Squashing to a single commit should un-confuse Scabot & Jenkins, I think.

2018-03-12 20:26 UTC, thestuckster commented
Can do, I'll revert the change on that file and I'll make a new branch / PR with just one commit for all the changes to make it easier on the build system

2018-03-12 20:50 UTC, SethTisue commented
note that a new PR isn't necessary; you can force-push to this one. (but if you find it easier to just make a new PR instead, that's fine too.)

2018-03-12 22:09 UTC, thestuckster commented
Making a new PR seemed the easiest option IMO, you can find the new one here: https://github.com/scala/scala/pull/6418

thanks for the help!

2018-03-12 22:22 UTC, closed without merging