Allow compilation of files in empty package to a -d <symlink>
scala/scala pull request #6450
Opened 2018-03-21 08:13 UTC by retronym

Fixes a regression in 2.12.5

Before:
```
⚡ mkdir /tmp/foo; ln -s /tmp/foo /tmp/foo-symlink

⚡ qscalac -d /tmp/foo-symlink $(f "package p1; class C")

⚡ qscalac -d /tmp/foo-symlink $(f "class C")
error: error writing C: Can't create directory /tmp/foo-symlink; there is an existing (non-directory) file in its path
one error found
```

After:

```
⚡ qscalac -d /tmp/foo-symlink $(f "package p1; class C")

⚡ qscalac -d /tmp/foo-symlink $(f "class C")

⚡ touch /tmp/exists
```

And after, error cases:

⚡ qscalac -d /tmp/exists $(f "class C")
scalac error: /tmp/exists does not exist or is not a directory
  scalac -help  gives more information

⚡ rm /tmp/exists

⚡ mkdir -p /tmp/out1/p1

⚡ qscalac -d /tmp/out1 $(f "class C")

⚡ qscalac -d /tmp/out1 $(f "package p2; class C")

⚡ qscalac -d /tmp/out1 $(f "package p1; class C")

⚡ touch /tmp/out1/p3

⚡ qscalac -d /tmp/out1 $(f "package p3; class C")
error: error writing p3/C: Can't create directory /tmp/out1/p3; there is an existing (non-directory) file in its path
one error found
```

2018-03-21 11:48 UTC, lrytz requested changes
What happnes if parent is an existing symlink, but pointing to a file (not a directory)?

2018-03-21 11:48 UTC, lrytz commented on src/compiler/scala/tools/nsc/backend/jvm/ClassfileWriters.scala
> +              // but that's find for us (and common enough, `scalac -d /tmp` on mac targets symlink).
typo "that's find" -> "fine"

2018-03-21 11:56 UTC, retronym commented
> What happnes if parent is an existing symlink, but pointing to a file (not a directory)?

Added that to the manual tests commit msg / PR description.

2018-03-21 12:21 UTC, lrytz approved these changes

2018-03-21 12:22 UTC, retronym commented
/synch

2018-03-21 20:24 UTC, merged

2018-03-23 20:22 UTC, som-snytt commented
I wonder if this solves [this problem](https://github.com/scala/bug/issues/10763#issuecomment-371567222) compiling to `-d /tmp` on MacOS.  I don't have the mac with me to try it out.

2018-03-23 20:41 UTC, retronym commented
Yep, that’s the problem I noticed.

2019-11-29 16:20 UTC, som-snytt commented
I forgot that problem, which is `f--d in dotty`.