Update to Jline 2.14.6
scala/scala pull request #6478
Opened 2018-03-28 14:20 UTC by hvesalai

This version of Jline fixes three things for Emacs, which means all
the special handling of emacs can be removed from scala-code.

The things fixed in Jline 2.15.6 are:
- ANSI colors are now enabled for Emacs.
- Terminal echo is now disabled for Emacs.
- History is enabled for all dump terminals.

This PR should be cherry-picked or merged also to the 2.11 and 2.13 branches.

2018-03-28 14:20 UTC, hvesalai commented
ping @fommil

2018-03-28 18:49 UTC, SethTisue commented
assignment to 2.12.6 milestone is tentative, we need to consider whether it's sufficiently safe

2018-03-28 19:00 UTC, fommil commented
the only thing I could imagine that this might impact is ammonite... could somebody maybe manually check it against this build?

2018-03-28 19:48 UTC, hvesalai commented
The changes between jline-2.14.5 and jline-2.14.6 are really small and can be summarized as:
- changes that affect jline terminal selection when the environment variable `INSIDE_EMACS` is set
- a new constructor to `UnsupportedTerminal` (old default constructor intact)
- storing of input history: it is stored also for dumb terminals
- a new constructor to `FileHistory` (old constructors intact)

Two of the changes change public interfaces of classes, but only by adding new constructors. To my knowledge that will not break anything, except some very twisted reflective thing that is expecting only one constructor.

2018-04-03 09:19 UTC, adriaanm requested changes
Thanks! With one small change, I'm happy to include this in 2.12.6.

2018-04-03 09:19 UTC, adriaanm commented on src/compiler/scala/tools/nsc/Properties.scala
> -  def isEmacsShell         = propOrEmpty("env.emacs") != ""
This may be used elsewhere. Juuuuust to be remain on the safe side, let's deprecate instead of removing.

2018-04-03 12:30 UTC, hvesalai commented
Added the review request as a separate commit, can be squash merged.

2018-04-03 12:31 UTC, adriaanm approved these changes
Thanks!

2018-04-03 13:19 UTC, merged