Be more explicit about the unsoundness holes used by the collections.
scala/scala pull request #6508
Opened 2018-04-10 13:30 UTC by julienrf

Insert explicit @uncheckedVariance annotations even for private[this]
or protected[this] members.

This commit is a port of scala/collection-strawman#521.

These changes are not required by the Scala compiler, but they will be required if the Dotty project wants to compile the Scala collections. Or, if we disable the `protected[this]`/`private[this]` escape hatch in Scala too. For reference, this is the Dotty PR that made these changes required to be able to compile the collections with Dotty: lampepfl/dotty#4013

2018-04-11 12:51 UTC, lrytz commented
Some tests failed: https://scala-ci.typesafe.com/job/scala-2.13.x-validate-main/780/testReport/

2018-04-12 14:44 UTC, julienrf commented
Fixes https://github.com/scala/collection-strawman/issues/475, scala/collection-strawman#505 and scala/collection-strawman#547.

2018-04-25 08:07 UTC, lrytz requested changes
Could you add a comments why we went for this (unsound) solution, and what the consequences are (which / when overrides are necessary for correctness)?

There are more `protected[this]` methods that were not annotated `@uncheckedVariance` in this PR: `IterableOps.coll`, `IterableOps.fromIterable`, `IterableOps.newSpecificBuilder`, `WithFilter.filtered`. Could those be made unqualified `protected`? Or should they be annotated as well?

2018-04-25 08:07 UTC, lrytz commented on src/library/scala/collection/Iterable.scala
> +  protected[this] def fromSpecificIterable(coll: Iterable[A @uncheckedVariance]): C
Also here.

2018-04-25 08:07 UTC, lrytz commented on src/library/scala/collection/Iterable.scala
> +  protected[this] type IterableCC[X] = CC[X] @uncheckedVariance
Comment welcome here as well, maybe something a bit more general that also covers why there's other type aliases in subclasses (`MapCC`, `BitSetC`)

2018-04-25 08:07 UTC, lrytz commented on src/library/scala/collection/Iterable.scala
> +    `this`: IterableOps[A, CC, _],
Maybe call the parameter `self`?

2018-04-25 08:07 UTC, lrytz commented on src/library/scala/collection/Map.scala
> +    `this`: MapOps[K, V, CC, _] with IterableOps[(K, V), IterableCC, _],
Same suggestion here to use `self`

2018-04-25 08:07 UTC, lrytz commented on src/library/scala/collection/SortedMap.scala
> +    `this`: SortedMapOps[K, V, CC, _] with MapOps[K, V, MapCC, _] with IterableOps[(K, V), IterableCC, _],
Also here...

2018-04-25 08:07 UTC, lrytz commented on src/library/scala/collection/SortedSet.scala
> +    `this`: SortedSetOps[A, CC, _] with IterableOps[A, IterableCC, _],
and here

2018-04-25 08:45 UTC, julienrf commented
> There are more protected[this] methods that were not annotated @uncheckedVariance in this PR: IterableOps.coll, IterableOps.fromIterable, IterableOps.newSpecificBuilder, WithFilter.filtered. Could those be made unqualified protected? Or should they be annotated as well?

They don’t need the `@uncheckedVariance` annotation because they don’t break variance rules.

2018-04-25 08:52 UTC, julienrf commented
I think we should keep the `protected` qualifier but we could remove the `[this]` scope. I think the motivation for using `protected[this]` was that disables variance checking, but since this escape hatch has been removed in Dotty we wanted to not rely on it here as well. Unless there is another reason for using `protected[this]` over just `protected`?

2018-04-25 09:05 UTC, lrytz commented
AFAIK, `protected[this]` disallows using the member from instances other than `this`:

```
scala> class C { protected def a = 0; protected[this] def b = 0 }
defined class C

scala> class K extends C { def test(o: K) = { this.a; this.b; o.a; o.b } }
<console>:12: error: value b is not a member of K
       class K extends C { def test(o: K) = { this.a; this.b; o.a; o.b } }
                                                                     ^
```

I don't think we need that in the collections. So I think we should just use plain `protected`.

Thinking about it: since we add the necessary `@uncheckedVariance` annotations, we should also change those annotated methods to plain `protected` - or is there a reason to keep `protected[this]`?

2018-04-25 09:11 UTC, julienrf commented
> Thinking about it: since we add the necessary @uncheckedVariance annotations, we should also change those annotated methods to plain protected - or is there a reason to keep protected[this]?

That’s what I was thinking too… But since these operations are unsound (well, those that have `@uncheckedVariance` annotations), we should probably keep restricting their visibility?

2018-04-25 09:15 UTC, lrytz commented
Well, the difference between `protected` and `protected[this]` is marginal. In fact, making them `protected` hast the advantage that the compiler will actually tell you if you *don't* add the `@uncheckedVariance` annotation, which is a good thing IMO.

2018-04-25 09:39 UTC, julienrf commented
@lrytz I’ve added a commit that moves from `protected[this]` to just `protected`, and adds some documentation. Let me know if this is enough.

2018-04-25 11:06 UTC, lrytz reviewed
Some tests need updating https://scala-ci.typesafe.com/job/scala-2.13.x-validate-main/954 (in the sbt console, `> partest --update-check test/files/neg/abstract-report.scala`)

2018-04-25 11:06 UTC, lrytz commented on src/library/scala/collection/Iterable.scala
> +  protected def fromSpecificIterable(coll: Iterable[A @uncheckedVariance]): C
Maybe you can also add a comment here, and to `newSpecificBuilder` (restrictions on how this method can be used)

2018-04-25 11:38 UTC, lrytz commented
Thanks a lot, LGTM now! The changes need to be rebased (conflict in `StringOps.scala`) and squashed (to get a green "combined" status).

2018-04-25 11:41 UTC, julienrf commented
Thanks for reviewing! I’ve just rebased and squashed the commits.

2018-04-25 11:51 UTC, lrytz approved these changes

2018-04-25 12:40 UTC, julienrf commented
I’m surprised by the new failure. I don’t think it’s related to my changes. I’ve just try to run the same test from the `2.13.x` branch and it fails as well.

2018-04-25 12:42 UTC, lrytz commented
Not your fault, I'm taking a look.

2018-04-25 13:34 UTC, SethTisue commented
@julienrf a quick rebase should fix it (because #6557)

2018-04-25 13:35 UTC, julienrf commented
OK, I’ve done a quick rebase then.

2018-04-26 07:59 UTC, merged