Add missing operations to ArrayOps
scala/scala pull request #6572
Opened 2018-04-27 19:35 UTC by szeiger

plus some related bug fixes

Fixes https://github.com/scala/collection-strawman/issues/567

2018-04-30 14:01 UTC, szeiger commented
The test errors appear to be caused by a binary incompatible partest after bootstrapping, so this needs to be rebased after merging https://github.com/scala/scala/pull/6566

2018-05-10 14:04 UTC, lrytz commented on src/library/scala/collection/ArrayOps.scala
> +  def head: A = try xs.apply(0) catch { case _: ArrayIndexOutOfBoundsException => throw new NoSuchElementException }
Should we pass on the exception message? Or maybe use `initCause`?

2018-05-10 14:08 UTC, lrytz commented on src/library/scala/collection/ArrayOps.scala
> +  def head: A = try xs.apply(0) catch { case _: ArrayIndexOutOfBoundsException => throw new NoSuchElementException }
Actually I realize that doesn't make sense for head / tail, so this looks fine.

2018-05-10 14:11 UTC, lrytz commented on src/library/scala/collection/ArrayOps.scala
> +  def head: A = try xs.apply(0) catch { case _: ArrayIndexOutOfBoundsException => throw new NoSuchElementException }
`"head/last of empty array"` would make sense though

2018-05-11 21:11 UTC, adriaanm commented
/synch

2018-05-11 21:12 UTC, adriaanm commented
/rebuild

2018-05-14 11:36 UTC, lrytz requested changes

2018-05-14 11:36 UTC, lrytz commented on src/library/scala/collection/ArrayOps.scala
> +    val b = ArrayBuilder.make[B]()
this seems to be unused

2018-05-14 11:36 UTC, lrytz commented on src/library/scala/collection/ArrayOps.scala
> +    val lo = if(i < 0) xs.length else i
`hi` and `lo` are identical, that looks suspicious

2018-05-14 13:45 UTC, lrytz approved these changes

2018-05-14 16:14 UTC, merged