Improve efficiency of scope lookup
scala/scala pull request #6615
Opened 2018-05-11 04:08 UTC by retronym

- Avoids a redundant calls to lookupEntry
  - Avoid iterator allocation in more cases when the lookup finds nothing
  - Avoid indirection through Iterator Context.lookup

2018-05-12 06:07 UTC, retronym commented
Here's a minimization of the regression in bootstrap:

```scala
case class ClassDef(a: Any)

trait T {
  def ClassDef(a: Any): Any
}
class C extends T {
  def ClassDef(a: Any) = a match {
    case t @ ClassDef(_) => t
  }
}

```

```
sandbox/test.scala:9: error: method ClassDef is not a case class, nor does it have an unapply/unapplySeq member
    case t @ ClassDef(_) => t
             ^
one error found
```

2018-05-24 08:57 UTC, retronym commented on src/compiler/scala/tools/nsc/typechecker/Contexts.scala
> +          symbolDepth = (cx.depth - cx.scope.nestingLevel) + e1.depth
This does need to capture `symbolDepth` in a object ref, I can't see a good way to avoid that. It is only one per call to `lookupSymbol`.

2018-05-24 09:30 UTC, lrytz requested changes

2018-05-24 09:30 UTC, lrytz commented on src/compiler/scala/tools/nsc/typechecker/Contexts.scala
> +        symbolDepth = -1
This is unnecessary as we return anyway on the next line.

2018-05-24 09:32 UTC, lrytz commented
hmm, my other comment got lost. it was: can we move the `return` keyword into the block, here https://github.com/scala/scala/pull/6615/files#diff-04639e477fcdf844cf3ae0e3e4bf5d7eR1113

2018-05-25 01:19 UTC, retronym commented
I've made those changes.

2018-05-25 07:30 UTC, lrytz approved these changes

2018-05-25 07:30 UTC, merged

2018-05-25 09:17 UTC, retronym commented
Benchmarks like it:

![image](https://user-images.githubusercontent.com/65551/40536637-33ce982a-6050-11e8-8113-ff16c84819ad.png)
![image](https://user-images.githubusercontent.com/65551/40536669-433d7a88-6050-11e8-851d-5cfe214e9241.png)