Remove element type from mutable.ArraySeq.(elemTag|array)
scala/scala pull request #6648
Opened 2018-05-15 11:29 UTC by szeiger

ArraySeq can be boxed or unboxed for primitives and could have been
created with an `Array[AnyRef]` for arbitrary reference types, so we
cannot guarantee any specific element type for the backing array.

Fixes https://github.com/scala/bug/issues/10851

2018-05-15 11:48 UTC, lrytz requested changes
We have the same issue for `immutable.ArraySeq`

```
scala> collection.immutable.ArraySeq.untagged(1,2,3).unsafeArray
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [I
  ... 33 elided
```

Could you also add some tests?

2018-05-30 15:31 UTC, szeiger commented
Updated to cover `immutable.ArraySeq`, too.

2018-05-30 16:11 UTC, szeiger commented on src/library/scala/collection/immutable/ArraySeq.scala
> -  // uncheckedVariance should be safe: Array[A] for reference types A is covariant at the JVM level. Array[A] for
So much for my assumptions...

2018-05-30 20:35 UTC, lrytz approved these changes

2018-05-30 20:35 UTC, merged