add deprecated DefaultMap in immutable package object
scala/scala pull request #6787
Opened 2018-06-13 09:22 UTC by xuwei-k

`scala.collection.immutable.DefaultMap` is not deprecated in Scala 2.12.6. but deleted suddenly since Scala 2.13.0-M4

https://github.com/scala/scala/blob/v2.12.6/src/library/scala/collection/immutable/DefaultMap.scala

2018-06-13 09:33 UTC, xuwei-k commented
FYI, deprecated `scala.collection.DefaultMap` exists.

https://github.com/scala/scala/blob/v2.13.0-M4/src/library/scala/collection/DefaultMap.scala

2018-06-14 06:41 UTC, dwijnand approved these changes
SGTM!

2018-06-15 12:29 UTC, szeiger requested changes
I don't think this will help. `DefaultMap` is usually extended, not used as a type, but you cannot use a type for that, it has to be a trait.

2018-06-15 12:54 UTC, adriaanm commented
You can extend a type alias, assuming it expands to a trait / class:

```
scala> trait T
defined trait T

scala> type TT = T
defined type alias TT

scala> class C extends TT
defined class C
```

2018-06-15 13:14 UTC, szeiger commented
Hm, is this a recent feature? I thought I had tried that in the past and it didn't work.

2018-06-15 13:14 UTC, szeiger approved these changes

2018-06-15 13:21 UTC, dwijnand commented
You can even construct values via type aliases:

```scala
scala> type WaitWhat[A] = Some[A]
defined type alias WaitWhat

scala> new WaitWhat(1)
res0: Some[Int] = Some(1)
```

2018-06-15 13:22 UTC, merged