Optimize ScalaRunTime.array_length
scala/scala pull request #6881
Opened 2018-07-03 13:27 UTC by isaacl

java.lang.reflect.Array.get_length is a jdk intrinsic.

jmh bench shows about 3x speedup
```
lenNew  avgt   10  13.343 ± 0.265  ns/op
lenOld  avgt   10  36.554 ± 1.057  ns/op
```
http://gist.github.com/isaacl/a365bf39afd81964b68f1c94f1c2b1a0/raw

For scala/bug#10968.

2018-07-07 13:21 UTC, isaacl commented
@retronym ^

2018-07-07 15:18 UTC, ijuma commented
If I remember correctly, the Java code was used originally. But it was slow and hence the change. It may be that it has been optimized since, but it would be good to confirm with benchmarks.

2018-07-09 01:50 UTC, som-snytt commented
The previous comment sounds familiar.

2018-07-09 03:31 UTC, retronym commented
a326f40dbf25e50976d17a3a90bdd2dc5e37a87e moved the control flow into Scala code rather than calling the Java versions. That's pretty old, so if the motivation was performance the landscape has probably changed significantly since then.

2018-07-09 03:41 UTC, retronym commented
I looked at the OpenJDK implementation of some of these in this [chat](https://gitter.im/scala/contributors?at=5b39ad6181816669a4282e4c).

The native implementation of `Array.getLength` looks better than what we can do (it exploits the fact that all array classes have the `length` field in the same spot). C2 JIT inlines access to that data into the native code for methods that call it.

`get` / `set`: the native implementation can do a switch to pick the right code path, rather than our `instanceof` cascade, which in theory is faster.  But they are just JNI implementations, not a JIT intrinsic, so there might be a performance penalty of the JNI boundary.

In addition, we need to handle the special case of unboxing `null` to `0` to get the Scala semantics.

2018-07-09 03:52 UTC, retronym reviewed
We'll need to drive this with micro benchmark. My intuition is that `array_length` will be a winner but the others might be hampered by the fact that they can't be inlined across the JNI boundary.

2018-07-09 03:52 UTC, retronym requested changes
We'll need to drive this with micro benchmark. My intuition is that `array_length` will be a winner but the others might be hampered by the fact that they can't be inlined across the JNI boundary.

2018-07-09 04:40 UTC, ijuma commented
Yeah, the JNI boundary was the issue then. If it can't be inlined, then it's definitely expensive given the cost of the underlying operation. As you say, it was a long time ago then and a microbenchmark would clarify things.

2018-07-09 06:41 UTC, NthPortal commented
If I'm not mistaken, at least on HotSpot, hot JNI methods will get JIT-ed, to remove the JNI boundary costs.

2018-07-09 06:56 UTC, retronym commented
I pretty sure that's not true.

```
scala> val a = Array[String]("")
a: Array[String] = Array("")

scala> java.lang.reflect.Array.get(a, 0)
res0: Object = ""

scala> while (true) java.lang.reflect.Array.get(a, 0)
Started [cpu] profiling
Profiler already started
Started [cpu] profiling
```

```
$ git clone jvm-profiling-tools/async-profiler; cd async-profiler; make all
$ ./profiler.sh -d 5 -f /tmp/profile.jfr -o jfr 64579
```

![image](https://user-images.githubusercontent.com/65551/42435075-d246753e-8398-11e8-8e56-5b64d5eb5090.png)

2018-07-10 02:26 UTC, smarter commented
> get / set: the native implementation can do a switch to pick the right code path, rather than our instanceof cascade, which in theory is faster. But they are just JNI implementations, not a JIT intrinsic, so there might be a performance penalty of the JNI boundary.

Maybe we should try contributing intrinsified versions to HotSpot ?

2018-07-11 03:35 UTC, isaacl commented
OK my bench shows the JNI methods are significantly slower than our scala impl, so I removed array_apply and array_set changes from the PR.

array_length change is a win.
```
lenNew  avgt   10  13.343 ± 0.265  ns/op
lenOld  avgt   10  36.554 ± 1.057  ns/op
```
http://gist.github.com/isaacl/a365bf39afd81964b68f1c94f1c2b1a0/raw

2018-07-11 03:40 UTC, retronym approved these changes

2018-07-11 04:39 UTC, som-snytt commented
The only problem now is how to spend all those spare ns.

2018-07-11 06:28 UTC, merged