Trim forwarders from Reporting [ci: last-only]
scala/scala pull request #6969
Opened 2018-07-24 16:26 UTC by som-snytt

The forwarders `inform`, `globalError`, `warning` were
marked `deprecatedOverriding`, but this commit just removes
them in favor of `reporter.error` etc. This reduces the
`global` namespace and focuses attention on the `Reporter`
interface, reducing confusion as to which `warning` to use.

2018-07-24 19:27 UTC, som-snytt commented
sbt needs inform and warning, in 0.13. Looks like latest zinc uses both warning and reporter.warning.

2018-08-03 10:02 UTC, adriaanm requested changes
Paranoid, perhaps, but rather not take any risks this close to ~~RC0~~ M5

2018-08-03 10:02 UTC, adriaanm commented on src/reflect/scala/reflect/internal/Reporting.scala
> -  @deprecatedOverriding("This forwards to the corresponding method in reporter -- override reporter instead", "2.11.2")
I would prefer to leave these in place and make them plain `@deprecated`. Sadly, you never know who may be calling us here.

2018-08-03 11:44 UTC, jvican commented
Are we sure we want to remove this (and even deprecate it)? I know of lots of compiler plugins that don't use `reporter` that would need to be updated after this change in 2.13, mine included.

2018-08-03 20:38 UTC, som-snytt commented
`sbt` is the canary. I'll close for now. I wasn't sure it was the direction previously intended, though my personal opinion is that it's confusing, in a way that goes back to `global.error`.

2018-08-03 20:38 UTC, closed without merging

2018-08-04 10:13 UTC, adriaanm commented
I would like to remove these forwarders, but maybe it’ll have to wait until
3.0 ;-)
On Fri, Aug 3, 2018 at 22:38 som-snytt <notifications@github.com> wrote:

> sbt is the canary. I'll close for now. I wasn't sure it was the direction
> previously intended, though my personal opinion is that it's confusing, in
> a way that goes back to global.error.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/scala/scala/pull/6969#issuecomment-410370025>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAFjy3QAoYG0qOoEkwgj-icBLtVMDxaFks5uNLTagaJpZM4VdEJk>
> .
>

2018-08-04 15:52 UTC, som-snytt commented
With the `-Yimports` PR, it's trivial to add `global` conversions to your build, and even on a per-2.x basis. I sure hope that PR makes it in.