Add a default to ImplicitSearch ctor arg to unbreak shapeless
scala/scala pull request #6971
Opened 2018-07-25 07:20 UTC by milessabin

The introduction of the `isByNamePt` constructor argument of `ImplicitSearch` breaks the use of this constructor by shapeless. This commit fixes that by adding a default argument.

I'd be happy to also reorder the arguments so that isByNamePt comes last, or alternatively reinstate the previous constructor signature via a secondary constructor.

2018-07-25 07:36 UTC, retronym commented
I think a deprecated secondary constructor with the old signature would be best.

2018-07-25 07:38 UTC, retronym requested changes
[Requesting change to secondary constructor]

2018-07-25 08:01 UTC, milessabin commented
A deprecated secondary doesn't really help me, because then I'd have to disable `-deprecation` or `-Xfatal-warnings` for 2.13.x.

2018-07-25 08:09 UTC, milessabin commented
>  it feels awkward to have the default parameter for isByNamePt and not have a default for the subsequent parameter.

Agreed. I think it'd be best to move `isByNamePt` to the end of the primary constructor argument list. I would have done that in the first place, but I wanted to start with the smallest possible change that'd fix the problem and iterate from there.

2018-07-25 09:05 UTC, milessabin commented
@retronym done. If that doesn't work for you I'll have to go with variant source for 2.13.x in shapeless ... not pleasant, but not the end of the world.

2018-07-25 23:39 UTC, retronym approved these changes

2018-07-25 23:39 UTC, merged

2018-07-26 09:49 UTC, milessabin commented
Thanks!