Accept numeric literal separators and leading zero
scala/scala pull request #6989
Opened 2018-07-29 17:42 UTC by som-snytt

`000123`, `000_123`, `000'123`, `3_14e-0_2`.

2018-08-02 17:37 UTC, szeiger commented
Marking as WIP until the status of this change (SIP? Micro-SIP?) is clear.

2018-08-02 17:44 UTC, som-snytt commented
@szeiger Thanks. SWIP.

2018-08-07 12:59 UTC, som-snytt commented
@adriaanm @SethTisue Probably a syntax change can't land in 2.13.1? "It's just syntax."

2018-08-09 15:19 UTC, sjrd commented
There is a precedent: trailing commas landed in 2.12.2.

2018-08-09 17:58 UTC, SethTisue commented
right, we don't guarantee forward source compat, only forward binary compat

2018-08-09 18:59 UTC, som-snytt commented
Wow, I thought "It's just syntax" was just a saying. I'm going to start using trailing commas everywhere now. Or everywhere except 0.13 builds, I guess.

2018-11-02 11:18 UTC, lrytz commented
What's next here? I'd personally prefer supporting only one of the two separators.

2018-11-03 22:35 UTC, NthPortal commented
+1 to Lukas' comment. I'm in favour of `_` personally, although I can't think of a good justification for that

2018-11-03 22:53 UTC, som-snytt commented
The only part I feel strongly about is `1l`, and the identifier `lintel`, is @propensive listening?

Maybe I'll break that out into another PR and y'all can scrabble over the rest.

2018-11-04 22:22 UTC, som-snytt commented
There was a long discussion elsewhere in which Ichoran expressed a personal preference for `1234'5678`. I have no preference except to avoid the foisting of preferences.

Here is the commit rebased and slightly cleaner. The warnings were pushed to the linked PR. It should be easy for someone else to push a tweak once the committee makes up its mind.

2018-11-14 12:49 UTC, adriaanm commented
Our approach here is usually to copy Java, which means just having underscore: https://docs.oracle.com/javase/8/docs/technotes/guides/language/underscores-literals.html

2018-11-14 13:14 UTC, soronpo commented
Does Java accept a leading zero?

2018-11-14 17:41 UTC, som-snytt commented
@soronpo Java supports octal syntax.

2018-11-14 18:51 UTC, som-snytt commented
I was not inspired to add a forking `-Ynumeric-separator`.

2018-12-04 17:15 UTC, som-snytt commented on src/compiler/scala/tools/nsc/ast/parser/Scanners.scala
> +      if (s.exists(isNumberSeparator)) s.replaceAll("_","").replaceAll("'","") else s
Could you tighten that up?

2018-12-04 19:03 UTC, som-snytt commented
Since this change has sat in the queue for four months, I pushed an improvement. Now
```
123_456
```
desugars to
```
(f: (Int, Int) => Int) => f(123, 456)
```

2018-12-04 19:18 UTC, soronpo commented
> desugars to ...

Why is this good?

2018-12-04 19:54 UTC, som-snytt commented
The underscore stands for a missing operator, of course.

Naturally, there are implicit macros that provide just the numeric syntax.

I'm sure I can add more features if the PR stays open through the winter holidays, when the grog will flow more freely.
```
scala> val g = 123_456
g: ((Int, Int) => Int) => Int = $$Lambda$846/393481646@1c504e66

scala> g(_ + _)
res0: Int = 579

scala> import scala.lang.syntax._

scala> 123_456()
res1: Int = 123456
```

2018-12-04 19:56 UTC, som-snytt commented
I'm going to backport place-holder syntax for operators to openjdk 12, so Scala will remain as Java-like as possible.

2018-12-04 23:07 UTC, SethTisue commented
this is ready for merge, right? I'm certainly in favor of the change.

2018-12-04 23:09 UTC, SethTisue requested changes
this looks ready to go (post-squash), except that it should include a spec update

2018-12-04 23:11 UTC, SethTisue commented
as always, our compass is [WWGD?](https://github.com/golang/go/issues/28493)

2018-12-04 23:13 UTC, SethTisue commented
@jvican @darjutak did this go before the SIP committee?

2018-12-04 23:59 UTC, som-snytt commented
It's been before the SIP committee of public opinion.

I'll spec and squash. I omitted place-holder syntax for operators after all, as usual the feature was sunk by the difficulty of specifying it cleanly.

2018-12-05 08:59 UTC, adriaanm commented
/cc @olafurpg fyi, small syntax change. We should also think about what this means for round-tripping (normalisation during lexing means we can't print the original source based on the AST.). I'm not saying this has to block the PR, but it's worth documenting.

2018-12-05 09:23 UTC, olafurpg reviewed
This looks great! In Scalameta we already store the original syntax in tokens so the underscores won't be lost during a pretty-printing roundtrip. I recommend to add some position tests (esp. with `-Yrangepos`) to ensure compiler trees are able recover the original syntax.

2018-12-05 09:23 UTC, olafurpg commented on test/files/pos/t6124.scala
> +  def i: Int = 1_024
Can we add a test to assert that the tree positions enclose the full literal?

2018-12-05 19:50 UTC, som-snytt commented
I wonder if it's too late for @SethTisue to delete his go link, in order to avoid inviting folks from other realms to read my dumb jokes. Also, I'd be upset if they implemented `1234'5678` because I think that was a great idea.

2018-12-05 19:52 UTC, som-snytt commented on test/files/pos/t6124.scala
> +  def i: Int = 1_024
I added a quick test that prints and verified the output, which proves nothing but guards against regressions in literal positioning.

2018-12-12 19:19 UTC, som-snytt commented
@SethTisue One, two, three, four, what's the syntax we adore? Numeric underscore!

Fully baked squash pie. This is the rare PR with no thumbs pointed netherward. Even when the mob was all pitchforky about single quote as separator, they dared not jinx it, such was their faith and enthusiasm.

2018-12-14 06:01 UTC, merged

2018-12-14 06:01 UTC, adriaanm commented
Hmmmm 🥧

2018-12-14 06:24 UTC, NthPortal commented
🎉

2018-12-14 06:52 UTC, dwijnand commented
Nice!

Particularly well done for not restricting it to groupings of 3, which wouldn't be very nice towards some numbering systems like https://en.wikipedia.org/wiki/Indian_numbering_system