Document scala.Singleton
scala/scala pull request #7354
Opened 2018-10-20 16:48 UTC by callumcodes

Information from: http://scala-programming-language.1934581.n4.nabble.com/scala-Singleton-td1940630.html

Fixes https://github.com/scala/bug/issues/9525

2018-10-25 10:40 UTC, lrytz requested changes

2018-10-25 10:40 UTC, lrytz commented on src/library-aux/scala/Singleton.scala
> +  *  }}}
I think is a little too technical for a Scaladoc comment. Also, `Singleton` has some valid use cases in user code. My suggestion:

```
`Singleton` is used by the compiler as a supertype for singleton types. This includes literal types,
as they are also singleton types.

{{{
scala> object A { val x = 42 }
defined object A

scala> implicitly[A.type <:< Singleton]
res12: A.type <:< Singleton = generalized constraint

scala> implicitly[A.x.type <:< Singleton]
res13: A.x.type <:< Singleton = generalized constraint

scala> implicitly[42 <:< Singleton]
res14: 42 <:< Singleton = generalized constraint

scala> implicitly[Int <:< Singleton]
                 ^
       error: Cannot prove that Int <:< Singleton.
}}}

`Singleton` has a special meaning when it appears as an upper bound on a formal type
parameter. Normally, type inference in Scala widens singleton types to the underlying
non-singleton type. When a type parameter has an explicit upper bound of `Singleton`,
the compiler infers a singleton type.

{{{
scala> def check42[T](x: T)(implicit ev: T =:= 42): T = x
check42: [T](x: T)(implicit ev: T =:= 42)T

scala> val x1 = check42(42)
                       ^
       error: Cannot prove that Int =:= 42.

scala> def singleCheck42[T <: Singleton](x: T)(implicit ev: T =:= 42): T = x
singleCheck42: [T <: Singleton](x: T)(implicit ev: T =:= 42)T

scala> val x2 = singleCheck42(42)
x2: Int = 42
}}}

See also [[https://docs.scala-lang.org/sips/42.type.html SIP-23 about Literal-based Singleton Types]].
```

2018-11-02 11:22 UTC, callumcodes commented
@lrytz I have updated my PR to include your suggestion

2018-11-02 12:49 UTC, lrytz approved these changes

2018-11-02 12:49 UTC, lrytz commented
Thanks!

2018-11-02 12:49 UTC, merged

2018-11-02 18:36 UTC, SethTisue commented
thank you, and welcome!