Fixes scala/bug#11217, scala/bug#11218 and scala/bug#11220.
scala/scala pull request #7357
Opened 2018-10-21 15:26 UTC by odd

Adds junit test class scala.collection.immutable.VectorMapTest.

2018-10-23 03:18 UTC, SethTisue commented
perhaps this should be run through scala-collections-laws

2018-10-29 13:12 UTC, szeiger commented on src/library/scala/collection/immutable/VectorMap.scala
> +        (slot, null.asInstanceOf[K])
The last two cases could be unified to `case k => (slot, k.asInstanceOf[K])` to avoid unnecessary null and type checks.

2018-10-30 15:23 UTC, mdedetrich requested changes
Is it possible to use the property based tests to test this more comprehensively? There are some that already exist for `VectorMap`

2018-11-06 16:32 UTC, SethTisue commented
> Is it possible to use the property based tests to test this more comprehensively?

let's use scala-collection-laws. making it easier to run scala-collections-laws is on my plate, my last few weeks have been so crazy (Reactive Summit -> Lightbend tech meeting -> SIP retreat -> team meetings in Switzerland) I haven't been able to get to it, but it's a high priority for me to get it done, and far enough in advance of RC1 that we have time to fix any problems it finds

the ticket is https://github.com/scala/scala-dev/issues/411, I'll make a note there to be sure and add VectorMap

@odd but also, does Matthew's suggestion to also improve the property based checks in this repo to cover these bugs seem sensible to you?

2018-11-07 14:49 UTC, odd commented
@SethTisue Making scala-collection-laws easier to use would be great! That would enable me to verify both this PR and the PR for `OrderedMap` (#7145).
@mdedetrich I'm a bit uncertain as to which test class to add the extra tests to? Should I target the `VectorMapTest` in `test/scalacheck`, `VectorMapProperties` in `test/scalacheck/scala/collection/immutable`, or `SeqMapTest` in `test/scalacheck`?

2018-11-09 14:42 UTC, mdedetrich commented
`VectorMapProperties` is what contains property checks, these are for property based tests.

2018-11-21 17:09 UTC, odd commented
@mdedetrich Property tests have been added in 6adbff3.

2018-11-23 23:14 UTC, mdedetrich commented
Cool will look at it tomorrow

2018-11-25 23:19 UTC, mdedetrich approved these changes

2018-11-25 23:19 UTC, mdedetrich commented
Looks good on my end, thanks @odd

2018-11-26 15:44 UTC, SethTisue commented
@odd LGTM, squash before merge?

2018-11-26 22:00 UTC, odd commented
@SethTisue Squashed.

2018-12-04 22:47 UTC, merged