Leading import _root_ is always root package
scala/scala pull request #7465
Opened 2018-11-27 00:59 UTC by som-snytt

Warn if there is an alternative relative _root_,
and ignore it.

In any position other than the start of an import
clause, `_root_` remains an ordinary, if rather
homely, identifier.

Fixes scala/bug#6217

2018-11-27 02:45 UTC, som-snytt commented
Actually it needs to happen for other qualifiers, too. I resisted pushing it down to typer.

2018-12-11 19:10 UTC, lrytz approved these changes

2018-12-11 19:11 UTC, lrytz requested changes
Actually, the commit message is out of synch.. could you update it? And squash the two commits. Thanks!

2018-12-11 20:04 UTC, som-snytt commented
Reworded and squashed. I hope this is a useful change for anyone (anyone?) who may need to use `_root_` and do so with confidence. At least until a better solution to this schismatic controversy is discovered in the labs at EPFL.

2018-12-11 20:45 UTC, lrytz approved these changes

2018-12-11 20:45 UTC, merged