Optimize IterableLike grouped function
scala/scala pull request #7557
Opened 2018-12-20 17:10 UTC by bmbferreira

While doing some cpu profiling in a scala application I detected a "hotspot" while calling the `grouped` function. I tried to reimplement it using an ArrayBuffer and two while loops and I think that the performance is a bit better this way.

2018-12-20 20:29 UTC, Ichoran requested changes

2018-12-20 20:29 UTC, Ichoran commented on src/library/scala/collection/IterableLike.scala
> +      val itSize = iterator.size
This will exhaust many iterators.  You need to use `knownSize`.

2018-12-20 20:29 UTC, Ichoran commented on src/library/scala/collection/IterableLike.scala
> +      itSize / size + itSize % size
If size is negative (or zero) this will result in weird stuff.  It's also wrong: try it out with itSize = 100 and size=50.  (You end up with 27 slots but you only need 2.)

You should throw an exception on size <= 0 like `GroupedIterator` does.

2018-12-20 20:29 UTC, Ichoran commented on src/library/scala/collection/IterableLike.scala
> +    arrayBuffer.toIterator
This might be faster in the eager case--can you provide benchmarks please so we know how much faster?

In general I'm reluctant to turn a lazy operation into an eager one unless the performance benefit is pretty large.  (Then it's worth thinking about.)

2018-12-21 07:05 UTC, NthPortal commented on src/library/scala/collection/IterableLike.scala
> +      val itSize = iterator.size
this is 2.12 - there is no `knownSize` :(

It is a very good point though that `size` is almost guaranteed to exhaust the iterator though, and that still needs fixing.

2018-12-21 07:42 UTC, bmbferreira commented on src/library/scala/collection/IterableLike.scala
> +      val itSize = iterator.size
oh, I was so fool trying to find the ArrayBuffer size this way... Should I use a ListBuffer instead?

2018-12-21 07:43 UTC, bmbferreira commented on src/library/scala/collection/IterableLike.scala
> +      itSize / size + itSize % size
you're absolutely right, this was very naive... Thanks for the feedback.

2018-12-21 08:13 UTC, bmbferreira commented on src/library/scala/collection/IterableLike.scala
> +    arrayBuffer.toIterator
I just did some benchmarking like this:

```scala
val testList = (1 to 1000000).toList

def time[A](a: => A, n:Int) = {
    var times = List[Long]()
        for (_ <- 1 to n) {
        val now = System.nanoTime
        val res = a
        times :::= List(System.nanoTime - now)
    }
    val result = times.sum / n
    println("%d microseconds".format(result / 1000))
    result
}

time(testList.grouped(7).size, 10)
time(testList.grouped2(7).size, 10)
time(testList.grouped3(7).size, 10)
```

The `grouped` is the original one from the standard library, the `grouped2` function is the one implemented with the ArrayBuffer (and with the problems already reported) and the `grouped3` function is using a ListBuffer, like this:

```scala
def grouped3(size: Int): Iterator[Repr] = {
    val it = iterator
    val listBuffer = new ListBuffer[Repr]()

    while (it.hasNext) {
      val b = newBuilder
      var i = 0
      while (i < size && it.hasNext) {
        b += it.next
        i += 1
      }
      listBuffer += b.result()
    }
    listBuffer.toIterator
}
```

The execution times were:
`grouped`:    68591 microseconds
`grouped2`:  23591 microseconds
`grouped3`:  18040 microseconds


I'll do more benchmarking using JMH but from these results I think that the performance benefit may be worth it.

2018-12-21 09:33 UTC, bmbferreira commented on src/library/scala/collection/IterableLike.scala
> +    arrayBuffer.toIterator
Oh, and btw, using thyme like this:

```scala
val th = ichi.bench.Thyme.warmed(verbose = print)
val testList = (1 to 1000000).toList
th.pbench(testList.grouped(7).size)
th.pbench(testList.grouped2(7).size)
th.pbench(testList.grouped3(7).size)
```

I got these results for `grouped`, `grouped2` and `grouped3` respectively:
```
Benchmark (20 calls in 1.841 s)
  Time:    73.97 ms   95% CI 71.84 ms - 76.11 ms   (n=19)
  Garbage: 14.00 ms   (n=8 sweeps measured)

Benchmark (60 calls in 1.393 s)
  Time:    21.55 ms   95% CI 20.72 ms - 22.38 ms   (n=20)
  Garbage: 1.000 ms   (n=4 sweeps measured)

Benchmark (20 calls in 405.5 ms)
  Time:    15.73 ms   95% CI 15.01 ms - 16.45 ms   (n=19)
  Garbage: 2.800 ms   (n=2 sweeps measured)
```

And also, I want to add that this implementation is quite similar to the [List splitAt implementation](https://github.com/scala/scala/blob/cbb284dbd2a7dfab895e11c0831324cb63528cd8/src/library/scala/collection/immutable/List.scala#L190).

2019-02-11 04:41 UTC, Ichoran commented on src/library/scala/collection/IterableLike.scala
> +    arrayBuffer.toIterator
You should use `pbenchOff(){ testList.grouped(7).size }{ testList.grouped2(7).size }`.  Thyme is a lot better at producing robust results in head-to-head tests than flat ones.

2019-05-24 14:05 UTC, adriaanm commented
Sorry it's been so long, but I don't think we can merge this. What if we want to get a grouped iterator over an infinite Stream?

```
Welcome to Scala 2.12.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_181).
Type in expressions for evaluation. Or try :help.

scala> Stream.from(1, 1).grouped(10).take(5).toList
res0: List[scala.collection.immutable.Stream[Int]] = List(Stream(1, ?), Stream(11, ?), Stream(21, ?), Stream(31, ?), Stream(41, ?))
```

The eager behavior in this PR will break lazy collections (verified on the above example), and will have very different memory consumption for strict, but large, collections.

2019-05-24 14:05 UTC, closed without merging