Change LazyList to have a strict head
scala/scala pull request #7558
Opened 2018-12-21 05:38 UTC by NthPortal

Resolves scala/bug#11307.

2018-12-21 05:39 UTC, NthPortal commented
Opening this so others can see how it looks and suggest changes/simplifications. Please don't merge until the discussion on the relevant issue is completed.

2019-01-08 22:54 UTC, NthPortal commented
I will try to get this sometime later this week

2019-01-11 04:11 UTC, NthPortal commented
I think this is ready for review.

Left a few overrides calling super with TODOs to revisit for potential minor laziness improvements. Because the overrides are there, they don't need to be addressed before 2.13.0.

2019-01-11 04:33 UTC, SethTisue commented
(I don't see Scaladoc changes, shouldn't there be some of those?)

2019-01-11 05:09 UTC, NthPortal commented
@SethTisue the docs were already hopelessly out of date - this PR doesn't make them any more so. Updating them is a task for scala/bug#11131

2019-01-12 20:22 UTC, Ichoran requested changes
Overridden methods that don't need to be overridden should be removed (and in some cases the superclass implementation could be improved!), but otherwise this looks like a great simplification.

2019-01-12 20:22 UTC, Ichoran commented on src/library/scala/collection/immutable/LazyList.scala
> +  override def endsWith[B >: A](that: collection.Iterable[B]): Boolean = super.endsWith(that)
That could be arbitrarily expensive with all those comparisons that you otherwise could skip.  I think the super implementation is the right one, and you should just remove this override and let it use the one from Seq.  `LinearSeq` as a whole could probably use an override that sped up some common scenarios, but this is the PR for that.

2019-01-12 20:22 UTC, Ichoran commented on src/library/scala/collection/immutable/LazyList.scala
> +  override def endsWith[B >: A](that: collection.Iterable[B]): Boolean = super.endsWith(that)
Actually, you should fix the `Seq` one to early-return `false` if `length` is less than `that.length`.  Lots of expensive stuff that could be skipped there.  Also, to return `true` if `that` is empty (without evaluating the current collection at all, not even calling `length`).  This is better for everyone, but especially important for avoiding unnecessarily eager behavior in `LazyList`.

2019-01-12 20:22 UTC, Ichoran commented on src/library/scala/collection/immutable/LazyList.scala
> +  override def lastIndexOfSlice[B >: A](that: collection.Seq[B], end: Int): Int =
Just remove this method and let the superclass handle it.  The `Seq` implementation already special-cases `IndexedSeq` and everything else; any benefits should be applied there.  (It uses KMP searching, so it's nontrivial to improve on it.)

2019-01-17 07:24 UTC, NthPortal commented on src/library/scala/collection/immutable/LazyList.scala
> +  override def lastIndexOfSlice[B >: A](that: collection.Seq[B], end: Int): Int =
@Ichoran after more thought, I'm thinking that this method (and `endsWith`) should not attempt to preserve any laziness of `that` - would you agree?

2019-01-17 07:36 UTC, NthPortal commented
@Ichoran I believe I have addressed your comments

2019-01-23 01:11 UTC, Ichoran approved these changes
Changes LGTM--let's get this in and more thoroughly tested (e.g. with collections-laws)

2019-01-23 01:23 UTC, Ichoran commented
Handled the merge conflict.  Let's see if the tests go through.

2019-01-23 13:18 UTC, NthPortal commented
@Ichoran there's a test in `LazyListTest` that checks that `updated` throws eagerly; I'll remove it tonight since Stefan's PR already added a test for the correct behaviour.

2019-01-25 22:52 UTC, NthPortal commented
/sync

2019-01-25 22:52 UTC, NthPortal commented
ping

2019-01-27 18:08 UTC, merged

2019-01-28 01:57 UTC, SethTisue commented
nice to have this settled 🙂