bug fix #11270. Overrode distinctBy to detect cycles and help termina…
scala/scala pull request #7568
Opened 2018-12-24 01:38 UTC by ashwinbhaskar

…te. Removed lazyness test for distinctBy and distinct as checking if the list is cyclic cannot be lazy

2018-12-24 07:20 UTC, NthPortal commented
I think if adding cycle detection removes laziness, it's not worth it. Cycles aren't that common, and laziness is much more important.

2019-01-23 01:33 UTC, Ichoran requested changes
This looks like it would work, but it's not very efficient.  Can you try an algorithm that repeats less work?

2019-01-23 01:33 UTC, Ichoran commented on src/library/scala/collection/immutable/LazyList.scala
> +    var set = Set[B]()
I doubt using an immutable set here is the fastest way to do this.

2019-01-23 01:33 UTC, Ichoran commented on src/library/scala/collection/immutable/LazyList.scala
> +    internalDistinct(distinctLL = LazyList(),slowIterator = this, fastIterator = if(this.isEmpty) this else this.tail).reverse //reversed to maintain original sequence
This does all the slow/fast work twice, first by checking to see if it's a cyclic case, and then actually handling it.  Can we change this to just do the work on the first pass (using the same algorithm as the superclass so it's just as efficient)?

2019-01-27 05:22 UTC, ashwinbhaskar commented
@Ichoran It works. And your suggestions are also good. But it still removes the laziness right? Optimizing will not help here, IMHO. We have to find a way to keep the evaluation still lazy and somehow detect cycles. Hence I am closing this PR. But if you think that it can be done while still maintaining the laziness, I would be glad to check it out!

2019-01-27 05:22 UTC, closed without merging

2019-01-27 18:38 UTC, Ichoran commented
Won't the existing algorithm run forever?  Being eager and completing is way way better than being eager and hanging.

2019-01-28 05:46 UTC, ashwinbhaskar commented
@Ichoran Yes the existing algorithm will run forever. But the solution rips away the laziness of the list. Being eager will only help when the lazy list is cyclic. But to find out if it is cyclic the above solution traverses through the whole lazy list and ends up evaluating the elements. In the existing solution if you do 
```
val nonCyclic = 1 #:: 2 #:: 3 #:: 4 #:: 5 #:: 6
nonCyclic distinct take 3 println
```
Using the existing algorithm it will evaluate only the first 3 elements and print `1 2 3`. But using the solution of this PR it will traverse through the whole list to find out if it is cyclic or not (Even if you optimize the solution in this PR and do the traversal only once, you still do a traversal of the whole list) and hence end up evaluating elements that are not going to be consumed by println.

Are cyclic lazy lists common in practical scenarios?

2019-01-28 18:46 UTC, SethTisue commented
> Are cyclic lazy lists common in practical scenarios?

I don't know about "common", but I wouldn't call it "rare", either. It's a useful technique when you want something to repeat over and over again, while still only ever consuming finite memory.

It's common enough that it ought to work, but not so common that we should strive for special checks and optimizations around it (IMO). I said something similar on scala/bug#11270