Add inner tail-recursive definitions
scala/scala pull request #7720
Opened 2019-02-06 00:38 UTC by diesalbla

2019-03-14 06:02 UTC, retronym commented on src/reflect/scala/reflect/internal/Types.scala
> +        case _                           => ExistentialType(qsyms, underlying)
Should be `ExistentialType(qsyms, underlying)`

2019-03-14 06:03 UTC, retronym commented
How about just marking the existing methods `@tailrec final`? They aren't designed to be customized in subclasses.

2019-03-14 06:05 UTC, retronym requested changes
- Fix typo in code
 - consider just marking the existing methods `@tailrec` final
 - The (rough) convention in the compiler is to call these inner tail rec methods `loop`.

2019-03-14 07:39 UTC, retronym commented
I'm taking a broader sweep looking for methods that are already tail recursive and ought to be marked as such and methods (like these) that could be tail recursive with a final modifier:

https://github.com/retronym/scala/tree/topic/tailrec-patrol

2019-03-14 07:40 UTC, diesalbla commented
@retronym Regarding marking the methods as `@tailrec` and `final`... can the compiler optimise tail calls in public methods?

2019-03-14 09:37 UTC, retronym commented
Yep

2019-03-14 22:04 UTC, diesalbla commented
After looking at the changes being done by @retronym  https://github.com/retronym/scala/tree/topic/tailrec-patrol, it seems that branch also adds the improvements originally submitted here. 

That being the case, I am closing this PR in favour of Jason's branch.

2019-03-14 22:04 UTC, closed without merging

2019-03-15 01:00 UTC, retronym commented
I've submitted my patch as #7876