Complexity: fold map into the sum.
scala/scala pull request #7797
Opened 2019-02-26 02:20 UTC by diesalbla

Merges the use of a `map` function into the `sum` function, so as to not allocate a list of objects.

2019-02-26 18:21 UTC, som-snytt requested changes
I'm not feeling well yet after a day of massive fever, so forgive me if I'm loopy. (pun)

2019-02-26 18:21 UTC, som-snytt commented on src/compiler/scala/tools/nsc/typechecker/Implicits.scala
> +      }
You could make it more loopy:
```
@annotation.tailrec def g(sum: Int, xs: List[Type]): Int = xs match {
  case h :: t => g(sum + complexity(h), t)
  case _: Nil.type => sum 
}
```
Your `s` is captured, so it's off-stack. You could also consider a while loop and allocating an iterator, but that would not be as fancy.

2019-02-26 22:36 UTC, som-snytt approved these changes

2019-02-26 22:38 UTC, som-snytt commented
Could also just `foldLeft` for compact expression.

2019-02-27 17:52 UTC, SethTisue commented
Travis-CI failure is spurious (scala/scala-dev#617)

2019-02-28 18:56 UTC, merged