11416 MethodType.toString prints in scala format
scala/scala pull request #7798
Opened 2019-02-26 22:49 UTC by psilospore

Issue: 11416

I skimmed through the checkfiles and it seems right to me

2019-03-01 13:56 UTC, azolotko commented on test/files/neg/names-defaults-neg.check
> +both method f in object t3 of type (a2: Int): (b: Int): String
Does this format of multiple parameter lists look as intended? `(a2: Int): (b: Int): String` looks as strange as `(a2: Int)(b: Int)String` did.

2019-03-09 15:54 UTC, hrhino requested changes

2019-03-09 15:54 UTC, hrhino commented on src/reflect/scala/reflect/internal/Types.scala
> +    override def safeToString = s"${paramString(this)}: $resultType"
I think you need to check if `resultType` is a `MethodType` and not add the colon if so. Maybe look at the "object creation impossible" error in `RefChecks` for how it's done there.

2019-03-09 15:54 UTC, hrhino commented on test/files/neg/macro-invalidsig.check
> +Macros_Test_2.scala:60: error: wrong number of type parameters for method foo: [T, U, V](c: scala.reflect.macros.blackbox.Context): (implicit evidence$7: c.WeakTypeTag[T], implicit evidence$8: c.Weak
There's a ticket somewhere adjacent to the fact that we print each param in an implicit param list with `implicit` before it. That enhancement would be in the spirit of this PR, I think.

`def isImplicitParams = params.nonEmpty && params.head.isImplicit` and so on.

Sorry, I mean `!params.isEmpty`. Is that old yet?

2019-06-18 11:32 UTC, SethTisue commented
@psilospore interested in returning to this? PR queue is moving again, post-2.13.0

2019-06-26 19:26 UTC, psilospore commented
Yeap @SethTisue I can start looking at this again

2019-08-24 07:38 UTC, psilospore commented
The recent changes should also only have implicit once instead of before each parameter. e.g. `(a: A)(b: B)(implicit c: C, d: D): E`

2019-09-27 10:00 UTC, lrytz commented
This looks good!

Are we fine with the representation for constructors?

```diff
- t1038.scala:4: error: not enough arguments for constructor X: (x: Int)X.
+ t1038.scala:4: error: not enough arguments for constructor X: (x: Int): X.
```

We should probably also change the `toString` of `NullaryMethodType`:

```scala
scala> class C[-T] { def f: T = ??? }
                         ^
       error: contravariant type T occurs in covariant position in type => T of method f
```

2019-10-02 21:02 UTC, psilospore commented
Thanks! What should the error message look like for NullaryMethodType? Would it be something like 
error: contravariant type T occurs in covariant position in type T of method f

2019-10-10 08:29 UTC, lrytz commented
>  error: contravariant type T occurs in covariant position in type T of method f

I think that looks good.

2020-02-05 01:31 UTC, SethTisue commented
@psilospore interested in returning this? needs a rebase, which will probably be easy. this could make 2.13.2, which we plan to release later this month

2020-02-05 18:56 UTC, psilospore commented
@SethTisue thanks I've updated it!

2020-02-06 01:19 UTC, SethTisue commented
```
!!  1 - res/t687.res                              [output differs][duration 5.97s]
!!  2 - res/t9170.res                             [output differs]
```

2020-02-06 03:06 UTC, psilospore commented
@SethTisue sorry missed that it should be good now

2020-02-06 04:18 UTC, SethTisue commented
we'd better merge this before any more merge conflicts accumulate :-)

2020-02-06 04:18 UTC, merged

2020-02-06 05:55 UTC, lrytz commented
🎉🎉