Guard the Map.map of immutable map with exists clause
scala/scala pull request #7853
Opened 2019-03-12 08:55 UTC by diesalbla

The `map` method of the immutable.Map class may allocate an entire new Map, since it cannot know in advance if the set of keys changes. Since this can be an expensive operation, we avoid it by first
checking if any entry in the Map would be updated.

2019-03-12 10:02 UTC, retronym commented
This phase is certainly ripe for further optimization. I actually have some WIP you might want to take a look at: https://github.com/retronym/scala/tree/topic/spec-unzip

This change looks to be independent of those changes.

2019-03-12 10:46 UTC, retronym commented on src/compiler/scala/tools/nsc/transform/SpecializeTypes.scala
> +    else env
Let's avoid this minor duplication.

```scala
def needsSubst(sym: Symbol, tpe: Type) = sym.owner == origsym && tpe == AnyRefTpe 
val needsChange = env.exists { case (sym, tpe) => needsSubst(sym, tpe)
...
  env map ( binding => if (needSubst(binding._1, binding._2) ... else binding)
```

Same for below.

2019-03-12 10:47 UTC, retronym submitted a review, later dismissed
DRY things up a touch

2019-03-12 12:39 UTC, diesalbla commented
I have DRYed them out to a single higuer-order method, that takes as parameter the function to compute the new value for each key (symbol).

2019-03-13 00:40 UTC, retronym commented
Thinking about this some more, I remembered that `immutable.HashMap` has a `transform` method which we should use rather than `map` when we only need to modify the values, not the keys.

Furthermore, this method has been optimized in 2.13.x to perform structural sharing when the transform is an identity. This means we don't need to do a "read only" pass first with `.exists` to optimize for a common case of identity mapping functions.

I also noticed this optimization was not yet implemented for the hand-specialized, low arity `Map`-s.

I have fixed this and moved to using `transform` in the specialization phase in #7859, targetted to 2.13.x.

We should either mark the commit this PR as `[nomerge]`, or just close this in the knowledge that we'll get the performance benefit soon enough in the 2.13 series.

2019-03-13 00:46 UTC, retronym requested changes
If you agree my 2.13.x solution is okay as the longer term fix, either mark as `[nomerge]` or close

2019-05-24 14:10 UTC, adriaanm commented
@diesalbla how do you feel about leaving this as-is in 2.12? I'm open to merging with the amended commit title as well.

2019-05-24 14:21 UTC, diesalbla commented
@adriaanm That will be fine. I had almost forgotten about this one.

2019-05-24 14:21 UTC, closed without merging