Infer - Remover intermediate lists and functions.
scala/scala pull request #7888
Opened 2019-03-18 22:41 UTC by diesalbla

The `Infer` file uses several functions to break up a result (a mutable map from symbols to types) into separate lists, of symbols matched or not matched to types (keys), and types they were matched to, etc. These functions are provided as "unapply" functions of some objects, to be used in a pattern-match fashion. The implementations of these functions were using some combinations of List operations like `collect`, `partition`, or `HashMap.map`, that were generating some intermediate lists or collections that are not used afterwards. 

This commit, removes those and reimplements each function as a `foreach` loop that builds those lists on mutable buffers.

2019-03-18 23:01 UTC, diesalbla commented on src/compiler/scala/tools/nsc/typechecker/Infer.scala
> +          case (p, Some(a) ) => oksKeys += p ; valsOrNothing += a         ; okTparams += a
Having in mind the comment above, I hope that using a matrix-like alignment will make the code more readable.

2019-03-19 07:40 UTC, retronym requested changes
Let's use this as an opportunity to be more nominal and O-O here..

  - `methTypeArgs` and `adjustTypeArgs` should return in instance of a class `AdjustedTypeArgs`. That can wrap a private field of `mutable.LinkedHashMap[Symbol, Option[Type]]`. 
  - The methods you've introduced can be members of this class.
  - Do we really need the `LinkedHashMap` as an intermediate data structure here? It would seem simpler and more performance to just populate the `okTparams`, `okArgs`, `undetTparams` lists directly in `adjustTypeArgs`.

```scala
class AdjustedTypeArgs(tparams {
  private val

2019-03-20 01:59 UTC, retronym commented
Here's my alternative proposal: https://github.com/scala/scala/pull/7900

2019-03-21 12:14 UTC, diesalbla commented
Closing in favour of https://github.com/scala/scala/pull/7900

2019-03-21 12:14 UTC, closed without merging