Eta lifts function before args.
scala/scala pull request #7963
Opened 2019-04-03 00:16 UTC by hrhino

The comment says it, the spec says it, and most importantly, Dotty says it.

Maybe qualify for the coveted "performance" label by avoiding an argument load.

Fixes scala/bug#11465.

2019-04-03 00:37 UTC, som-snytt requested changes
That was kind of easy. This must also change the examples in the spec 6.7.

2019-04-03 00:37 UTC, som-snytt commented on test/files/run/t11465.check
> +55
Is `55` some sort of senior citizens' joke?

2019-04-03 01:20 UTC, hrhino commented
Ach, good catch. I just read that bit, to be sure of myself, but I didn't read the examples, because who does that anymore?

2019-04-03 01:51 UTC, diesalbla approved these changes

2019-04-06 22:40 UTC, som-snytt approved these changes
Thanks. When I "contributed" the examples to document the state of affairs, Adriaan was like what are you sure. I could've fixed it back then. Obviously, no one seemed to care. And what does that say?

2019-04-12 12:47 UTC, diesalbla commented
@hrhino Is this ready?

2019-04-12 20:47 UTC, hrhino commented
But for timing, should be. I'm in no rush, though.

2019-06-18 12:32 UTC, adriaanm approved these changes

2019-06-18 12:32 UTC, merged