Clarify what Null is a subtype of.
scala/scala pull request #8053
Opened 2019-05-13 00:40 UTC by hrhino

To wit, any non-value-class class type, and non-class value types so declared, but certainly not value-class types.

Okay, okay, that's not what I've made it say. Hopefully this is clearer.

Fixes scala/bug#11479.

2019-05-13 01:56 UTC, dwijnand commented
> ```scala
>  *  `Null` is the type of the `null` literal. It is a subtype of every class type
>  *  except value class types (that is, those which are subtypes of [[AnyVal]]).
> ```

Should the "class" part of "class type" should be dropped?  I think this reads a little clearer:

> ```scala
>  *  `Null` is the type of the `null` literal. It is a subtype of every type
>  *  except value types (that is, those which are subtypes of [[AnyVal]]).
> ```

(I also preferred the "instance of type" rather than the "type of literal" formulation, but it doesn't matter.)

2019-05-14 01:43 UTC, hrhino commented
So this isn't just me being lingustically obfuscatory: the spec defines "class type" as a term (SLS chapter 3): types are divided into "first-order types" and "type constructors"; the subset of first-order types called "value types" are further subdivided into "concrete types" and "abstract types", and then concrete types are resubdivided into "class types" and "compound types" (by which I assume it refers to `RefinedType`). 

I just noticed the fact that compound types are not included as class types. So maybe I'm speaking inaccurately, and the correct statement is that "every _value type_ that is not a subtype of `AnyVal` is a supertype of `Null`", and then I'll have misspoken in both places. What do you call a type `<: AnyVal`, then? Spec parlance doesn't include "value class", but that's what everyone calls them, except now we're talking types, not classes, and "value class type" is risible. (Does `case class Id[X](val self: X) extends AnyVal` allow you to use `case Id(_)` as a "value class type constructor pattern"? Let's not.)

I'm open for suggestions.

    `Null` is the type of the `null` literal. It is a subtype of every reference type (that is, every concrete type which is not a subtype of [[scala.AnyVal]]); this reflects that every such type contains the `null` reference.

2019-05-14 10:17 UTC, dwijnand commented
Thanks, @hrhino.  I suspected there was a reason for initially going with "value class type"; thanks for the references.

I see how my suggestion of "value type" is very misleading.  Maybe:

```scala
 *  `Null` is the type of the `null` literal. It is a subtype of every type
 *  except value classes (that is, those which are subtypes of [[AnyVal]]).
```

But your suggestion at the end of your message works too, for me.

2019-05-15 01:28 UTC, hrhino commented
My only quibble with your wording is that value classes are not types. But this isn't spec, just doc, so it's not so bad. I think I'll do "It is a subtype of every type except those of value classes (that is, ...)". Is that too unwieldy? Can I pretend it's 2010 and say "inline classes"?

2019-05-15 06:54 UTC, dwijnand approved these changes

2019-05-24 15:09 UTC, adriaanm requested changes
Since I'm nitpicking, I've tried to include a ready-to-go batch of suggestions. Maybe I missed school when we covered multi-line suggestions?

2019-05-24 15:09 UTC, adriaanm commented on src/library-aux/scala/Null.scala
> +  * except those of value classes (that is, classes which are subtypes of [[AnyVal]]).
Still kind of confusing to refer back to the "except ..." clause with "this includes", so: "the exception includes"? Does that contract to "exclusion"?

Suggestion line 1:

```suggestion
  * except those of value classes. Value classes are subclasses of [[AnyVal]], which includes
```

2019-05-24 15:09 UTC, adriaanm commented on src/library-aux/scala/Null.scala
> +  * This includes primitive types such as [[Int]] and [[Boolean]], as well
```suggestion
  * primitive types such as [[Int]], [[Boolean]], and user-defined value classes.
```

2019-05-24 15:09 UTC, adriaanm commented on src/library-aux/scala/Null.scala
> +  * as types of user-defined value classes.
```suggestion
```

2019-06-18 11:26 UTC, dwijnand commented
@hrhino this is good to go if you apply (or counter) Adriaan's suggestions!

2019-06-18 11:27 UTC, hrhino commented
Oh! I completely missed noticing Adriaan's suggestions. I'll have a look tonight.

2019-07-17 14:19 UTC, lrytz commented
pong @hrhino :)

2019-07-17 22:30 UTC, hrhino commented
I have no ability to make code changes for the next two weeks, as I'm on vacation without a laptop. Adrian's suggestions sound good, so I'm OK if you want to push them to my branch; otherwise I'll have a computer by August.

2019-07-18 09:23 UTC, lrytz commented
👍 thanks, enjoy your vacation!

2019-07-18 14:13 UTC, lrytz approved these changes

2019-07-18 14:13 UTC, merged