Avoid using the "lines" method.
scala/scala pull request #8333
Opened 2019-08-14 01:55 UTC by diesalbla

When attempting to build Scala on one of the newest JDKs (11 or 12)
the "lines" method is no longer available. Instead, we need to use
linesIterator.

We add a utility to get last of iterator.

2019-08-14 10:40 UTC, hrhino requested changes
See comment

2019-08-14 11:06 UTC, diesalbla commented
@hrhino Sorry, which comment?

2019-08-14 11:07 UTC, hrhino commented
GITHUUUUUUUB!

I promise I did type it in. 

Why do we need `toList` in the places it's used?

2019-08-14 11:15 UTC, diesalbla commented
Oh, because the `scala.Iterator` does not include methods like, say, `last`. In fact, the first time I had written an auxiliary method`def lastOf(Iterator[A]): A`, but then I dropped it.

2019-08-14 11:18 UTC, hrhino commented
Oh. That's unfortunate.

What about the `mkString`s, though?

None of this is performance-critical as I understand, so no biggie.

2019-08-14 22:00 UTC, hrhino submitted a review, later dismissed

2019-08-14 22:00 UTC, hrhino commented on src/reflect/scala/reflect/internal/Printers.scala
> +          if (lines.hasNext) print(k.escapedStringValue)
That's not the same, is it? `hasNext` means `size >= 1`; this should be `size <= 1`. I think `toList` is justifiable.

2019-08-15 12:04 UTC, diesalbla commented
I have been able to compile locally, both the main code and tests, on both versions 11 and 12 of the  `AdoptOpenJDK`, installed by https://sdkman.io.

2019-08-15 15:08 UTC, som-snytt approved these changes
"What I did for lines," was that the old song?

Probably OK, but the one place making a string more expensive might matter is in typer, which could be making strings silently.

2019-08-19 21:54 UTC, hrhino approved these changes

2019-08-19 21:54 UTC, hrhino commented on src/reflect/scala/reflect/internal/Printers.scala
> +            printSeq(lines.map(x => tqp.replaceAllIn(x, tqq)).toList)(print(_))(print(Chars.LF))
You can get rid of this `toList`, too

2019-08-21 15:22 UTC, merged

2019-08-21 17:31 UTC, SethTisue commented
thanks Diego!