Stop warning on higher-kinded usage without -language:higherKinds
scala/scala pull request #8348
Opened 2019-08-19 18:15 UTC by smarter

See https://contributors.scala-lang.org/t/is-f-bound-polymorphism-useful/3618/5

Sadly, it seems that no deprecation warnings are reported on imports,
so `import scala.language.higherKinds` will not warn.

2019-08-19 21:13 UTC, hrhino requested changes
You've got to update a few checkfiles that were (accidentally) asserting the existence of this warning.

Would it make sense to remove the flag everywhere it's used in flags files?

2019-08-19 21:27 UTC, smarter commented
> Would it make sense to remove the flag everywhere it's used in flags files?

I think so yes. More generally it'd be nice to have a deprecation warning when using the `-language:higherKinds` flag but this is beyond my motivation level, help welcome :).

2019-09-08 14:15 UTC, hrhino approved these changes

2019-09-09 15:26 UTC, merged

2019-09-09 16:23 UTC, SethTisue commented
(for the record, this was discussed and approved at a Scala team meeting)