Merge 2.12.x to 2.13.x [ci: last-only]
scala/scala pull request #8440
Opened 2019-09-23 22:17 UTC by retronym

Only change include here is the optimizations to immutable.Map*.hashCode

2019-09-23 22:18 UTC, retronym commented
Marking as WIP until I do some more testing.

2019-09-24 05:26 UTC, retronym commented
Addressed a few problems:

  - boxing of the hashcode coming out of the lambda argument to `nonAllocating { ... }` was costing an allocation. Not sure why the 2.12.x version of this test wasn't failing, maybe it was relying on JVM escape analysis which for some reason doesn't trigger in 2.13.x? Addressed here by using discarding the value. It occurs to me that we really ought to use `jmh.BlackHole` or similar to make sure that code under test is actually run, but I'll leave that for a separate change.
  - Map hash codes changed in 2.13.x because of https://github.com/scala/scala/pull/7634 and https://github.com/scala/scala/pull/7693. I've added a unit test to ensure consistency between the hand-inlined non-allocating versions and the generic version.

2019-09-24 06:29 UTC, mkeskells commented
I modified the `AllocationTest`, e.g. `def nonAllocating` in the 2.12 version
it seems that due to the way that the lambda is captured the method under test generating a int, and that being boxed before checking, so that counted as an extra object

I changed the nonAllocation verson in 2.12 to take account of this allocation like this
```
  val costInt: Long = { 
    object coster extends AllocationTest 
    val costs = coster.allocationInfoImpl(coster.hashCode(), new AllocationExecution(), 0) 
    costs.min 
  } 
```

this wasn't in the 2.13 version, a we never tested allocation on a primitive before

2019-09-24 07:36 UTC, retronym commented
I've pushed a commit to rework things further.

   - Forward port @mkeskells's changes to `AllocationTest` to account for generic boxing of `Integers`.
   - Centralize optimization in `MurmurHash3.mapHash` in terms of `Map.foreachEntry`.

2019-09-24 21:56 UTC, mkeskells commented on src/testkit/scala/tools/testkit/AllocationTest.scala
> +    assertEquals(expected, nonAllocating(if (a == b) "t" else "f"))
I think this is the cause of the failures in the last run
"t" cant equal true

2019-09-24 22:05 UTC, mkeskells commented on src/testkit/scala/tools/testkit/AllocationTest.scala
> +  def min: Long = {
Note - I just unrolled this when looking for the extra allocations

2019-09-24 22:05 UTC, mkeskells commented on src/testkit/scala/tools/testkit/AllocationTest.scala
> +    while (i < execution.executionCount) {
Note - I just unrolled this when looking for the extra allocations

2019-09-25 13:05 UTC, lrytz requested changes

2019-09-25 13:05 UTC, lrytz commented on build.sbt
> +    ProblemFilters.exclude[MissingClassProblem]("scala.collection.immutable.Map$HashCodeAccumulator"),
This class seems to be unused in the final version

2019-09-25 13:49 UTC, lrytz commented
Maybe it's more clear to merge with `-s ours` and apply the 2.13 changes separately?

2019-09-30 03:59 UTC, retronym commented
I've made this PR into a `-sours` no-op merge and will submit a separate PR with the 2.13.x rework.

2019-09-30 17:33 UTC, merged