Update build.sbt
scala/scala pull request #8566
Opened 2019-12-01 20:37 UTC by Meniarayoub

2019-12-01 20:59 UTC, ashawley approved these changes

2019-12-01 22:27 UTC, hrhino requested changes

2019-12-01 22:27 UTC, hrhino commented on build.sbt
> + * The main reason, is that we are not benefiting from sbt's conventions when it comes project
`reason is` sounds better to me, as `reason` is the subject of `is`.

2019-12-02 13:59 UTC, lrytz commented
@Meniarayoub in order to accept your contribution, you need to sign the CLA: lightbend.com/contribute/cla/scala. Thank you!

2019-12-09 13:12 UTC, lrytz commented
Closing because the author did not yet sign the CLA and did not give any sign within a week. @Meniarayoub feel free to re-open.

2019-12-09 13:12 UTC, closed without merging