Mention existence of `-opt:help`
scala/scala pull request #8683
Opened 2020-02-02 14:34 UTC by dwijnand

Looking at `scalac -help` I saw the mention of `help` for
`-opt-inline-from`, but it was only thanks to the deprecation message of
`-optimize` did I learn about `-opt:help`.

So how about we make that more prominent?

2020-02-02 15:05 UTC, hrhino approved these changes
I'd have gone with parens to avoid having to think on whether that's a comma splice or not. I've seen the `opt:help` text in this file but never realized what would cause it to be displayed.

2020-02-02 22:33 UTC, dwijnand commented
> I'd have gone with parens to avoid having to think on whether that's a comma splice or not.

I was following `-opt-inline-from`'s lead: https://github.com/scala/scala/blob/46a81568daeca71ee05364be2a224ffe227e8fe0/src/compiler/scala/tools/nsc/settings/ScalaSettings.scala#L359

2020-02-03 09:34 UTC, lrytz requested changes
mentioning `-opt-warnings:help` would help even more 🙂

2020-02-03 10:30 UTC, lrytz approved these changes

2020-02-03 11:58 UTC, merged

2020-02-03 11:59 UTC, dwijnand commented
```
java.nio.file.NoSuchFileException: /tmp/scala.picklecache2182359323111604117/tmp/pipelineBase7235595933252729861/projects/m1/p1/target.jar
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixPath.toRealPath(UnixPath.java:837)
	at scala.tools.nsc.PipelineMainClass.$anonfun$newCompiler$1(PipelineMain.scala:618)
	at scala.tools.nsc.PipelineMainClass.newCompiler(PipelineMain.scala:615)
	at scala.tools.nsc.PipelineMainClass$Task.liftedTree1$1(PipelineMain.scala:429)
	at scala.tools.nsc.PipelineMainClass$Task.compiler$lzycompute(PipelineMain.scala:428)
	at scala.tools.nsc.PipelineMainClass$Task.compiler(PipelineMain.scala:428)
	at scala.tools.nsc.PipelineMainClass.$anonfun$process$57(PipelineMain.scala:258)
	at scala.tools.nsc.PipelineMainClass.$anonfun$process$57$adapted(PipelineMain.scala:258)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:447)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
java.nio.file.NoSuchFileException: /tmp/scala.picklecache2182359323111604117/tmp/pipelineBase7235595933252729861/projects/m1/p1/target.jar
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixPath.toRealPath(UnixPath.java:837)
	at scala.tools.nsc.PipelineMainClass.$anonfun$newCompiler$1(PipelineMain.scala:618)
	at scala.tools.nsc.PipelineMainClass.newCompiler(PipelineMain.scala:615)
	at scala.tools.nsc.PipelineMainClass$Task.liftedTree1$1(PipelineMain.scala:429)
	at scala.tools.nsc.PipelineMainClass$Task.compiler$lzycompute(PipelineMain.scala:428)
	at scala.tools.nsc.PipelineMainClass$Task.compiler(PipelineMain.scala:428)
	at scala.tools.nsc.PipelineMainClass.$anonfun$process$57(PipelineMain.scala:258)
	at scala.tools.nsc.PipelineMainClass.$anonfun$process$57$adapted(PipelineMain.scala:258)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:447)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[error] Error: Total 0, Failed 0, Errors 0, Passed 0
[error] Error during tests:
[error] 	Running java with options -classpath /home/travis/build/scala/scala/target/junit/test-classes:/home/travis/build/scala/scala/build/quick/classes/junit:/home/travis/build/scala/scala/build/quick/classes/testkit:/home/travis/build/scala/scala/build/quick/classes/compiler:/home/travis/build/scala/scala/build/quick/classes/library:/home/travis/build/scala/scala/build/quick/classes/reflect:/home/travis/build/scala/scala/build/quick/classes/repl-frontend:/home/travis/build/scala/scala/build/quick/classes/repl:/home/travis/build/scala/scala/build/quick/classes/interactive:/home/travis/build/scala/scala/build/quick/classes/scaladoc:/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar:/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/org/openjdk/jol/jol-core/0.9/jol-core-0.9.jar:/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/com/googlecode/java-diff-utils/diffutils/1.3.0/diffutils-1.3.0.jar:/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6.jar:/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/org/webjars/jquery/3.4.1/jquery-3.4.1.jar:/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/junit/junit/4.12/junit-4.12.jar:/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/org/fusesource/jansi/jansi/1.12/jansi-1.12.jar:/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/com/novocode/junit-interface/0.11/junit-interface-0.11.jar:/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-asm/7.0.0-scala-1/scala-asm-7.0.0-scala-1.jar:/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/travis/.sbt/boot/scala-2.12.10/org.scala-sbt/sbt/1.3.7/test-agent-1.3.7.jar:/home/travis/.sbt/boot/scala-2.12.10/org.scala-sbt/sbt/1.3.7/test-interface-1.0.jar sbt.ForkMain 42779 failed with exit code 255
```

```
[error]   - junit/test:testOnly failed: sbt.TestsFailedException: Tests unsuccessful
```

2020-02-03 12:00 UTC, lrytz commented
I assumed that's spurious, let's see :-)

2020-02-03 18:52 UTC, SethTisue commented
@retronym do I remember correctly that you've been on the lookout for these picklecache errors?

2020-02-04 10:25 UTC, som-snytt commented
`help` is implicit:

```
➜ scalac -Wmacros:help -g:help -Wunused:help
Usage: -g:<level> where <level> choices are none, source, line, vars, notailcalls (default: vars).


Usage: -Wmacros:<mode> where <mode> choices are none, before, after, both (default: before).
  none    Do not inspect expansions or their original trees when generating unused symbol warnings.
  before  Only inspect unexpanded user-written code for unused symbols.
  after   Only inspect expanded trees when generating unused symbol warnings.
  both    Inspect both user-written code and expanded trees when generating unused symbol warnings.


Enable or disable specific `unused` warnings
  imports    Warn if an import selector is not referenced.
  patvars    Warn if a variable bound in a pattern is unused.
  privates   Warn if a private member is unused.
  locals     Warn if a local definition is unused.
  explicits  Warn if an explicit parameter is unused.
  implicits  Warn if an implicit parameter is unused.
  params     Enable -Wunused:explicits,implicits.
  linted     -Xlint:unused.
Default: All choices are enabled by default.
```