Add back test for XML NodeBuffer literal
scala/scala pull request #8702
Opened 2020-02-07 18:49 UTC by ashawley

Missing test identified in #8701 where a `run` test was written. This is just a `pos` test.

2020-02-07 18:50 UTC, ashawley commented
Reverting the fix of #9027 and the test fails.  Call it good enough?

```patch
--- src/compiler/scala/tools/nsc/ast/parser/MarkupParsers.scala
+++ src/compiler/scala/tools/nsc/ast/parser/MarkupParsers.scala
@@ -387,11 +387,12 @@ trait MarkupParsers {
 
         // parse more XML?
         if (charComingAfter(xSpaceOpt()) == '<') {
-          do {
-            xSpaceOpt()
+          xSpaceOpt()
+          while (ch == '<') {
             nextch()
             content_LT(ts)
-          } while (charComingAfter(xSpaceOpt()) == '<')
+            xSpaceOpt()
+          }
           handle.makeXMLseq(r2p(start, start, curOffset), ts)
         }
         else {
```

2020-02-08 00:34 UTC, som-snytt requested changes
I think a pos test doesn't hurt! Except for the nit, which I noticed in your test repo, which I'd looked at.

2020-02-08 00:34 UTC, som-snytt commented on test/files/pos/xml-nodebuffer.scala
> +  nodeBuffer.map(println)
Should be `foreach`, so we can look back without any regrets. I mean so we can look at ourselves in the mirror.

2020-02-08 00:36 UTC, som-snytt commented on test/files/pos/xml-nodebuffer.scala
> +  nodeBuffer.map(println)
```suggestion
  nodeBuffer.foreach(println)
```

2020-02-08 01:08 UTC, ashawley commented on test/files/pos/xml-nodebuffer.scala
> +  nodeBuffer.map(println)
Good catch and thanks!

2020-02-08 02:44 UTC, som-snytt approved these changes

2020-02-08 02:45 UTC, merged