Deprecate nested class shadowing
scala/scala pull request #8705
Opened 2020-02-08 03:14 UTC by eed3si9n

Fixes https://github.com/scala/bug/issues/8353
Fixes https://github.com/scala/bug/issues/11360

This deprecates nested class shadowing for Dotty compatibilty.

2020-02-08 04:52 UTC, eed3si9n commented
So the compiler bridge is failing to compile?

```scala
$ sbt -Dstarr.version=$STARR -warn setupValidateTest test:compile info testAll
Detected sbt version 1.3.8
Using jvm options defined in file .jvmopts
# Executing command line:
java
-Xmx1536M
-Xss1M
-Dstarr.version=2.13.2-bin-d4afc05-SNAPSHOT
-jar
/home/travis/.sbt/launchers/1.3.8/sbt-launch.jar
-warn
setupValidateTest
test:compile
info
testAll
....
/tmp/sbt_b22a8908/xsbt/ConsoleInterface.scala:45: error: recursive value loop needs type
    val loop = new ILoop(ShellConfig(interpreterSettings)) {
                   ^
/tmp/sbt_b22a8908/xsbt/ExtractAPI.scala:752: error: recursive value sortClasses needs type
  private[this] val sortClasses = new Comparator[Symbol] {
                                      ^
/tmp/sbt_b22a8908/xsbt/ScaladocInterface.scala:66: error: recursive value generator needs type
          new DefaultDocDriver {
              ^
3 errors
```

2020-02-08 19:06 UTC, eed3si9n commented
RefChecks result looks better

```
[error] 2 of 17 test tasks failed:
[error] - partest run
[error]   - test/it:testOnly failed: sbt.TestsFailedException: Tests unsuccessful
[error] - partest res scalap specialized
[error]   - test/it:testOnly failed: sbt.TestsFailedException: Tests unsuccessful
```

2020-02-10 13:36 UTC, eed3si9n commented
/rebuild

2020-02-11 13:46 UTC, lrytz requested changes

2020-02-11 13:46 UTC, lrytz commented on src/compiler/scala/tools/nsc/typechecker/RefChecks.scala
> +      def checkNestedClassShadow(): Unit =
In principle, `clazz.allOverriddenSymbols.filter(_.isClass)` would be the simplest solution, but this condition rules it out:

https://github.com/scala/scala/blob/57f2e5700927808c8f0dd547d9890c833d5d5900/src/reflect/scala/reflect/internal/Symbols.scala#L2424-L2428

Inlining through the implementation of `allOverriddenSymbols`, this seems to work:

```
scala> :power
Power mode enabled. :phase is at typer.
import scala.tools.nsc._, intp.global._, definitions._
Try :help or completions for vals._ and power._

scala> class C { class I }
defined class C

scala> class D extends C { class I }
defined class D

scala> val clazz = typeOf[D].member(TypeName("I"))
clazz: $r.intp.global.Symbol = class I

scala> val os = clazz.owner.ancestors.map(a => clazz.matchingSymbol(a, clazz.owner.thisType)).filter(c => c.exists && c.isClass)
os: List[$r.intp.global.Symbol] = List(class I)

scala> os.map(_.fullNameString)
res14: List[String] = List(C.I)
```

2020-02-11 19:25 UTC, SethTisue commented
is there some other kind of class shadowing that isn't "nested class shadowing"?

2020-02-11 19:43 UTC, eed3si9n commented
@SethTisue 

The following is OK in Dotty

```scala
scala> class C0 {
     |   class Status
     |   class C1 {
     |     class Status
     |   }
     | }
// defined class C0
```

The following is NOT ok in Dotty:

```scala
scala> trait Base {
     |   class Status
     | }
     |
     | class C0 extends Base {
     |   class Status
     | }
     |
6 |  class Status
  |        ^
  |class Status cannot have the same name as class Status in trait Base -- class definitions cannot be overridden
```

How should we distinguish the two cases?

2020-02-11 19:47 UTC, eed3si9n commented on test/files/neg/nested-class-shadowing.check
> +nested-class-shadowing.scala:9: warning: nested class shadowing is deprecated but class Status shadows class Status defined in trait Core; rename the class to something else
warning: class shadowing that looks like overriding is deprecated but class Status shadows class Status defined in trait Core; rename the class to something else

?

2020-02-11 19:52 UTC, eed3si9n commented on test/files/neg/nested-class-shadowing.check
> +nested-class-shadowing.scala:9: warning: nested class shadowing is deprecated but class Status shadows class Status defined in trait Core; rename the class to something else
warning: shadowing a nested class of a parent class is deprecated but class Status shadows class Status defined in trait Core; rename the class to something else

?

2020-02-11 19:54 UTC, eed3si9n commented on test/files/neg/nested-class-shadowing.check
> +nested-class-shadowing.scala:9: warning: nested class shadowing is deprecated but class Status shadows class Status defined in trait Core; rename the class to something else
warning: shadowing an inherited nested class is deprecated but class Status shadows class Status defined in trait Core; rename the class to something else

?

2020-02-12 10:02 UTC, lrytz commented
> How should we distinguish the two cases?

The difference is this

```
scala> class C0 {
     |   class Status
     |   class C1 {
     |     class Status
     |   }
     | }
defined class C0

scala> trait Base {
     |   class Status
     | }
defined trait Base

scala> class Sub extends Base {
     |   class Status
     | }
defined class Sub

scala> def shadowedInherited(clazz: Symbol) = clazz.owner.ancestors.map(_.info.member(clazz.name)).filter(_.exists)
shadowedInherited: (clazz: $r.intp.global.Symbol)List[$r.intp.global.Symbol]

scala> shadowedInherited(typeOf[C0#C1#Status].typeSymbol)
res0: List[$r.intp.global.Symbol] = List()

scala> shadowedInherited(typeOf[Sub#Status].typeSymbol)
res1: List[$r.intp.global.Symbol] = List(class Status)
```

The current patch that you pushed only deprecates shadowing of an inherited class, which is what we want. Shadowing from an outer scope remains allowed, for classes and for any other definitions.



> How should we distinguish the two cases?

Maybe your question was not technical, but what the best deprecation message would be? I like your second version:

> warning: shadowing a nested class of a parent ~class~ is deprecated but class Status shadows class Status defined in trait Core; rename the class to something else

2020-02-12 13:52 UTC, eed3si9n commented
@lrytz 

> Maybe your question was not technical, but what the best deprecation message would be?

That's right, since Seth noticed that I changed the warning message in the last commit.

> I like your second version:

ok. I'll go with that then.

2020-02-12 14:28 UTC, lrytz approved these changes
👍 LGTM, can be squashed.

2020-02-12 15:40 UTC, eed3si9n commented
Squashed and updated the description.

2020-02-12 15:46 UTC, SethTisue approved these changes

2020-02-12 20:44 UTC, merged

2020-02-24 03:16 UTC, soronpo commented
This PR causes a false class shadowing warning.
https://github.com/scala/bug/issues/11895

2020-02-24 03:19 UTC, soronpo commented
And also in this regard, has anyone compared the community-build's log before and after this PR to see how many deprecation warnings were added (if at all)?

2020-02-25 19:37 UTC, SethTisue commented
> has anyone compared the community-build's log before and after 

carefully worded to avoid actually volunteering ;-)

I don't think we need a before-and-after, just an after, since the error message text is new and thus greppable.

(or is it? not every repo has `-deprecation` enabled, I imagine, but I suppose the great majority do. a before-and-after would address that, I guess, since a number would increment. however, I suspect that nondeterminism (e.g. from parallelism) and timestamps and such would make before-and-after comparison of two full logs difficult)

also It's difficult to get a truly complete log because it's typical in the community build for any full rebuild to suffer from at least one intermittent test failure. but an example of a recent, nearly complete (all but 5 repos) log is https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/3231/consoleText

so let's have a look:

```
% grep 'shadowing a nested class' consoleText.txt| wc -l                          
     123
% grep 'shadowing a nested class' consoleText.txt| cut '-d ' -f 1 | uniq
[shapeless]
[scala-parallel-collections]
[scala-swing]
[slick]
[treehugger]
[redis4cats]
```

HOWEVER, some of these may go away after @som-snytt's https://github.com/scala/scala/pull/8751 , which has not been run through the community build yet.

I have set a reminder to come back to this ticket and try the same thing again after the next time the CB moves to a new Scala 2.13 SHA.

2020-03-04 10:39 UTC, SethTisue commented
(haven't forgotten. waiting for https://github.com/scala/scala/pull/8763 to land before doing fresh runs)

2020-03-06 08:34 UTC, SethTisue commented
if someone wants to grovel through a nearly-complete community build log on this, here's one: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/3267/ (ignore the actual failures, they are either intermittent or unrelated)

2020-03-06 09:29 UTC, soronpo commented
> 
> 
> @eed3si9n here's a nearly-complete community build log on this, mind doing the log-groveling this time? https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/3267/ (ignore the actual failures, they are either intermittent or unrelated)


From what I've seen, now all warnings are justified. Affected libraries are `shapeless`, `scala-parallel-collections`, `scala-swing`, `treehugger`, `slick`
Most uses look like: 
```scala 
trait Parent {
  trait Foo
}
trait Child extends Parent {
  trait Foo extends super.Foo
} 
```
`shapeless` has a class that extends an abstract trait

2020-03-06 09:41 UTC, soronpo commented
Is it possible to fix such issue and still maintain binary/source compatibility? 
In any case, the good this is that warning suppression is coming in this release.

2020-03-06 10:23 UTC, sjrd commented
> Is it possible to fix such issue and still maintain binary/source compatibility?

I cannot think of any way to fix it while maintaining binary compatibility.

2020-03-06 15:43 UTC, eed3si9n commented
For the record, here is the result from running `cat ~/Downloads/jenkins-3267.log | rg "shadowing a nested class"`

<details>

<summary>

> [shapeless] [warn] core/jvm/target/scala-2.13/src_managed/main/shapeless/polyntraits.scala:31:9: shadowing a nested class of a parent is deprecated but class CaseBuilder shadows trait CaseBuilder defined in trait Poly; rename the class to something else
> ....
> [scala-parallel-collections] [warn] core/src/main/scala/scala/collection/parallel/ParSeqLike.scala:477:19: shadowing a nested class of a parent is deprecated but trait Accessor shadows trait Accessor defined in trait ParIterableLike; rename the class to something else
> ....
> [scala-swing] [warn] src/main/scala/scala/swing/RichWindow.scala:42:9: shadowing a nested class of a parent is deprecated but trait InterfaceMixin shadows trait InterfaceMixin defined in class Window; rename the class to something else
> ....
> [treehugger] [warn] library/src/main/scala/treehugger/TreePrinters.scala:37: shadowing a nested class of a parent is deprecated but class TreePrinter shadows trait TreePrinter defined in trait TreePrinters; rename the class to something else
> ....
[slick] [warn] slick/src/main/scala/slick/jdbc/DB2Profile.scala:76: shadowing a nested class of a parent is deprecated but class QueryBuilder shadows class QueryBuilder defined in trait JdbcStatementBuilderComponent; rename the class to something else
> ....
> [redis4cats] [warn] shadowing a nested class of a parent is deprecated but class E$F shadows class E$F defined in class BaseRedis; rename the class to something else
</summary>

```
[shapeless] [warn] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.16/project-builds/shapeless-8255f881981f2eb014acd91e962b0423d9b26365/core/jvm/target/scala-2.13/src_managed/main/shapeless/polyntraits.scala:31:9: shadowing a nested class of a parent is deprecated but class CaseBuilder shadows trait CaseBuilder defined in trait Poly; rename the class to something else
[shapeless] [warn] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.16/project-builds/shapeless-8255f881981f2eb014acd91e962b0423d9b26365/core/jvm/target/scala-2.13/src_managed/main/shapeless/polyntraits.scala:57:9: shadowing a nested class of a parent is deprecated but class CaseBuilder shadows trait CaseBuilder defined in trait Poly; rename the class to something else
[shapeless] [warn] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.16/project-builds/shapeless-8255f881981f2eb014acd91e962b0423d9b26365/core/jvm/target/scala-2.13/src_managed/main/shapeless/polyntraits.scala:83:9: shadowing a nested class of a parent is deprecated but class CaseBuilder shadows trait CaseBuilder defined in trait Poly; rename the class to something else
[shapeless] [warn] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.16/project-builds/shapeless-8255f881981f2eb014acd91e962b0423d9b26365/core/jvm/target/scala-2.13/src_managed/main/shapeless/polyntraits.scala:109:9: shadowing a nested class of a parent is deprecated but class CaseBuilder shadows trait CaseBuilder defined in trait Poly; rename the class to something else
[shapeless] [warn] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.16/project-builds/shapeless-8255f881981f2eb014acd91e962b0423d9b26365/core/jvm/target/scala-2.13/src_managed/main/shapeless/polyntraits.scala:135:9: shadowing a nested class of a parent is deprecated but class CaseBuilder shadows trait CaseBuilder defined in trait Poly; rename the class to something else
[shapeless] [warn] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.16/project-builds/shapeless-8255f881981f2eb014acd91e962b0423d9b26365/core/jvm/target/scala-2.13/src_managed/main/shapeless/polyntraits.scala:161:9: shadowing a nested class of a parent is deprecated but class CaseBuilder shadows trait CaseBuilder defined in trait Poly; rename the class to something else
[shapeless] [warn] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.16/project-builds/shapeless-8255f881981f2eb014acd91e962b0423d9b26365/core/jvm/target/scala-2.13/src_managed/main/shapeless/polyntraits.scala:187:9: shadowing a nested class of a parent is deprecated but class CaseBuilder shadows trait CaseBuilder defined in trait Poly; rename the class to something else
[shapeless] [warn] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.16/project-builds/shapeless-8255f881981f2eb014acd91e962b0423d9b26365/core/jvm/target/scala-2.13/src_managed/main/shapeless/polyntraits.scala:213:9: shadowing a nested class of a parent is deprecated but class CaseBuilder shadows trait CaseBuilder defined in trait Poly; rename the class to something else
[shapeless] [warn] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.16/project-builds/shapeless-8255f881981f2eb014acd91e962b0423d9b26365/core/jvm/target/scala-2.13/src_managed/main/shapeless/polyntraits.scala:239:9: shadowing a nested class of a parent is deprecated but class CaseBuilder shadows trait CaseBuilder defined in trait Poly; rename the class to something else
[shapeless] [warn] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.16/project-builds/shapeless-8255f881981f2eb014acd91e962b0423d9b26365/core/jvm/target/scala-2.13/src_managed/main/shapeless/polyntraits.scala:265:9: shadowing a nested class of a parent is deprecated but class CaseBuilder shadows trait CaseBuilder defined in trait Poly; rename the class to something else
[shapeless] [warn] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.16/project-builds/shapeless-8255f881981f2eb014acd91e962b0423d9b26365/core/jvm/target/scala-2.13/src_managed/main/shapeless/polyntraits.scala:291:9: shadowing a nested class of a parent is deprecated but class CaseBuilder shadows trait CaseBuilder defined in trait Poly; rename the class to something else
[shapeless] [warn] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.16/project-builds/shapeless-8255f881981f2eb014acd91e962b0423d9b26365/core/jvm/target/scala-2.13/src_managed/main/shapeless/polyntraits.scala:317:9: shadowing a nested class of a parent is deprecated but class CaseBuilder shadows trait CaseBuilder defined in trait Poly; rename the class to something else
[shapeless] [warn] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.16/project-builds/shapeless-8255f881981f2eb014acd91e962b0423d9b26365/core/jvm/target/scala-2.13/src_managed/main/shapeless/polyntraits.scala:343:9: shadowing a nested class of a parent is deprecated but class CaseBuilder shadows trait CaseBuilder defined in trait Poly; rename the class to something else
[shapeless] [warn] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.16/project-builds/shapeless-8255f881981f2eb014acd91e962b0423d9b26365/core/jvm/target/scala-2.13/src_managed/main/shapeless/polyntraits.scala:369:9: shadowing a nested class of a parent is deprecated but class CaseBuilder shadows trait CaseBuilder defined in trait Poly; rename the class to something else
[shapeless] [warn] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.16/project-builds/shapeless-8255f881981f2eb014acd91e962b0423d9b26365/core/jvm/target/scala-2.13/src_managed/main/shapeless/polyntraits.scala:395:9: shadowing a nested class of a parent is deprecated but class CaseBuilder shadows trait CaseBuilder defined in trait Poly; rename the class to something else
[shapeless] [warn] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.16/project-builds/shapeless-8255f881981f2eb014acd91e962b0423d9b26365/core/jvm/target/scala-2.13/src_managed/main/shapeless/polyntraits.scala:421:9: shadowing a nested class of a parent is deprecated but class CaseBuilder shadows trait CaseBuilder defined in trait Poly; rename the class to something else
[shapeless] [warn [...]