Fix erasure of higher-kinded type aliases
scala/scala pull request #8720
Opened 2020-02-15 18:15 UTC by joroKr21

Don't lose the applied arguments. They might be relevant after all.

Fix scala/bug#11884

2020-02-15 18:17 UTC, joroKr21 commented
I would very interested to know if this will eliminate boxing for certain constructs that make use of abstract types and type aliases 🤔

2020-02-15 18:21 UTC, joroKr21 commented
But also, would it cause binary incompatibilities in libraries?

2020-02-15 18:38 UTC, joroKr21 commented
> I would very interested to know if this would eliminate boxing for certain constructs that make use of abstract types and type aliases 🤔

```scala
scala> :paste
// Entering paste mode (ctrl-D to finish)

trait Tag[T]
object Tag {
  type @@[A, B] <: A with Tag[B]
}

typeOf[Tag.@@[Int, String]].erasure

// Exiting paste mode, now interpreting.

trait Tag
object Tag
val res2: $r.intp.global.Type = Int
```

![](https://www.nicepng.com/png/full/107-1079237_shut-up-and-take-my-money-shut-up.png)

2020-02-16 07:11 UTC, joroKr21 commented
> But also, would it cause binary incompatibilities in libraries?

I assume this could be worked around by adding a `private[foo]` variant with `Object`.

2020-02-17 16:14 UTC, lrytz reviewed
LGTM, but adding Jason as a reviewer because of the potential impact on binary compatibility.

2020-02-21 15:09 UTC, sjrd commented
I can confirm that this PR fixes https://github.com/scala-js/scala-js/issues/3953. :smiley:

2020-02-28 09:20 UTC, joroKr21 commented
Would it make sense to backport to 2.12 and is it too late for that?

2020-02-28 12:50 UTC, lrytz commented
It's too late for 2.12.11 anyway, so let's see first how this change goes in 2.13.

2020-06-06 05:35 UTC, sjrd commented
May I ask what is blocking this PR?

2020-06-07 08:56 UTC, joroKr21 commented
> May I ask what is blocking this PR?

I'm not sure tbh, perhaps the concerns for binary compatibility of libraries compiled with the erasure fix in place.

2020-06-08 10:18 UTC, lrytz commented
@retronym what do you think? The side-effect of this PR is that before:
```
scala> type T[A] <: A
     | def f(x: T[Int]): Int = x
type T
def f(x: T[Int]): Int

scala> :javap f
...
  public int f(java.lang.Object);
    descriptor: (Ljava/lang/Object;)I
```

and after:
```
scala> type T[A] <: A
     | def f(x: T[Int]): Int = x
type T
def f(x: T[Int]): Int

scala> :javap f
...
  public int f(int);
    descriptor: (I)I
```

There's no change if `T` is a type alias (`type T[A] = A`) instead of an abstract type.

2020-06-08 13:12 UTC, smarter requested changes
Am I missing something? Not only does this break binary compatibility between patch versions, which I thought was a big no-no, it also seems like it makes it impossible for dotty to be binary compatible with scalac: when calling a method unpickled from a scalac classfile, we don't know which exact patch version it was compiled with, so we don't know it's binary signature. I'm surprised @sjrd, Defender of ABIs, is OK with this :).

2020-06-08 13:34 UTC, joroKr21 commented
Note that this doesn't break binary compatibility in the standard library but it potentially break it in downstream libraries (e.g. shapeless is one such library). The question is, can binary compatibility be recovered by adding the `Object` version explicitly?

I hadn't thought of Tasty though. Not sure how it works exactly. Isn't the binary signature already in the classfile though?

2020-06-08 13:38 UTC, sjrd commented
TBH I have not really looked at the consequences of this PR. If it indeed breaks the public ABI of code compiled by this fix, I think we should not merge it in a minor release.

Since the workaround hack we have for Scala.js at https://github.com/scala-js/scala-js/pull/3960 changes the type of the params inside the method, aligning with the existing public ABI, I kind of assumed the proper fix on the JVM was doing the same, but apparently not.

I wonder whether a similar good fix for the JVM that would leave the external public ABI intact might exist? Otherwise it seems we'll have no choice but to use our hack on our side.

2020-06-08 13:50 UTC, joroKr21 commented
> Since the workaround hack we have for Scala.js at scala-js/scala-js#3960 changes the type of the params inside the method, aligning with the existing public ABI, I kind of assumed the proper fix on the JVM was doing the same, but apparently not.

I'm not sure how that would look like. I'm not even sure it's necessary for the JVM because it seems to be working fine the way things are right now (apart from boxing but that's unavoidable if we keep `Object` in the signature).

It would be interesting to check the erasure of such types in dotty.

2020-06-08 14:01 UTC, smarter commented
> It would be interesting to check the erasure of such types in dotty.

Note that I'm working on adding a "scala 2 mode" for erasure to deal with the situations where scalac and dotty erase differently (needed because of the very weird way scalac erases intersection types)

2020-06-08 14:07 UTC, sjrd commented
> > Since the workaround hack we have for Scala.js at [scala-js/scala-js#3960](https://github.com/scala-js/scala-js/pull/3960) changes the type of the params inside the method, aligning with the existing public ABI, I kind of assumed the proper fix on the JVM was doing the same, but apparently not.
> 
> I'm not sure how that would look like. I'm not even sure it's necessary for the JVM because it seems to be working fine the way things are right now (apart from boxing but that's unavoidable if we keep `Object` in the signature).

It's working fine on the JVM because the rest of the pipeline completely ignores the `tpe` of the `paramss`. When emitting bytecode, the method descriptor is emitted from the `MethodType`, which has the boxed types. Then when emitting references to the formal params, in the bytecode it's only an index. The JVM itself, when loading the bytecode, infers the type of the params from the descriptor of the method.

But all along, the `tpe` of the `param` symbol has been wrong in the sense that it wasn't in sync with what the `MethodType` says. This triggers an issue in Scala.js because Scala.js does care about the `tpe` of the params.

So in scalac, what it would look like would be to amend the `tpe` of the `paramss` so that it indeed matches what the `MethodType` says.

2020-06-09 13:34 UTC, joroKr21 commented
> So in scalac, what it would look like would be to amend the tpe of the paramss so that it indeed matches what the MethodType says.

But isn't that the case with all symbols? I don't see erasure modifying the info of any symbols. It only sets the `tpt` of trees.

2020-06-09 15:12 UTC, sjrd commented
Erasure, and a lot of phases, certainly do change the `info` of symbols:
```scala
$ ~/opt/scala-2.13.2/bin/scala 
Welcome to Scala 2.13.2 (OpenJDK 64-Bit Server VM, Java 1.8.0_252).
Type in expressions for evaluation. Or try :help.

scala> class Foo[A](val x: A)
class Foo

scala> :power
Power mode enabled. :phase is at typer.
import scala.tools.nsc._, intp.global._, definitions._
Try :help or completions for vals._ and power._

scala> typeOf[Foo[_]].decl(TermName("x"))
val res1: $r.intp.global.Symbol = value x

scala> res1.info
val res2: $r.intp.global.Type = A

scala> exitingErasure { res1.info }
val res4: $r.intp.global.Type = (): Object
```

2020-06-15 21:16 UTC, SethTisue commented
we want to build 2.13.3 this week and it seems the path forward here isn't fully clear yet, so I've re-milestoned it for consideration for 2.13.4

2020-08-03 12:53 UTC, joroKr21 commented
`uncurry` is the phase that dealiases - if we don't want to fix erasure, what do you suggest?

2020-08-03 14:48 UTC, joroKr21 commented
After looking closer at `uncurry` I am now convinced that method signatures are dealiased *before* `erasure` and therefore this should not pose a big problem for binary compatibility after all. But I will submit an alternative PR that makes `uncurry` dealias more consistently.

2020-10-07 15:21 UTC, SethTisue commented
note that #9149 has recent discussion — 15 days ago

2020-10-07 15:22 UTC, dwijnand commented
Drafting while review/progress in #9149 is ongoing.

2020-10-09 09:25 UTC, lrytz commented
I think we can close this one, the change in binary compatibility is not safe for 2.13.x.

2020-10-09 09:25 UTC, closed without merging