Fix dinosaur name
scala/scala pull request #9092
Opened 2020-06-29 20:30 UTC by janekdb

2020-06-29 20:33 UTC, janekdb commented
No merge yet!

I need to

* Squash commits
* Self review

Plus I'm being lazy and running the build for the first time in this PR!

2020-06-29 21:15 UTC, SethTisue requested changes
commented on one needed fix, otherwise LGTM! 🦕❤️

2020-06-29 21:15 UTC, SethTisue commented on test/junit/scala/tools/nsc/typechecker/InferencerTest.scala
> +<<<<<<< d86afea18a973dcf3489944edd9e337997dd35ea:test/junit/scala/tools/nsc/typechecker/InferencerTest.scala
whoops, a merge conflict crept in here

2020-06-29 21:15 UTC, SethTisue commented
> No merge yet!

(GitHub's "draft" feature is good for this.)

2020-06-29 21:39 UTC, janekdb reviewed
> > No merge yet!
> 
> (GitHub's "draft" feature is good for this.)

Didn't know about "draft" feature - I will check it out!

2020-06-29 21:39 UTC, janekdb commented on test/junit/scala/tools/nsc/typechecker/InferencerTest.scala
> +<<<<<<< d86afea18a973dcf3489944edd9e337997dd35ea:test/junit/scala/tools/nsc/typechecker/InferencerTest.scala
Opps!

2020-06-30 06:50 UTC, lrytz commented on test/files/run/finally.scala
> -      case e: Throwable => println("COUGHT: " + e)
🤧

2020-06-30 21:03 UTC, janekdb commented on test/files/run/finally.scala
> -      case e: Throwable => println("COUGHT: " + e)
Bless you!

2020-06-30 21:08 UTC, janekdb commented on test/junit/scala/tools/nsc/typechecker/InferencerTest.scala
> +<<<<<<< d86afea18a973dcf3489944edd9e337997dd35ea:test/junit/scala/tools/nsc/typechecker/InferencerTest.scala
Fixed.

2020-06-30 21:10 UTC, janekdb commented
I've addressed all the comments and do not have any else to do on this. If this passes CI then give it a review!

2020-06-30 21:14 UTC, janekdb commented on test/junit/scala/tools/nsc/typechecker/InferencerTest.scala
> +<<<<<<< d86afea18a973dcf3489944edd9e337997dd35ea:test/junit/scala/tools/nsc/typechecker/InferencerTest.scala
Fixed.

2020-07-01 20:39 UTC, som-snytt commented on src/compiler/scala/tools/nsc/backend/jvm/opt/CallGraph.scala
> +          // when inlining non-static callsites. However, LocalOpt's nullness cleanup will also do
`καλλίστη`

2020-07-01 20:45 UTC, som-snytt commented on test/files/run/OrderingTest.scala
> +  assert(Ordering[String].compare("australopithecus", "brontosaurus") < 0)
`"apatosaurus"` and `>`.

2020-07-01 20:46 UTC, som-snytt commented on test/files/run/finally.scala
> -      case e: Throwable => println("COUGHT: " + e)
Very pandemic!

2020-07-01 20:51 UTC, SethTisue approved these changes

2020-07-01 20:51 UTC, merged

2020-07-01 20:51 UTC, SethTisue commented
thank you Janek!