Backport 2.13.x Set/Map test and fix regression in HashMapBuilder
scala/scala pull request #9229
Opened 2020-10-02 00:18 UTC by retronym

In #8726, the optimization to HashMapBuilder fails to overwrite a value
if the existing value is `==` to it. Map implementations should only
call `==` on keys and never on values.

This PR does not go further to align other collections with 2.13.x
rules for preserving existing keys on updates.

2020-10-02 22:22 UTC, mkeskells requested changes

2020-10-02 22:22 UTC, mkeskells commented on src/library/scala/collection/immutable/HashMap.scala
> +            else new HashMap1(this.key, hash, value, null)
we should use `kv` if we can. I agree the previous was wrong, but how about
```
  // preserve kv if we can. We know that kv matches key and value
  // and we know if kv ne null that the value is eq, so if the key is also eq 
  // then we can retain the tuple
 else new HashMap1(this.key, hash, value, if (this.key.asInstanceOf[AnyRef] eq key.asInstanceOf[AnyRef]) kv else null)`

2020-10-02 22:22 UTC, mkeskells commented on src/library/scala/collection/immutable/HashMap.scala
> +        val nkv = if ((kv ne null) && (kv._1.asInstanceOf[AnyRef] eq this.key.asInstanceOf[AnyRef])) kv else null
This change look wrong to me, and the original looked correct
This is the case where the hashes don't match (as I see it) so `kv._1` is unrelated to `this.key`

As I see it this would cause a corruption in the tree, as the new value would be lost
so - conceptually 
```
val previous = HashMap1(hash1, "a", "A")
val result = previous.updated("b", "B")
//which calls previous.updated(hash2, "b", "B", null, null)
```
this would give us a 
HashTrieMap containing 
previous and HashMap1(hash2, "a", "B")
and should be 
previous and HashMap1(hash2, **"b",** "B")

I guess there isn't a  test for that, or I am misreading the code

2020-10-02 22:22 UTC, mkeskells commented on src/library/scala/collection/immutable/Map.scala
>          elems.get(elem._1) match {
The change that you mane is better that the original ...but 

It looks to me like the new and old code don't cope with a different value in the map for the same key, and convert to a hashMapBuilder when we could still use a Map4.
Also we could remove the creation of a `Some` via use of a `getOrElse`

something like

in object Map
```
private val flag = new AbstractFunction0[Any, Any] {
  def apply() = flag
}
```
and here 
```
val valueOrFlag = elems.getOrElse(elem._1, Map.flag).asInstanceOf[AnyRef]
if (valueOrFlag eq Map.flag) {
  //its a new key
 convertToHashMapBuilder()
 hashMapBuilder += elem
} else if (valueOrFlag ne elem._2.asInstanceOf[AnyRef]) 
  // its an existing key with a new value 
  elems = elems + elem
//else as key is == and value is eq, its no change
```

2020-10-02 22:26 UTC, mkeskells commented on test/junit/scala/collection/SetMapRulesTest.scala
> +class SetMapRulesTest {
👍
new tests - Looks like I have some reading and understanding to do!

2020-10-05 01:58 UTC, retronym commented
/rebuild

2020-10-05 07:10 UTC, retronym commented on src/library/scala/collection/immutable/HashMap.scala
> +            else new HashMap1(this.key, hash, value, null)
Agreed, it ought to be `if (this.key eq key) kv else null`.

2020-10-05 08:19 UTC, mkeskells approved these changes
LGTM

2020-10-07 12:31 UTC, lrytz approved these changes

2020-10-07 16:06 UTC, merged