remove null to executionContext.global
scala/scala pull request #9245
Opened 2020-10-13 11:53 UTC by YuMuuu

I wondered use a null value to executionContext.global 
argument.
And match null for `impl.ExecutionContextImpl.fromExecutor(null: Executor)`

I thought it could be improved.

2020-10-14 10:30 UTC, viktorklang commented on src/library/scala/concurrent/impl/ExecutionContextImpl.scala
> +      new ExecutionContextImpl(es, reporter) with ExecutionContextExecutorService {
Might be worth throwing an IllegalArgumentException if `es` is `null` here.

2020-10-14 10:30 UTC, viktorklang commented on src/library/scala/concurrent/impl/ExecutionContextImpl.scala
> +    new ExecutionContextImpl(e, reporter)
Might be worth throwing an IllegalArgumentException if `es` is `null` here.

2020-10-14 10:31 UTC, viktorklang requested changes
LGTM after comments

2020-10-14 10:39 UTC, YuMuuu commented
@viktorklang 
thank you for reply.
I fix failed tests (sry T_T) and correct the review content.

2020-10-15 16:28 UTC, som-snytt commented
I don't have an actual opinion, but I was surprised by Viktor's OK, because of compatibility. Previously, I have wished for an easy API to "get the default context." I remember thinking that "give me null" is suboptimal. Anything that requires saying `concurrent.impl` is no longer API. I'm too lazy to figure out if the change means "I used to supply a null, but now I must reference impl.something."

2020-10-15 19:06 UTC, viktorklang commented
@som-snytt My reason for the OK was that `object ExecutionContextImpl` is `private[concurrent]`.

2020-10-19 00:41 UTC, YuMuuu commented
The job exceeded the maximum time limit for jobs, and has been terminated. 🤔

2020-10-19 06:56 UTC, viktorklang commented on test/files/jvm/future-spec/FutureTests.scala
> +      val ec: ExecutionContextExecutorService = ExecutionContext.global
You can't use global here—the test shuts down the newly created `ec`.

2020-10-19 06:56 UTC, viktorklang commented on test/files/jvm/future-spec/FutureTests.scala
> +      val ec: ExecutionContextExecutorService = ExecutionContext.global
See line 239

2020-11-22 18:50 UTC, SethTisue commented
@YuMuuu interested in returning to this?

2021-01-06 16:44 UTC, SethTisue commented
@YuMuuu second ping, interested in returning to this?

2021-01-07 01:31 UTC, YuMuuu commented
@SethTisue Sorry. I forgot that I was an softrware engineer. I do it.

2021-01-26 17:15 UTC, SethTisue commented
closing for inactivity, but there's no intent to discourage from progressing, we can reopen anytime

2021-01-26 17:15 UTC, closed without merging