Remove flaky foldRightAllocations test
scala/scala pull request #9278
Opened 2020-10-26 20:25 UTC by dwijnand

Fixes https://github.com/scala/scala-dev/issues/727

Fixes to make reinstate it non-flaky are welcome, but meanwhile the cost of the test failure is too high to keep the it IMO.

2020-10-26 21:33 UTC, SethTisue commented
fyi @mkeskells — it's notoriously hard to test this kind of thing

2020-10-26 21:40 UTC, SethTisue approved these changes
`exactAllocates` is not unique to this test, so I don't know why this particular test would be especially prone to expose a flaw in it. but in any case, yes, deleting it, at least for now, is what we should do

2020-10-27 07:58 UTC, mkeskells commented
It looks not to be an issue with the test /infra counting itself, just that the JIT is optimising away the allocation ( its allocating 0 rather than 72 bytes). we could change the call to `exactAllocates` to `onlyAllocates`
That does the same, but enforces an upper limit on the allocation
As such it doesn't enforce the ratcheting of the values down, but that can be done by other means (periodically, manually)

It would be good to know what is different in 2.13 to make this happen (to encorage this elsewhere) @retronym (as the JitWatch expert :-) ) is JitWatch the best way to find out by the JIT did the right thing here

2020-10-27 08:00 UTC, mkeskells requested changes

2020-10-27 08:00 UTC, mkeskells commented on test/junit/scala/collection/immutable/ListMapTest.scala
> -    assertEquals("(1,1)XX", exactAllocates(tuples(m.size))(m.foldRight(acc.reset)(acc)))
can we just change the call from `exactAllocates` to `onlyAllocates`

2020-10-28 18:30 UTC, merged