delete temp dirs made by tastytest
scala/scala pull request #9389
Opened 2020-12-14 16:01 UTC by bishabosha

using `scala.reflect.io.Directory` to delete a directory recursively.

If a temp directory is required by tastytest, add the automatic cleanup of that directory after creation.

I thought it was not critical if there is a problem in cleaning up the temp directory, so if the temp directory is not fully deleted then the test will still pass, perhaps we want to change that?

2020-12-14 17:19 UTC, som-snytt commented
I tried to use `Using`, but Windows doesn't like deleting dirs it thinks are "in use".

https://github.com/scala/scala/blob/2.13.x/src/testkit/scala/tools/testkit/TempDir.scala#L46

I didn't arrive at a strategy for coping with this issue.

2020-12-17 08:11 UTC, dwijnand requested changes
I don't gather from your description, Jamie, you're addressing an existing problem, but just adding some clean up.  If so, then I'd rather not risk this starting to fail on Windows.  Could you look to avoid that?  I'm not sure if testkit is reachable in tastytest, but ideally we don't need to duplicate.

2020-12-23 17:12 UTC, bishabosha commented
> I don't gather from your description, Jamie, you're addressing an existing problem, but just adding some clean up.

This PR is just meant to clean up temporary directories that are created to store all the classfiles and tasty generated by TastyTest each time the CI is ran.

If there is no issue of storage being consumed on the CI then feel free to close this, otherwise I was not aware of potential issues with deleting files on windows

2020-12-23 17:19 UTC, closed without merging

2020-12-23 20:21 UTC, som-snytt commented
I'll resubmit this when I get a chance. Maybe during the eggnoggy period between Xmas and New Year's, or possibly Pentecost. Pentecost is when the cost of all that pent-up shopping comes due.