restore SubstMap's unsealed status
scala/scala pull request #9630
Opened 2021-05-13 14:42 UTC by SethTisue

it was recently sealed (by #9363), but in the community build we
saw that Scalafix has their own subclass (in CompilerTypePrinter)

2021-05-13 14:45 UTC, SethTisue commented
this came up at https://github.com/scala/community-build/pull/1413

the Scalafix code in question is https://github.com/scalacenter/scalafix/blob/6c9eeec9bc99522dc2073ae54290488c6d06401f/scalafix-rules/src/main/scala/scalafix/internal/rule/CompilerTypePrinter.scala#L138-L153

@som-snytt is there a downside to just unsealing it?

2021-05-13 15:11 UTC, som-snytt commented
The previous PR renamed `SubstMap` to `AbstractSubstMap`, and my PR renamed it back and rejiggered the internals of `reload`.

Oh, I see the scalafix uses `SubstSymMap`, which was sealed to handle the `reload` dance at creation.

I'll take a second look.

2021-05-13 15:12 UTC, dwijnand approved these changes
Shame, it's internal but this was a side nice-to-have.

2021-05-13 15:15 UTC, dwijnand requested changes, later dismissed
Ah, Som's right, this would make Scalafix's SubstSymMap not be correctly instantiated.

2021-05-13 15:22 UTC, som-snytt commented
I should have said, I'll take a look in a second. I was going to skip morning coffee, but I guess I won't.

Sorry for the hassle.

2021-05-14 16:48 UTC, SethTisue commented
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2750/ will see if this makes Scalafix happy again. if it does, let's merge this and do a full community build run

2021-05-14 18:07 UTC, merged

2021-05-14 18:50 UTC, som-snytt commented
Thanks for furthering it. I still had a tab open.